---
apiVersion: v2
name: gitlab
version: 10.2.1
appVersion: master
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
keywords:
- gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
dependencies:
- name: gitlab
  version: "*.*.*"
- name: certmanager-issuer
  version: "*.*.*"
- name: registry
  version: "*.*.*"
- name: cert-manager
  version: v1.21.1
  repository: oci://quay.io/jetstack/charts
  condition: installCertmanager
  alias: certmanager
- name: prometheus
  version: 29.17.0
  repository: oci://ghcr.io/prometheus-community/charts
  condition: prometheus.install
- name: gitlab-runner
  version: 0.91.0
  repository: https://charts.gitlab.io/
  condition: gitlab-runner.install
- name: nginx-ingress
  condition: nginx-ingress.enabled
  version: "*.*.*"
- name: nginx-ingress
  condition: nginx-ingress-geo.enabled
  version: "*.*.*"
  alias: nginx-ingress-geo
- name: gitlab-zoekt
  version: 4.1.0
  repository: https://charts.gitlab.io/
  condition: gitlab-zoekt.install
- name: openbao
  version: 0.17.0
  repository: https://charts.gitlab.io/
  condition: openbao.install
- name: traefik
  repository: https://helm.traefik.io/traefik
  condition: traefik.install
  version: 10.19.4
- name: kubernetes-ingress
  alias: haproxy
  version: 1.39.4
  condition: haproxy.install
  repository: https://haproxytech.github.io/helm-charts
- name: gateway-helm
  alias: envoy-gateway
  repository: oci://registry-1.docker.io/envoyproxy
  version: 1.8.3
  condition: global.gatewayApi.installEnvoy
- name: ai-gateway
  version: 0.15.1
  repository: https://gitlab.com/api/v4/projects/gitlab-org%2fcharts%2fai-gateway-helm-chart/packages/helm/devel
  condition: ai-gateway.install
