---
apiVersion: v2
name: gitlab
version: 9.3.1
appVersion: master
description: GitLab is the most comprehensive AI-powered DevSecOps Platform.
keywords:
- gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
dependencies:
- name: gitlab
  version: "*.*.*"
- name: certmanager-issuer
  version: "*.*.*"
- name: minio
  version: "*.*.*"
- name: registry
  version: "*.*.*"
- name: cert-manager
  version: v1.17.4
  repository: https://charts.jetstack.io/
  condition: installCertmanager
  alias: certmanager
- name: prometheus
  version: 27.23.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.install
- name: postgresql
  version: 13.4.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.install
- name: gitlab-runner
  version: 0.80.0
  repository: https://charts.gitlab.io/
  condition: gitlab-runner.install
- name: redis
  version: 18.19.4
  repository: https://charts.bitnami.com/bitnami
  condition: redis.install
- name: nginx-ingress
  condition: nginx-ingress.enabled
  version: "*.*.*"
- name: nginx-ingress
  condition: nginx-ingress-geo.enabled
  version: "*.*.*"
  alias: nginx-ingress-geo
- name: gitlab-zoekt
  version: 3.2.0
  repository: https://charts.gitlab.io/
  condition: gitlab-zoekt.install
- name: openbao
  version: 0.5.1
  repository: https://charts.gitlab.io/
  condition: openbao.install
- name: traefik
  repository: https://helm.traefik.io/traefik
  condition: traefik.install
  version: 10.19.4
- name: kubernetes-ingress
  alias: haproxy
  version: 1.39.4
  condition: haproxy.install
  repository: https://haproxytech.github.io/helm-charts
