[tools]
kubectl = "1.35.3"
minikube = "1.38.1"
helm = "4.2.0"
stern = "1.23.0"
yq = "4.53.2"
gomplate = "5.0.0"

# For linting documentation
markdownlint-cli2 = "0.22.1"
lychee = "0.24.2"
vale = "3.14.1"
