[tools]
kubectl = "1.35.1"
minikube = "1.29.0"
helm = "4.1.1"
stern = "1.23.0"
yq = "4.52.4"
gomplate = "5.0.0"

# For linting documentation
markdownlint-cli2 = "0.19.0"
lychee = "0.21.0"
vale = "3.13.0"
