# frozen_string_literal: true

MESSAGE = <<REV_EOF
If this is a wider community contribution, the ~"Community contribution" label should be added.

When requesting a review, it's recommended that you pick the reviewer suggested by the reviewer roulette, but you can pick someone else if you see fit. Community contributors can comment `@gitlab-bot ready <@user>` to request a review.

Merge requests should receive a response within the limit documented in the [Review-response SLO](https://handbook.gitlab.com/handbook/engineering/workflow/code-review/#review-response-slo).

If you don't receive a response from the reviewer within the SLO, please mention `@gitlab-org\/software-delivery\/operate`, or one of our [Project Maintainers](https://handbook.gitlab.com/handbook/engineering/projects/#gitlab-chart)
REV_EOF

# Print maintainers message
message(MESSAGE)
