# Need to set certmanager-issuer.email before templating
certmanager-issuer:
  email: me@example.com

# YAML anchor to demonstrate setting image.repository and image.tag
.custom: &custom
  image:
    repository: custom-repository
    tag: 1.2.3-example

# --- Global settings ---

global:
  <<: *custom
  kubectl: *custom
  certificates: *custom
  gitlabBase: *custom

# --- GitLab charts ---

gitlab:
  geo-logcursor: *custom
  gitaly:
    <<: *custom
    init: *custom
  gitlab-exporter:
    <<: *custom
    init: *custom
  gitlab-shell:
    <<: *custom
    init: *custom
  mailroom: *custom
  migrations:
    <<: *custom
    init: *custom
  sidekiq:
    <<: *custom
    init: *custom
  toolbox:
    <<: *custom
    init: *custom
  webservice:
    <<: *custom
    init: *custom
    workhorse:
      image: custom-repository
      tag: custom-tag

certmanager:
  <<: *custom
  cainjector: *custom

gitlab-runner:
  image:
    image: custom-repository
    tag: custom-tag

nginx-ingress:
  controller: *custom

registry:
    <<: *custom
    init: *custom

prometheus:
  server: *custom
  configmapReload: *custom

upgradeCheck: *custom
