nginx-ingress:
  controller:
    electionID: "$RELEASE_NAME-nginx-election"
    ingressClassByName: true
    controllerValue: "ci.gitlab.com/$RELEASE_NAME"

global:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "10"
    tls:
      secretName: helm-charts-win-tls
    configureCertmanager: false