{{/*
Returns the secret name of AI Gateway/Duo signing key.
This secret will be generated by shared secrets.
*/}}
{{- define "gitlab.ai-gateway.signing.secret" -}}
{{- printf "%s-ai-gateway-signing-secret" .Release.Name -}}
{{- end -}}

{{/*
Returns the secret key of AI Gateway/Duo signing key.
This key matches the expected AIGW envionment variable.
*/}}
{{- define "gitlab.ai-gateway.signing.key" -}}
DUO_WORKFLOW_SELF_SIGNED_JWT__SIGNING_KEY
{{- end -}}

{{/*
Returns the AI Gateway URL.
*/}}
{{- define "gitlab.ai-gateway.url" -}}
{{- $scheme := or .Values.global.hosts.https .Values.global.hosts.aiGateway.https | ternary "https" "http" -}}
{{- $host := (include "gitlab.ai-gateway.hostname" .) -}}
{{- printf "%s://%s" $scheme $host -}}
{{- end -}}

{{/*
Returns the AI Gateway host.
*/}}
{{- define "gitlab.ai-gateway.hostname" -}}
{{- coalesce .Values.global.hosts.aiGateway.name (include "gitlab.assembleHost"  (dict "name" "aigw" "context" . )) -}}
{{- end -}}

{{/*
Renders if the AI Gateway Ingress should be enabled.
Behaves similar to "gitlab.ingress.enabled" but checks for the local `gitlabIngress`
because AI Gateway has currently two Ingress configurations.
*/}}
{{- define "gitlab.ai-gateway.ingress.enabled" -}}
{{- $globalSet := and (hasKey .Values.global.ingress "enabled") (kindIs "bool" .Values.global.ingress.enabled) -}}
{{- $localSet := and (hasKey .Values.gitlabIngress "enabled") (kindIs "bool" .Values.gitlabIngress.enabled) -}}
{{- if $localSet }}
{{-   .Values.gitlabIngress.enabled }}
{{- else if $globalSet }}
{{-  .Values.global.ingress.enabled }}
{{- else }}
{{-   true }}
{{- end -}}
{{- end -}}

{{/*
Renders if the AI Gateway Ingress should use TLS.
Behaves similar to "gitlab.ingress.tls.enabled" but checks for the local `gitlabIngress`
because AI Gateway has currently two Ingress configurations.
*/}}
{{- define "gitlab.ai-gateway.ingress.tls.enabled" -}}
{{- if (((.Values).gitlabIngress).tls).enabled }}
{{-   .Values.gitlabIngress.tls.enabled }}
{{- else }}
{{-   include "gitlab.global.ingress.tls.enabled" . }}
{{- end -}}
{{- end -}}

