apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab.nginx.template.configmap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
data:
  nginx.tpl: |-
    {{- .Files.Get "nginx/nginx.tpl" | nindent 4 }}
