#!/bin/bash

# Sets up the GitLab chart's external dependencies (PostgreSQL, Valkey, Garage)
# for local chart development, using the gitlab-dev-stack umbrella chart. This
# is the same mechanism CI uses — see scripts/ci/lib/dev_stack.sh.

set -eo pipefail
[[ "${TRACE}" ]] && set -x

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPTS_DIR}/.."
VALUES_DIR="${PROJECT_ROOT}/.values"

# dev_stack.sh resolves its values template relative to SCRIPT_DIR, which for
# it means scripts/ci.
SCRIPT_DIR="${SCRIPTS_DIR}/ci"

# Source CI library functions for shared logic and naming conventions.
source "${SCRIPT_DIR}/lib/helpers.sh"
source "${SCRIPT_DIR}/lib/dev_stack.sh"

NAMESPACE="${NAMESPACE:-gitlab}"

# Versions come from .gitlab-ci.yml so a local stack matches CI's. Override
# any of them to try a bump before changing CI.
DEV_STACK_CHART_VERSION="${DEV_STACK_CHART_VERSION:-$(ci_variable DEV_STACK_CHART_VERSION)}"
CNPG_CHART_VERSION="${CNPG_CHART_VERSION:-$(ci_variable CNPG_CHART_VERSION)}"
CNPG_POSTGRESQL_TAG="${CNPG_POSTGRESQL_TAG:-$(ci_variable CNPG_POSTGRESQL_TAG)}"
GARAGE_APP_VERSION="${GARAGE_APP_VERSION:-$(ci_variable GARAGE_APP_VERSION)}"

GENERATED_VALUES="${VALUES_DIR}/dev-external.values.yaml"

function check_prerequisites() {
  for tool in kubectl helm envsubst yq; do
    if ! command -v "${tool}" > /dev/null 2>&1; then
      echo "ERROR: ${tool} is required but not installed."
      echo "See doc/development/environment_setup.md for guidance."
      exit 1
    fi
  done
}

function ensure_namespace() {
  kubectl get namespace "${NAMESPACE}" > /dev/null 2>&1 \
    || kubectl create namespace "${NAMESPACE}"
  echo "    Namespace: ${NAMESPACE}"
}

# Renders the chart-side overlay that wires GitLab to the umbrella release.
# Same template CI layers into every deploy, so a local chart install matches
# what review environments get.
function generate_values_file() {
  mkdir -p "${VALUES_DIR}"

  {
    echo "# Generated by scripts/dev_dependencies.sh - do not commit this file."
    echo "# Use this values file when deploying the GitLab chart locally."
    echo "# See doc/development/external-dependencies.md for usage."
    echo ""
    env \
      DEV_STACK_RELEASE_NAME="$(dev_stack_release_name)" \
      NAMESPACE="${NAMESPACE}" \
        envsubst < "${SCRIPT_DIR}/values/gitlab-chart/dev-stack.values.yaml"
  } > "${GENERATED_VALUES}"

  echo "    Generated values file: ${GENERATED_VALUES}"
}

# Commands
function cmd_setup() {
  echo "Setting up external dependencies in namespace '${NAMESPACE}'..."
  echo ""
  check_prerequisites
  ensure_namespace

  echo "==> Setting up gitlab-dev-stack (PostgreSQL, Valkey, Garage)..."
  deploy_dev_stack

  generate_values_file

  echo ""
  echo "==> All external dependencies are ready."
  echo ""
  echo "Deploy the GitLab chart and use '.values/dev-external.values.yaml' for connecting to PostgreSQL, Valkey and Garage."
  echo "See doc/development/external-dependencies.md for more details."
}

function cmd_teardown() {
  echo "Removing external dependencies from namespace '${NAMESPACE}'..."
  echo ""
  remove_dev_stack
  rm -f "${GENERATED_VALUES}"
  echo ""
  echo "==> External dependencies removed."
  echo ""
  echo "The namespace '${NAMESPACE}' and GitLab chart release are not affected."
  echo "Run 'helm uninstall gitlab --namespace ${NAMESPACE}' to remove GitLab as well."
}

function cmd_status() {
  local release
  release="$(dev_stack_release_name)"

  echo "External dependency status in namespace '${NAMESPACE}':"
  echo ""

  echo "--- gitlab-dev-stack release (${release}) ---"
  helm status "${release}" --namespace "${NAMESPACE}" --show-resources 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- CloudNativePG operator ($(cnpg_operator_release_name)) ---"
  kubectl get deployment \
    --namespace "${NAMESPACE}" \
    -l "app.kubernetes.io/instance=$(cnpg_operator_release_name)" 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- PostgreSQL clusters ---"
  kubectl get cluster --namespace "${NAMESPACE}" 2>/dev/null \
    || echo "  Not found"

  echo ""
  echo "--- Connection secrets ---"
  for secret in \
    "${release}-gitlab-gitlabhq-production-conn" \
    "${release}-gitlab-registry-conn" \
    "${release}-valkey-conn" \
    "${release}-garage-conn"; do
    kubectl get secret --namespace "${NAMESPACE}" "${secret}" \
      -o jsonpath="  {.metadata.name}: present{'\n'}" 2>/dev/null \
      || echo "  ${secret}: not found"
  done
}

function usage() {
  cat <<EOF
Usage: $0 {setup|teardown|status}

  setup    Deploy PostgreSQL, Valkey, and Garage via the gitlab-dev-stack chart.
  teardown Remove the deployed external dependencies (does not remove the GitLab release).
  status   Show the current status of the external dependencies.

Environment variables:
  NAMESPACE               Kubernetes namespace to use (default: gitlab)

The versions below default to the matching \`variables:\` entry in
.gitlab-ci.yml; the current values are shown in parentheses.

  DEV_STACK_CHART_VERSION gitlab-dev-stack chart version (${DEV_STACK_CHART_VERSION})
  CNPG_CHART_VERSION      CloudNativePG operator chart version (${CNPG_CHART_VERSION})
  CNPG_POSTGRESQL_TAG     PostgreSQL image tag for the CNPG cluster (${CNPG_POSTGRESQL_TAG})
  GARAGE_APP_VERSION      Garage version to install (${GARAGE_APP_VERSION})

See doc/development/external-dependencies.md for full documentation.
EOF
  exit 1
}

case "${1:-}" in
  setup)    cmd_setup ;;
  teardown) cmd_teardown ;;
  status)   cmd_status ;;
  *)        usage ;;
esac
