gitlab:
  webservice:
    minReplicas: 1    # 2
    maxReplicas: 1    # 10
  sidekiq:
    minReplicas: 1    # 1
    maxReplicas: 1    # 10
  gitlab-shell:
    minReplicas: 1    # 2
    maxReplicas: 2    # 10
  toolbox:
    enabled: true
nginx-ingress:
  controller:
    replicaCount: 1   # 2
redis:
  resources:
    requests:
      cpu: 100m
minio:
  resources:
    requests:
      cpu: 100m