global:
  appConfig:
    object_store:
      enabled: true
      proxy_download: true
      connection:
        secret: "${GARAGE_RELEASE_NAME}-gitlab-object-storage"
        key: config
    artifacts:
      bucket: gitlab-artifacts
    lfs:
      bucket: git-lfs
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    externalDiffs:
      enabled: true
      bucket: gitlab-mr-diffs
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
    agentPlanContent:
      enabled: true
      bucket: gitlab-agent-plan-content
    dependencyProxy:
      enabled: true
      bucket: gitlab-dependency-proxy

gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: "${GARAGE_RELEASE_NAME}-gitlab-object-storage-s3cmd"
          key: config

registry:
  storage:
    secret: "${GARAGE_RELEASE_NAME}-gitlab-registry-storage"
    key: config
    redirect:
      disable: true
