nginx-ingress:
  enabled: true
  controller:
    electionID: "${GITLAB_RELEASE_NAME}-nginx-election"
    ingressClassByName: true
    ingressClassResource:
      controllerValue: "ci.gitlab.com/${GITLAB_RELEASE_NAME}"

global:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "10"
    tls:
      secretName: helm-charts-win-tls
    configureCertmanager: false

  gatewayApi:
    enabled: false
    installEnvoy: false
    configureCertmanager: false
