// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/certmanager_issuer.proto

package valuesv1

import (
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertmanagerIssuerValues is the top-level schema for the certmanager-issuer
// sub-chart values.yaml. It configures an ACME Issuer in cert-manager, only
// used when global.ingress.configureCertmanager is true.
type CertmanagerIssuerValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ACME directory server URL used by the Issuer.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Email to associate with issued TLS certificates.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// RBAC settings for the issuer.
	Rbac *CertmanagerIssuerRbac `protobuf:"bytes,3,opt,name=rbac,proto3" json:"rbac,omitempty"`
	// Pod resource requests and limits (opaque passthrough).
	Resources *structpb.Struct `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	// Priority class assigned to pods.
	PriorityClassName string `protobuf:"bytes,5,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Container-level security context (opaque passthrough).
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,6,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// Common settings shared across rendered resources.
	Common *CertmanagerIssuerCommon `protobuf:"bytes,7,opt,name=common,proto3" json:"common,omitempty"`
	// Whether to use the new Ingress mechanism for certificate provisioning.
	UseNewIngressForCerts bool `protobuf:"varint,8,opt,name=use_new_ingress_for_certs,json=useNewIngressForCerts,proto3" json:"use_new_ingress_for_certs,omitempty"`
	// Seconds to retain the completed Job before cleanup.
	TtlSecondsAfterFinished uint32 `protobuf:"varint,9,opt,name=ttl_seconds_after_finished,json=ttlSecondsAfterFinished,proto3" json:"ttl_seconds_after_finished,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CertmanagerIssuerValues) Reset() {
	*x = CertmanagerIssuerValues{}
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertmanagerIssuerValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertmanagerIssuerValues) ProtoMessage() {}

func (x *CertmanagerIssuerValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertmanagerIssuerValues.ProtoReflect.Descriptor instead.
func (*CertmanagerIssuerValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_certmanager_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *CertmanagerIssuerValues) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *CertmanagerIssuerValues) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CertmanagerIssuerValues) GetRbac() *CertmanagerIssuerRbac {
	if x != nil {
		return x.Rbac
	}
	return nil
}

func (x *CertmanagerIssuerValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CertmanagerIssuerValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *CertmanagerIssuerValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *CertmanagerIssuerValues) GetCommon() *CertmanagerIssuerCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CertmanagerIssuerValues) GetUseNewIngressForCerts() bool {
	if x != nil {
		return x.UseNewIngressForCerts
	}
	return false
}

func (x *CertmanagerIssuerValues) GetTtlSecondsAfterFinished() uint32 {
	if x != nil {
		return x.TtlSecondsAfterFinished
	}
	return 0
}

// CertmanagerIssuerRbac controls RBAC resource creation.
type CertmanagerIssuerRbac struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to create RBAC resources.
	Create        bool `protobuf:"varint,1,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertmanagerIssuerRbac) Reset() {
	*x = CertmanagerIssuerRbac{}
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertmanagerIssuerRbac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertmanagerIssuerRbac) ProtoMessage() {}

func (x *CertmanagerIssuerRbac) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertmanagerIssuerRbac.ProtoReflect.Descriptor instead.
func (*CertmanagerIssuerRbac) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_certmanager_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *CertmanagerIssuerRbac) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

// CertmanagerIssuerCommon holds settings shared across rendered resources.
type CertmanagerIssuerCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Additional labels applied to resources (opaque passthrough).
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertmanagerIssuerCommon) Reset() {
	*x = CertmanagerIssuerCommon{}
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertmanagerIssuerCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertmanagerIssuerCommon) ProtoMessage() {}

func (x *CertmanagerIssuerCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_certmanager_issuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertmanagerIssuerCommon.ProtoReflect.Descriptor instead.
func (*CertmanagerIssuerCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_certmanager_issuer_proto_rawDescGZIP(), []int{2}
}

func (x *CertmanagerIssuerCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_charts_values_v1_certmanager_issuer_proto protoreflect.FileDescriptor

const file_charts_values_v1_certmanager_issuer_proto_rawDesc = "" +
	"\n" +
	")charts/values/v1/certmanager_issuer.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x82\x04\n" +
	"\x17CertmanagerIssuerValues\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12;\n" +
	"\x04rbac\x18\x03 \x01(\v2'.charts.values.v1.CertmanagerIssuerRbacR\x04rbac\x125\n" +
	"\tresources\x18\x04 \x01(\v2\x17.google.protobuf.StructR\tresources\x12.\n" +
	"\x13priority_class_name\x18\x05 \x01(\tR\x11priorityClassName\x12U\n" +
	"\x1acontainer_security_context\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12A\n" +
	"\x06common\x18\a \x01(\v2).charts.values.v1.CertmanagerIssuerCommonR\x06common\x128\n" +
	"\x19use_new_ingress_for_certs\x18\b \x01(\bR\x15useNewIngressForCerts\x12;\n" +
	"\x1attl_seconds_after_finished\x18\t \x01(\rR\x17ttlSecondsAfterFinished:\x04\x88\xb5\x18\x01\"5\n" +
	"\x15CertmanagerIssuerRbac\x12\x16\n" +
	"\x06create\x18\x01 \x01(\bR\x06create:\x04\x88\xb5\x18\x01\"P\n" +
	"\x17CertmanagerIssuerCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_certmanager_issuer_proto_rawDescOnce sync.Once
	file_charts_values_v1_certmanager_issuer_proto_rawDescData []byte
)

func file_charts_values_v1_certmanager_issuer_proto_rawDescGZIP() []byte {
	file_charts_values_v1_certmanager_issuer_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_certmanager_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_certmanager_issuer_proto_rawDesc), len(file_charts_values_v1_certmanager_issuer_proto_rawDesc)))
	})
	return file_charts_values_v1_certmanager_issuer_proto_rawDescData
}

var file_charts_values_v1_certmanager_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_charts_values_v1_certmanager_issuer_proto_goTypes = []any{
	(*CertmanagerIssuerValues)(nil), // 0: charts.values.v1.CertmanagerIssuerValues
	(*CertmanagerIssuerRbac)(nil),   // 1: charts.values.v1.CertmanagerIssuerRbac
	(*CertmanagerIssuerCommon)(nil), // 2: charts.values.v1.CertmanagerIssuerCommon
	(*structpb.Struct)(nil),         // 3: google.protobuf.Struct
}
var file_charts_values_v1_certmanager_issuer_proto_depIdxs = []int32{
	1, // 0: charts.values.v1.CertmanagerIssuerValues.rbac:type_name -> charts.values.v1.CertmanagerIssuerRbac
	3, // 1: charts.values.v1.CertmanagerIssuerValues.resources:type_name -> google.protobuf.Struct
	3, // 2: charts.values.v1.CertmanagerIssuerValues.container_security_context:type_name -> google.protobuf.Struct
	2, // 3: charts.values.v1.CertmanagerIssuerValues.common:type_name -> charts.values.v1.CertmanagerIssuerCommon
	3, // 4: charts.values.v1.CertmanagerIssuerCommon.labels:type_name -> google.protobuf.Struct
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_charts_values_v1_certmanager_issuer_proto_init() }
func file_charts_values_v1_certmanager_issuer_proto_init() {
	if File_charts_values_v1_certmanager_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_certmanager_issuer_proto_rawDesc), len(file_charts_values_v1_certmanager_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_certmanager_issuer_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_certmanager_issuer_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_certmanager_issuer_proto_msgTypes,
	}.Build()
	File_charts_values_v1_certmanager_issuer_proto = out.File
	file_charts_values_v1_certmanager_issuer_proto_goTypes = nil
	file_charts_values_v1_certmanager_issuer_proto_depIdxs = nil
}
