// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/chart.proto

// Chart-level (parent) values that are not part of any GitLab sub-chart:
// upgradeCheck, shared-secrets, and gatewayApiResources. These live in the
// top-level values.yaml and are owned by the Operate team.

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpgradeCheckImage configures the image used by the pre-upgrade check hook.
type UpgradeCheckImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	PullPolicy    string                 `protobuf:"bytes,3,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	PullSecrets   []*structpb.Struct     `protobuf:"bytes,4,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCheckImage) Reset() {
	*x = UpgradeCheckImage{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCheckImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCheckImage) ProtoMessage() {}

func (x *UpgradeCheckImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCheckImage.ProtoReflect.Descriptor instead.
func (*UpgradeCheckImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{0}
}

func (x *UpgradeCheckImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpgradeCheckImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpgradeCheckImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *UpgradeCheckImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

// UpgradeCheck runs a hook that prevents unsupported version upgrades.
type UpgradeCheck struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Enabled                  bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Image                    *UpgradeCheckImage     `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	SecurityContext          *structpb.Struct       `protobuf:"bytes,3,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	ContainerSecurityContext *structpb.Struct       `protobuf:"bytes,4,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	Tolerations              []*structpb.Struct     `protobuf:"bytes,5,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	Annotations              *structpb.Struct       `protobuf:"bytes,6,opt,name=annotations,proto3" json:"annotations,omitempty"`
	ConfigMapAnnotations     *structpb.Struct       `protobuf:"bytes,7,opt,name=config_map_annotations,json=configMapAnnotations,proto3" json:"config_map_annotations,omitempty"`
	Resources                *structpb.Struct       `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	PriorityClassName        string                 `protobuf:"bytes,9,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpgradeCheck) Reset() {
	*x = UpgradeCheck{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCheck) ProtoMessage() {}

func (x *UpgradeCheck) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCheck.ProtoReflect.Descriptor instead.
func (*UpgradeCheck) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{1}
}

func (x *UpgradeCheck) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpgradeCheck) GetImage() *UpgradeCheckImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *UpgradeCheck) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *UpgradeCheck) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *UpgradeCheck) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *UpgradeCheck) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *UpgradeCheck) GetConfigMapAnnotations() *structpb.Struct {
	if x != nil {
		return x.ConfigMapAnnotations
	}
	return nil
}

func (x *UpgradeCheck) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *UpgradeCheck) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

// SharedSecretsImage configures the cfssl self-sign image.
type SharedSecretsImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	PullPolicy    string                 `protobuf:"bytes,3,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	PullSecrets   []*structpb.Struct     `protobuf:"bytes,4,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedSecretsImage) Reset() {
	*x = SharedSecretsImage{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedSecretsImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedSecretsImage) ProtoMessage() {}

func (x *SharedSecretsImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedSecretsImage.ProtoReflect.Descriptor instead.
func (*SharedSecretsImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{2}
}

func (x *SharedSecretsImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SharedSecretsImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SharedSecretsImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *SharedSecretsImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

// SharedSecretsSelfsign configures self-signed certificate generation.
type SharedSecretsSelfsign struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Image        *SharedSecretsImage    `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	KeyAlgorithm string                 `protobuf:"bytes,2,opt,name=key_algorithm,json=keyAlgorithm,proto3" json:"key_algorithm,omitempty"`
	// Key size, expressed as a string (for example "4096").
	KeySize       string `protobuf:"bytes,3,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	Expiry        string `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	CaSubject     string `protobuf:"bytes,5,opt,name=ca_subject,json=caSubject,proto3" json:"ca_subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedSecretsSelfsign) Reset() {
	*x = SharedSecretsSelfsign{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedSecretsSelfsign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedSecretsSelfsign) ProtoMessage() {}

func (x *SharedSecretsSelfsign) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedSecretsSelfsign.ProtoReflect.Descriptor instead.
func (*SharedSecretsSelfsign) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{3}
}

func (x *SharedSecretsSelfsign) GetImage() *SharedSecretsImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SharedSecretsSelfsign) GetKeyAlgorithm() string {
	if x != nil {
		return x.KeyAlgorithm
	}
	return ""
}

func (x *SharedSecretsSelfsign) GetKeySize() string {
	if x != nil {
		return x.KeySize
	}
	return ""
}

func (x *SharedSecretsSelfsign) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *SharedSecretsSelfsign) GetCaSubject() string {
	if x != nil {
		return x.CaSubject
	}
	return ""
}

// SharedSecretsRbac toggles RBAC object creation for shared-secrets jobs.
type SharedSecretsRbac struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Create        bool                   `protobuf:"varint,1,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedSecretsRbac) Reset() {
	*x = SharedSecretsRbac{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedSecretsRbac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedSecretsRbac) ProtoMessage() {}

func (x *SharedSecretsRbac) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedSecretsRbac.ProtoReflect.Descriptor instead.
func (*SharedSecretsRbac) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{4}
}

func (x *SharedSecretsRbac) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

// SharedSecretsServiceAccount configures the shared-secrets ServiceAccount.
type SharedSecretsServiceAccount struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Create  bool                   `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Pre-existing ServiceAccount name to use.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedSecretsServiceAccount) Reset() {
	*x = SharedSecretsServiceAccount{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedSecretsServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedSecretsServiceAccount) ProtoMessage() {}

func (x *SharedSecretsServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedSecretsServiceAccount.ProtoReflect.Descriptor instead.
func (*SharedSecretsServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{5}
}

func (x *SharedSecretsServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SharedSecretsServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *SharedSecretsServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// SharedSecrets generates the shared secrets used across the installation.
type SharedSecrets struct {
	state                    protoimpl.MessageState       `protogen:"open.v1"`
	Enabled                  bool                         `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rbac                     *SharedSecretsRbac           `protobuf:"bytes,2,opt,name=rbac,proto3" json:"rbac,omitempty"`
	Selfsign                 *SharedSecretsSelfsign       `protobuf:"bytes,3,opt,name=selfsign,proto3" json:"selfsign,omitempty"`
	Env                      string                       `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	ServiceAccount           *SharedSecretsServiceAccount `protobuf:"bytes,5,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	Resources                *structpb.Struct             `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	SecurityContext          *structpb.Struct             `protobuf:"bytes,7,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	ContainerSecurityContext *structpb.Struct             `protobuf:"bytes,8,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	Tolerations              []*structpb.Struct           `protobuf:"bytes,9,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	PodLabels                *structpb.Struct             `protobuf:"bytes,10,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	Annotations              *structpb.Struct             `protobuf:"bytes,11,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SharedSecrets) Reset() {
	*x = SharedSecrets{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedSecrets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedSecrets) ProtoMessage() {}

func (x *SharedSecrets) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedSecrets.ProtoReflect.Descriptor instead.
func (*SharedSecrets) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{6}
}

func (x *SharedSecrets) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SharedSecrets) GetRbac() *SharedSecretsRbac {
	if x != nil {
		return x.Rbac
	}
	return nil
}

func (x *SharedSecrets) GetSelfsign() *SharedSecretsSelfsign {
	if x != nil {
		return x.Selfsign
	}
	return nil
}

func (x *SharedSecrets) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *SharedSecrets) GetServiceAccount() *SharedSecretsServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *SharedSecrets) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SharedSecrets) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *SharedSecrets) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *SharedSecrets) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *SharedSecrets) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *SharedSecrets) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// GatewayApiClass configures the GatewayClass created for the installation.
type GatewayApiClass struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ControllerName string                 `protobuf:"bytes,2,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayApiClass) Reset() {
	*x = GatewayApiClass{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiClass) ProtoMessage() {}

func (x *GatewayApiClass) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiClass.ProtoReflect.Descriptor instead.
func (*GatewayApiClass) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayApiClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayApiClass) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

// GatewayApiCertificateRef references a TLS certificate secret.
type GatewayApiCertificateRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiCertificateRef) Reset() {
	*x = GatewayApiCertificateRef{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiCertificateRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiCertificateRef) ProtoMessage() {}

func (x *GatewayApiCertificateRef) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiCertificateRef.ProtoReflect.Descriptor instead.
func (*GatewayApiCertificateRef) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayApiCertificateRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GatewayApiListenerTls configures TLS termination for a listener.
type GatewayApiListenerTls struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Mode            string                      `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	CertificateRefs []*GatewayApiCertificateRef `protobuf:"bytes,2,rep,name=certificate_refs,json=certificateRefs,proto3" json:"certificate_refs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayApiListenerTls) Reset() {
	*x = GatewayApiListenerTls{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiListenerTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiListenerTls) ProtoMessage() {}

func (x *GatewayApiListenerTls) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiListenerTls.ProtoReflect.Descriptor instead.
func (*GatewayApiListenerTls) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayApiListenerTls) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GatewayApiListenerTls) GetCertificateRefs() []*GatewayApiCertificateRef {
	if x != nil {
		return x.CertificateRefs
	}
	return nil
}

// GatewayApiListener configures a single Gateway listener.
type GatewayApiListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Tls           *GatewayApiListenerTls `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiListener) Reset() {
	*x = GatewayApiListener{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiListener) ProtoMessage() {}

func (x *GatewayApiListener) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiListener.ProtoReflect.Descriptor instead.
func (*GatewayApiListener) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayApiListener) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GatewayApiListener) GetTls() *GatewayApiListenerTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

// GatewayApiGateway configures the Gateway resource.
type GatewayApiGateway struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Annotations    *structpb.Struct       `protobuf:"bytes,1,opt,name=annotations,proto3" json:"annotations,omitempty"`
	Infrastructure *structpb.Struct       `protobuf:"bytes,2,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	Addresses      []*structpb.Struct     `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Protocol       string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Listener configuration keyed by listener name (for example "gitlab-web").
	Listeners     map[string]*GatewayApiListener `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiGateway) Reset() {
	*x = GatewayApiGateway{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiGateway) ProtoMessage() {}

func (x *GatewayApiGateway) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiGateway.ProtoReflect.Descriptor instead.
func (*GatewayApiGateway) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{11}
}

func (x *GatewayApiGateway) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *GatewayApiGateway) GetInfrastructure() *structpb.Struct {
	if x != nil {
		return x.Infrastructure
	}
	return nil
}

func (x *GatewayApiGateway) GetAddresses() []*structpb.Struct {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GatewayApiGateway) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GatewayApiGateway) GetListeners() map[string]*GatewayApiListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// GatewayApiMonitor configures a ServiceMonitor or PodMonitor.
type GatewayApiMonitor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AdditionalLabels *structpb.Struct       `protobuf:"bytes,2,opt,name=additional_labels,json=additionalLabels,proto3" json:"additional_labels,omitempty"`
	EndpointConfig   *structpb.Struct       `protobuf:"bytes,3,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatewayApiMonitor) Reset() {
	*x = GatewayApiMonitor{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiMonitor) ProtoMessage() {}

func (x *GatewayApiMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiMonitor.ProtoReflect.Descriptor instead.
func (*GatewayApiMonitor) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{12}
}

func (x *GatewayApiMonitor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GatewayApiMonitor) GetAdditionalLabels() *structpb.Struct {
	if x != nil {
		return x.AdditionalLabels
	}
	return nil
}

func (x *GatewayApiMonitor) GetEndpointConfig() *structpb.Struct {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

// GatewayApiEnvoyGatewayMetrics wraps the Envoy Gateway ServiceMonitor.
type GatewayApiEnvoyGatewayMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceMonitor *GatewayApiMonitor     `protobuf:"bytes,1,opt,name=service_monitor,json=serviceMonitor,proto3" json:"service_monitor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayApiEnvoyGatewayMetrics) Reset() {
	*x = GatewayApiEnvoyGatewayMetrics{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiEnvoyGatewayMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiEnvoyGatewayMetrics) ProtoMessage() {}

func (x *GatewayApiEnvoyGatewayMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiEnvoyGatewayMetrics.ProtoReflect.Descriptor instead.
func (*GatewayApiEnvoyGatewayMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{13}
}

func (x *GatewayApiEnvoyGatewayMetrics) GetServiceMonitor() *GatewayApiMonitor {
	if x != nil {
		return x.ServiceMonitor
	}
	return nil
}

// GatewayApiEnvoyProxyMetrics wraps the Envoy Proxy PodMonitor.
type GatewayApiEnvoyProxyMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodMonitor    *GatewayApiMonitor     `protobuf:"bytes,1,opt,name=pod_monitor,json=podMonitor,proto3" json:"pod_monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiEnvoyProxyMetrics) Reset() {
	*x = GatewayApiEnvoyProxyMetrics{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiEnvoyProxyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiEnvoyProxyMetrics) ProtoMessage() {}

func (x *GatewayApiEnvoyProxyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiEnvoyProxyMetrics.ProtoReflect.Descriptor instead.
func (*GatewayApiEnvoyProxyMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{14}
}

func (x *GatewayApiEnvoyProxyMetrics) GetPodMonitor() *GatewayApiMonitor {
	if x != nil {
		return x.PodMonitor
	}
	return nil
}

// GatewayApiEnvoyMetrics groups the Envoy monitoring configuration.
type GatewayApiEnvoyMetrics struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	EnvoyGateway  *GatewayApiEnvoyGatewayMetrics `protobuf:"bytes,1,opt,name=envoy_gateway,json=envoyGateway,proto3" json:"envoy_gateway,omitempty"`
	EnvoyProxy    *GatewayApiEnvoyProxyMetrics   `protobuf:"bytes,2,opt,name=envoy_proxy,json=envoyProxy,proto3" json:"envoy_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiEnvoyMetrics) Reset() {
	*x = GatewayApiEnvoyMetrics{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiEnvoyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiEnvoyMetrics) ProtoMessage() {}

func (x *GatewayApiEnvoyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiEnvoyMetrics.ProtoReflect.Descriptor instead.
func (*GatewayApiEnvoyMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{15}
}

func (x *GatewayApiEnvoyMetrics) GetEnvoyGateway() *GatewayApiEnvoyGatewayMetrics {
	if x != nil {
		return x.EnvoyGateway
	}
	return nil
}

func (x *GatewayApiEnvoyMetrics) GetEnvoyProxy() *GatewayApiEnvoyProxyMetrics {
	if x != nil {
		return x.EnvoyProxy
	}
	return nil
}

// GatewayApiEnvoy configures the bundled Envoy proxy.
type GatewayApiEnvoy struct {
	state                   protoimpl.MessageState  `protogen:"open.v1"`
	ProxySpec               *structpb.Struct        `protobuf:"bytes,1,opt,name=proxy_spec,json=proxySpec,proto3" json:"proxy_spec,omitempty"`
	ClientTrafficPolicySpec *structpb.Struct        `protobuf:"bytes,2,opt,name=client_traffic_policy_spec,json=clientTrafficPolicySpec,proto3" json:"client_traffic_policy_spec,omitempty"`
	SecurityPolicySpec      *structpb.Struct        `protobuf:"bytes,3,opt,name=security_policy_spec,json=securityPolicySpec,proto3" json:"security_policy_spec,omitempty"`
	Metrics                 *GatewayApiEnvoyMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GatewayApiEnvoy) Reset() {
	*x = GatewayApiEnvoy{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiEnvoy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiEnvoy) ProtoMessage() {}

func (x *GatewayApiEnvoy) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiEnvoy.ProtoReflect.Descriptor instead.
func (*GatewayApiEnvoy) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{16}
}

func (x *GatewayApiEnvoy) GetProxySpec() *structpb.Struct {
	if x != nil {
		return x.ProxySpec
	}
	return nil
}

func (x *GatewayApiEnvoy) GetClientTrafficPolicySpec() *structpb.Struct {
	if x != nil {
		return x.ClientTrafficPolicySpec
	}
	return nil
}

func (x *GatewayApiEnvoy) GetSecurityPolicySpec() *structpb.Struct {
	if x != nil {
		return x.SecurityPolicySpec
	}
	return nil
}

func (x *GatewayApiEnvoy) GetMetrics() *GatewayApiEnvoyMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GatewayApiResources configures the Gateway API objects created by the chart.
type GatewayApiResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *GatewayApiClass       `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Gateway       *GatewayApiGateway     `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Envoy         *GatewayApiEnvoy       `protobuf:"bytes,3,opt,name=envoy,proto3" json:"envoy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayApiResources) Reset() {
	*x = GatewayApiResources{}
	mi := &file_charts_values_v1_chart_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayApiResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayApiResources) ProtoMessage() {}

func (x *GatewayApiResources) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_chart_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayApiResources.ProtoReflect.Descriptor instead.
func (*GatewayApiResources) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_chart_proto_rawDescGZIP(), []int{17}
}

func (x *GatewayApiResources) GetClass() *GatewayApiClass {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *GatewayApiResources) GetGateway() *GatewayApiGateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *GatewayApiResources) GetEnvoy() *GatewayApiEnvoy {
	if x != nil {
		return x.Envoy
	}
	return nil
}

var File_charts_values_v1_chart_proto protoreflect.FileDescriptor

const file_charts_values_v1_chart_proto_rawDesc = "" +
	"\n" +
	"\x1ccharts/values/v1/chart.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xcc\x01\n" +
	"\x11UpgradeCheckImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12C\n" +
	"\vpull_policy\x18\x03 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x04 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets:\x04\x88\xb5\x18\x01\"\xb0\x04\n" +
	"\fUpgradeCheck\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\x05image\x18\x02 \x01(\v2#.charts.values.v1.UpgradeCheckImageR\x05image\x12B\n" +
	"\x10security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x129\n" +
	"\vtolerations\x18\x05 \x03(\v2\x17.google.protobuf.StructR\vtolerations\x129\n" +
	"\vannotations\x18\x06 \x01(\v2\x17.google.protobuf.StructR\vannotations\x12M\n" +
	"\x16config_map_annotations\x18\a \x01(\v2\x17.google.protobuf.StructR\x14configMapAnnotations\x125\n" +
	"\tresources\x18\b \x01(\v2\x17.google.protobuf.StructR\tresources\x12.\n" +
	"\x13priority_class_name\x18\t \x01(\tR\x11priorityClassName:\x04\x88\xb5\x18\x01\"\xcd\x01\n" +
	"\x12SharedSecretsImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12C\n" +
	"\vpull_policy\x18\x03 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x04 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets:\x04\x88\xb5\x18\x01\"\xd0\x01\n" +
	"\x15SharedSecretsSelfsign\x12:\n" +
	"\x05image\x18\x01 \x01(\v2$.charts.values.v1.SharedSecretsImageR\x05image\x12#\n" +
	"\rkey_algorithm\x18\x02 \x01(\tR\fkeyAlgorithm\x12\x19\n" +
	"\bkey_size\x18\x03 \x01(\tR\akeySize\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x1d\n" +
	"\n" +
	"ca_subject\x18\x05 \x01(\tR\tcaSubject:\x04\x88\xb5\x18\x01\"1\n" +
	"\x11SharedSecretsRbac\x12\x16\n" +
	"\x06create\x18\x01 \x01(\bR\x06create:\x04\x88\xb5\x18\x01\"i\n" +
	"\x1bSharedSecretsServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name:\x04\x88\xb5\x18\x01\"\x97\x05\n" +
	"\rSharedSecrets\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x127\n" +
	"\x04rbac\x18\x02 \x01(\v2#.charts.values.v1.SharedSecretsRbacR\x04rbac\x12C\n" +
	"\bselfsign\x18\x03 \x01(\v2'.charts.values.v1.SharedSecretsSelfsignR\bselfsign\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12V\n" +
	"\x0fservice_account\x18\x05 \x01(\v2-.charts.values.v1.SharedSecretsServiceAccountR\x0eserviceAccount\x125\n" +
	"\tresources\x18\x06 \x01(\v2\x17.google.protobuf.StructR\tresources\x12B\n" +
	"\x10security_context\x18\a \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\b \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x129\n" +
	"\vtolerations\x18\t \x03(\v2\x17.google.protobuf.StructR\vtolerations\x126\n" +
	"\n" +
	"pod_labels\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x129\n" +
	"\vannotations\x18\v \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"T\n" +
	"\x0fGatewayApiClass\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fcontroller_name\x18\x02 \x01(\tR\x0econtrollerName:\x04\x88\xb5\x18\x01\"4\n" +
	"\x18GatewayApiCertificateRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:\x04\x88\xb5\x18\x01\"\x88\x01\n" +
	"\x15GatewayApiListenerTls\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12U\n" +
	"\x10certificate_refs\x18\x02 \x03(\v2*.charts.values.v1.GatewayApiCertificateRefR\x0fcertificateRefs:\x04\x88\xb5\x18\x01\"q\n" +
	"\x12GatewayApiListener\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x129\n" +
	"\x03tls\x18\x02 \x01(\v2'.charts.values.v1.GatewayApiListenerTlsR\x03tls:\x04\x88\xb5\x18\x01\"\x9e\x03\n" +
	"\x11GatewayApiGateway\x129\n" +
	"\vannotations\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vannotations\x12?\n" +
	"\x0einfrastructure\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0einfrastructure\x125\n" +
	"\taddresses\x18\x03 \x03(\v2\x17.google.protobuf.StructR\taddresses\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12P\n" +
	"\tlisteners\x18\x05 \x03(\v22.charts.values.v1.GatewayApiGateway.ListenersEntryR\tlisteners\x1ab\n" +
	"\x0eListenersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.charts.values.v1.GatewayApiListenerR\x05value:\x028\x01:\x04\x88\xb5\x18\x01\"\xbb\x01\n" +
	"\x11GatewayApiMonitor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x11additional_labels\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10additionalLabels\x12@\n" +
	"\x0fendpoint_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eendpointConfig:\x04\x88\xb5\x18\x01\"s\n" +
	"\x1dGatewayApiEnvoyGatewayMetrics\x12L\n" +
	"\x0fservice_monitor\x18\x01 \x01(\v2#.charts.values.v1.GatewayApiMonitorR\x0eserviceMonitor:\x04\x88\xb5\x18\x01\"i\n" +
	"\x1bGatewayApiEnvoyProxyMetrics\x12D\n" +
	"\vpod_monitor\x18\x01 \x01(\v2#.charts.values.v1.GatewayApiMonitorR\n" +
	"podMonitor:\x04\x88\xb5\x18\x01\"\xc4\x01\n" +
	"\x16GatewayApiEnvoyMetrics\x12T\n" +
	"\renvoy_gateway\x18\x01 \x01(\v2/.charts.values.v1.GatewayApiEnvoyGatewayMetricsR\fenvoyGateway\x12N\n" +
	"\venvoy_proxy\x18\x02 \x01(\v2-.charts.values.v1.GatewayApiEnvoyProxyMetricsR\n" +
	"envoyProxy:\x04\x88\xb5\x18\x01\"\xb4\x02\n" +
	"\x0fGatewayApiEnvoy\x126\n" +
	"\n" +
	"proxy_spec\x18\x01 \x01(\v2\x17.google.protobuf.StructR\tproxySpec\x12T\n" +
	"\x1aclient_traffic_policy_spec\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x17clientTrafficPolicySpec\x12I\n" +
	"\x14security_policy_spec\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x12securityPolicySpec\x12B\n" +
	"\ametrics\x18\x04 \x01(\v2(.charts.values.v1.GatewayApiEnvoyMetricsR\ametrics:\x04\x88\xb5\x18\x01\"\xcc\x01\n" +
	"\x13GatewayApiResources\x127\n" +
	"\x05class\x18\x01 \x01(\v2!.charts.values.v1.GatewayApiClassR\x05class\x12=\n" +
	"\agateway\x18\x02 \x01(\v2#.charts.values.v1.GatewayApiGatewayR\agateway\x127\n" +
	"\x05envoy\x18\x03 \x01(\v2!.charts.values.v1.GatewayApiEnvoyR\x05envoy:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_chart_proto_rawDescOnce sync.Once
	file_charts_values_v1_chart_proto_rawDescData []byte
)

func file_charts_values_v1_chart_proto_rawDescGZIP() []byte {
	file_charts_values_v1_chart_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_chart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_chart_proto_rawDesc), len(file_charts_values_v1_chart_proto_rawDesc)))
	})
	return file_charts_values_v1_chart_proto_rawDescData
}

var file_charts_values_v1_chart_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_charts_values_v1_chart_proto_goTypes = []any{
	(*UpgradeCheckImage)(nil),             // 0: charts.values.v1.UpgradeCheckImage
	(*UpgradeCheck)(nil),                  // 1: charts.values.v1.UpgradeCheck
	(*SharedSecretsImage)(nil),            // 2: charts.values.v1.SharedSecretsImage
	(*SharedSecretsSelfsign)(nil),         // 3: charts.values.v1.SharedSecretsSelfsign
	(*SharedSecretsRbac)(nil),             // 4: charts.values.v1.SharedSecretsRbac
	(*SharedSecretsServiceAccount)(nil),   // 5: charts.values.v1.SharedSecretsServiceAccount
	(*SharedSecrets)(nil),                 // 6: charts.values.v1.SharedSecrets
	(*GatewayApiClass)(nil),               // 7: charts.values.v1.GatewayApiClass
	(*GatewayApiCertificateRef)(nil),      // 8: charts.values.v1.GatewayApiCertificateRef
	(*GatewayApiListenerTls)(nil),         // 9: charts.values.v1.GatewayApiListenerTls
	(*GatewayApiListener)(nil),            // 10: charts.values.v1.GatewayApiListener
	(*GatewayApiGateway)(nil),             // 11: charts.values.v1.GatewayApiGateway
	(*GatewayApiMonitor)(nil),             // 12: charts.values.v1.GatewayApiMonitor
	(*GatewayApiEnvoyGatewayMetrics)(nil), // 13: charts.values.v1.GatewayApiEnvoyGatewayMetrics
	(*GatewayApiEnvoyProxyMetrics)(nil),   // 14: charts.values.v1.GatewayApiEnvoyProxyMetrics
	(*GatewayApiEnvoyMetrics)(nil),        // 15: charts.values.v1.GatewayApiEnvoyMetrics
	(*GatewayApiEnvoy)(nil),               // 16: charts.values.v1.GatewayApiEnvoy
	(*GatewayApiResources)(nil),           // 17: charts.values.v1.GatewayApiResources
	nil,                                   // 18: charts.values.v1.GatewayApiGateway.ListenersEntry
	(*structpb.Struct)(nil),               // 19: google.protobuf.Struct
}
var file_charts_values_v1_chart_proto_depIdxs = []int32{
	19, // 0: charts.values.v1.UpgradeCheckImage.pull_secrets:type_name -> google.protobuf.Struct
	0,  // 1: charts.values.v1.UpgradeCheck.image:type_name -> charts.values.v1.UpgradeCheckImage
	19, // 2: charts.values.v1.UpgradeCheck.security_context:type_name -> google.protobuf.Struct
	19, // 3: charts.values.v1.UpgradeCheck.container_security_context:type_name -> google.protobuf.Struct
	19, // 4: charts.values.v1.UpgradeCheck.tolerations:type_name -> google.protobuf.Struct
	19, // 5: charts.values.v1.UpgradeCheck.annotations:type_name -> google.protobuf.Struct
	19, // 6: charts.values.v1.UpgradeCheck.config_map_annotations:type_name -> google.protobuf.Struct
	19, // 7: charts.values.v1.UpgradeCheck.resources:type_name -> google.protobuf.Struct
	19, // 8: charts.values.v1.SharedSecretsImage.pull_secrets:type_name -> google.protobuf.Struct
	2,  // 9: charts.values.v1.SharedSecretsSelfsign.image:type_name -> charts.values.v1.SharedSecretsImage
	4,  // 10: charts.values.v1.SharedSecrets.rbac:type_name -> charts.values.v1.SharedSecretsRbac
	3,  // 11: charts.values.v1.SharedSecrets.selfsign:type_name -> charts.values.v1.SharedSecretsSelfsign
	5,  // 12: charts.values.v1.SharedSecrets.service_account:type_name -> charts.values.v1.SharedSecretsServiceAccount
	19, // 13: charts.values.v1.SharedSecrets.resources:type_name -> google.protobuf.Struct
	19, // 14: charts.values.v1.SharedSecrets.security_context:type_name -> google.protobuf.Struct
	19, // 15: charts.values.v1.SharedSecrets.container_security_context:type_name -> google.protobuf.Struct
	19, // 16: charts.values.v1.SharedSecrets.tolerations:type_name -> google.protobuf.Struct
	19, // 17: charts.values.v1.SharedSecrets.pod_labels:type_name -> google.protobuf.Struct
	19, // 18: charts.values.v1.SharedSecrets.annotations:type_name -> google.protobuf.Struct
	8,  // 19: charts.values.v1.GatewayApiListenerTls.certificate_refs:type_name -> charts.values.v1.GatewayApiCertificateRef
	9,  // 20: charts.values.v1.GatewayApiListener.tls:type_name -> charts.values.v1.GatewayApiListenerTls
	19, // 21: charts.values.v1.GatewayApiGateway.annotations:type_name -> google.protobuf.Struct
	19, // 22: charts.values.v1.GatewayApiGateway.infrastructure:type_name -> google.protobuf.Struct
	19, // 23: charts.values.v1.GatewayApiGateway.addresses:type_name -> google.protobuf.Struct
	18, // 24: charts.values.v1.GatewayApiGateway.listeners:type_name -> charts.values.v1.GatewayApiGateway.ListenersEntry
	19, // 25: charts.values.v1.GatewayApiMonitor.additional_labels:type_name -> google.protobuf.Struct
	19, // 26: charts.values.v1.GatewayApiMonitor.endpoint_config:type_name -> google.protobuf.Struct
	12, // 27: charts.values.v1.GatewayApiEnvoyGatewayMetrics.service_monitor:type_name -> charts.values.v1.GatewayApiMonitor
	12, // 28: charts.values.v1.GatewayApiEnvoyProxyMetrics.pod_monitor:type_name -> charts.values.v1.GatewayApiMonitor
	13, // 29: charts.values.v1.GatewayApiEnvoyMetrics.envoy_gateway:type_name -> charts.values.v1.GatewayApiEnvoyGatewayMetrics
	14, // 30: charts.values.v1.GatewayApiEnvoyMetrics.envoy_proxy:type_name -> charts.values.v1.GatewayApiEnvoyProxyMetrics
	19, // 31: charts.values.v1.GatewayApiEnvoy.proxy_spec:type_name -> google.protobuf.Struct
	19, // 32: charts.values.v1.GatewayApiEnvoy.client_traffic_policy_spec:type_name -> google.protobuf.Struct
	19, // 33: charts.values.v1.GatewayApiEnvoy.security_policy_spec:type_name -> google.protobuf.Struct
	15, // 34: charts.values.v1.GatewayApiEnvoy.metrics:type_name -> charts.values.v1.GatewayApiEnvoyMetrics
	7,  // 35: charts.values.v1.GatewayApiResources.class:type_name -> charts.values.v1.GatewayApiClass
	11, // 36: charts.values.v1.GatewayApiResources.gateway:type_name -> charts.values.v1.GatewayApiGateway
	16, // 37: charts.values.v1.GatewayApiResources.envoy:type_name -> charts.values.v1.GatewayApiEnvoy
	10, // 38: charts.values.v1.GatewayApiGateway.ListenersEntry.value:type_name -> charts.values.v1.GatewayApiListener
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_charts_values_v1_chart_proto_init() }
func file_charts_values_v1_chart_proto_init() {
	if File_charts_values_v1_chart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_chart_proto_rawDesc), len(file_charts_values_v1_chart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_chart_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_chart_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_chart_proto_msgTypes,
	}.Build()
	File_charts_values_v1_chart_proto = out.File
	file_charts_values_v1_chart_proto_goTypes = nil
	file_charts_values_v1_chart_proto_depIdxs = nil
}
