// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/gitlab_shell.proto

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShellValues is the top-level schema for the gitlab-shell sub-chart values.
type ShellValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image configuration.
	Image *ShellImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Kubernetes Service configuration.
	Service *ShellService `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Init container configuration.
	Init *ShellInit `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	// Tolerations for pod scheduling.
	Tolerations []*structpb.Struct `protobuf:"bytes,4,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// Priority class assigned to pods.
	PriorityClassName string `protobuf:"bytes,5,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Global settings shared across all sub-charts.
	Global *GlobalConfig `protobuf:"bytes,6,opt,name=global,proto3" json:"global,omitempty"`
	// Whether the gitlab-shell sub-chart is enabled.
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Annotations applied to gitlab-shell resources.
	Annotations *structpb.Struct `protobuf:"bytes,8,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Labels applied to pods.
	PodLabels *structpb.Struct `protobuf:"bytes,9,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Common settings such as shared labels.
	Common *ShellCommon `protobuf:"bytes,10,opt,name=common,proto3" json:"common,omitempty"`
	// Labels applied to the Service.
	ServiceLabels *structpb.Struct `protobuf:"bytes,11,opt,name=service_labels,json=serviceLabels,proto3" json:"service_labels,omitempty"`
	// Workhorse connection settings (defaults to being part of Webservice).
	Workhorse *structpb.Struct `protobuf:"bytes,12,opt,name=workhorse,proto3" json:"workhorse,omitempty"`
	// Compute resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,13,opt,name=resources,proto3" json:"resources,omitempty"`
	// Maximum number of pods unavailable during a disruption.
	MaxUnavailable uint32 `protobuf:"varint,14,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	// Minimum number of replicas.
	MinReplicas uint32 `protobuf:"varint,15,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// Maximum number of replicas.
	MaxReplicas uint32 `protobuf:"varint,16,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// Gateway API route configuration.
	GatewayRoute *ShellGatewayRoute `protobuf:"bytes,17,opt,name=gateway_route,json=gatewayRoute,proto3" json:"gateway_route,omitempty"`
	// Traefik ingress configuration.
	Traefik *ShellTraefik `protobuf:"bytes,18,opt,name=traefik,proto3" json:"traefik,omitempty"`
	// Horizontal Pod Autoscaler configuration.
	Hpa *ShellHpa `protobuf:"bytes,19,opt,name=hpa,proto3" json:"hpa,omitempty"`
	// KEDA autoscaling configuration.
	Keda *ShellKeda `protobuf:"bytes,20,opt,name=keda,proto3" json:"keda,omitempty"`
	// Deployment configuration.
	Deployment *ShellDeployment `protobuf:"bytes,21,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Logging configuration.
	Logging *ShellLogging `protobuf:"bytes,22,opt,name=logging,proto3" json:"logging,omitempty"`
	// gitlab-shell SSH daemon configuration.
	Config *ShellConfig `protobuf:"bytes,23,opt,name=config,proto3" json:"config,omitempty"`
	// Pod-level security context.
	SecurityContext *structpb.Struct `protobuf:"bytes,24,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	// Container-level security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,25,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// ServiceAccount configuration.
	ServiceAccount *ShellServiceAccount `protobuf:"bytes,26,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Metrics and ServiceMonitor configuration.
	Metrics *ShellMetrics `protobuf:"bytes,27,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// NetworkPolicy configuration.
	Networkpolicy *ShellNetworkPolicy `protobuf:"bytes,28,opt,name=networkpolicy,proto3" json:"networkpolicy,omitempty"`
	// SSH daemon implementation to run in the container.
	SshDaemon string `protobuf:"bytes,29,opt,name=ssh_daemon,json=sshDaemon,proto3" json:"ssh_daemon,omitempty"`
	// Pod affinity/anti-affinity rules.
	Affinity *structpb.Struct `protobuf:"bytes,30,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Topology spread constraints for pod scheduling.
	TopologySpreadConstraints []*structpb.Struct `protobuf:"bytes,31,rep,name=topology_spread_constraints,json=topologySpreadConstraints,proto3" json:"topology_spread_constraints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ShellValues) Reset() {
	*x = ShellValues{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellValues) ProtoMessage() {}

func (x *ShellValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellValues.ProtoReflect.Descriptor instead.
func (*ShellValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{0}
}

func (x *ShellValues) GetImage() *ShellImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ShellValues) GetService() *ShellService {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ShellValues) GetInit() *ShellInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *ShellValues) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *ShellValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *ShellValues) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ShellValues) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellValues) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ShellValues) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *ShellValues) GetCommon() *ShellCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *ShellValues) GetServiceLabels() *structpb.Struct {
	if x != nil {
		return x.ServiceLabels
	}
	return nil
}

func (x *ShellValues) GetWorkhorse() *structpb.Struct {
	if x != nil {
		return x.Workhorse
	}
	return nil
}

func (x *ShellValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ShellValues) GetMaxUnavailable() uint32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *ShellValues) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *ShellValues) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *ShellValues) GetGatewayRoute() *ShellGatewayRoute {
	if x != nil {
		return x.GatewayRoute
	}
	return nil
}

func (x *ShellValues) GetTraefik() *ShellTraefik {
	if x != nil {
		return x.Traefik
	}
	return nil
}

func (x *ShellValues) GetHpa() *ShellHpa {
	if x != nil {
		return x.Hpa
	}
	return nil
}

func (x *ShellValues) GetKeda() *ShellKeda {
	if x != nil {
		return x.Keda
	}
	return nil
}

func (x *ShellValues) GetDeployment() *ShellDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *ShellValues) GetLogging() *ShellLogging {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *ShellValues) GetConfig() *ShellConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ShellValues) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *ShellValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *ShellValues) GetServiceAccount() *ShellServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *ShellValues) GetMetrics() *ShellMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ShellValues) GetNetworkpolicy() *ShellNetworkPolicy {
	if x != nil {
		return x.Networkpolicy
	}
	return nil
}

func (x *ShellValues) GetSshDaemon() string {
	if x != nil {
		return x.SshDaemon
	}
	return ""
}

func (x *ShellValues) GetAffinity() *structpb.Struct {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *ShellValues) GetTopologySpreadConstraints() []*structpb.Struct {
	if x != nil {
		return x.TopologySpreadConstraints
	}
	return nil
}

// ShellImage configures the container image.
type ShellImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image repository.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Image pull policy.
	PullPolicy string `protobuf:"bytes,2,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	// Image pull secrets.
	PullSecrets []*structpb.Struct `protobuf:"bytes,3,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	// Container image tag.
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellImage) Reset() {
	*x = ShellImage{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellImage) ProtoMessage() {}

func (x *ShellImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellImage.ProtoReflect.Descriptor instead.
func (*ShellImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{1}
}

func (x *ShellImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ShellImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *ShellImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

func (x *ShellImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// ShellService configures the Kubernetes Service.
type ShellService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Service type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Internal port for SSH traffic.
	InternalPort uint32 `protobuf:"varint,3,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	// External traffic policy.
	ExternalTrafficPolicy string `protobuf:"bytes,4,opt,name=external_traffic_policy,json=externalTrafficPolicy,proto3" json:"external_traffic_policy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShellService) Reset() {
	*x = ShellService{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellService) ProtoMessage() {}

func (x *ShellService) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellService.ProtoReflect.Descriptor instead.
func (*ShellService) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{2}
}

func (x *ShellService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShellService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ShellService) GetInternalPort() uint32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *ShellService) GetExternalTrafficPolicy() string {
	if x != nil {
		return x.ExternalTrafficPolicy
	}
	return ""
}

// ShellInit configures the init container.
type ShellInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image override.
	Image *structpb.Struct `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Init container security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,3,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ShellInit) Reset() {
	*x = ShellInit{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellInit) ProtoMessage() {}

func (x *ShellInit) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellInit.ProtoReflect.Descriptor instead.
func (*ShellInit) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{3}
}

func (x *ShellInit) GetImage() *structpb.Struct {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ShellInit) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ShellInit) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

// ShellCommon holds settings shared across gitlab-shell resources.
type ShellCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Labels applied to all resources.
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommon) Reset() {
	*x = ShellCommon{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommon) ProtoMessage() {}

func (x *ShellCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommon.ProtoReflect.Descriptor instead.
func (*ShellCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{4}
}

func (x *ShellCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ShellGatewayRoute configures the Gateway API route.
type ShellGatewayRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the Gateway API route is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Gateway listener section name.
	SectionName string `protobuf:"bytes,2,opt,name=section_name,json=sectionName,proto3" json:"section_name,omitempty"`
	// Gateway name.
	GatewayName string `protobuf:"bytes,3,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// Gateway namespace.
	GatewayNamespace string `protobuf:"bytes,4,opt,name=gateway_namespace,json=gatewayNamespace,proto3" json:"gateway_namespace,omitempty"`
	// Annotations applied to the route.
	Annotations   *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellGatewayRoute) Reset() {
	*x = ShellGatewayRoute{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellGatewayRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellGatewayRoute) ProtoMessage() {}

func (x *ShellGatewayRoute) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellGatewayRoute.ProtoReflect.Descriptor instead.
func (*ShellGatewayRoute) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{5}
}

func (x *ShellGatewayRoute) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellGatewayRoute) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *ShellGatewayRoute) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *ShellGatewayRoute) GetGatewayNamespace() string {
	if x != nil {
		return x.GatewayNamespace
	}
	return ""
}

func (x *ShellGatewayRoute) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ShellTraefik configures Traefik ingress integration.
type ShellTraefik struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traefik entrypoint.
	Entrypoint string `protobuf:"bytes,1,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// Traefik apiVersion override.
	ApiVersion string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// IngressClassName for the IngressRouteTCP.
	IngressClassName string `protobuf:"bytes,3,opt,name=ingress_class_name,json=ingressClassName,proto3" json:"ingress_class_name,omitempty"`
	// Annotations applied to the IngressRouteTCP.
	TcpAnnotations *structpb.Struct `protobuf:"bytes,4,opt,name=tcp_annotations,json=tcpAnnotations,proto3" json:"tcp_annotations,omitempty"`
	// Middlewares applied to the IngressRouteTCP.
	TcpMiddlewares []*structpb.Struct `protobuf:"bytes,5,rep,name=tcp_middlewares,json=tcpMiddlewares,proto3" json:"tcp_middlewares,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShellTraefik) Reset() {
	*x = ShellTraefik{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellTraefik) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellTraefik) ProtoMessage() {}

func (x *ShellTraefik) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellTraefik.ProtoReflect.Descriptor instead.
func (*ShellTraefik) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{6}
}

func (x *ShellTraefik) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ShellTraefik) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ShellTraefik) GetIngressClassName() string {
	if x != nil {
		return x.IngressClassName
	}
	return ""
}

func (x *ShellTraefik) GetTcpAnnotations() *structpb.Struct {
	if x != nil {
		return x.TcpAnnotations
	}
	return nil
}

func (x *ShellTraefik) GetTcpMiddlewares() []*structpb.Struct {
	if x != nil {
		return x.TcpMiddlewares
	}
	return nil
}

// ShellHpa configures the Horizontal Pod Autoscaler.
type ShellHpa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU-based scaling target.
	Cpu *ShellHpaCpu `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Overrides the HPA metrics definition.
	CustomMetrics []*structpb.Struct `protobuf:"bytes,2,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty"`
	// Scaling behavior configuration.
	Behavior      *ShellHpaBehavior `protobuf:"bytes,3,opt,name=behavior,proto3" json:"behavior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellHpa) Reset() {
	*x = ShellHpa{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellHpa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellHpa) ProtoMessage() {}

func (x *ShellHpa) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellHpa.ProtoReflect.Descriptor instead.
func (*ShellHpa) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{7}
}

func (x *ShellHpa) GetCpu() *ShellHpaCpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ShellHpa) GetCustomMetrics() []*structpb.Struct {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

func (x *ShellHpa) GetBehavior() *ShellHpaBehavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

// ShellHpaCpu configures CPU-based autoscaling.
type ShellHpaCpu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target type: Utilization or AverageValue.
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Target average CPU value.
	TargetAverageValue string `protobuf:"bytes,2,opt,name=target_average_value,json=targetAverageValue,proto3" json:"target_average_value,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShellHpaCpu) Reset() {
	*x = ShellHpaCpu{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellHpaCpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellHpaCpu) ProtoMessage() {}

func (x *ShellHpaCpu) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellHpaCpu.ProtoReflect.Descriptor instead.
func (*ShellHpaCpu) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{8}
}

func (x *ShellHpaCpu) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ShellHpaCpu) GetTargetAverageValue() string {
	if x != nil {
		return x.TargetAverageValue
	}
	return ""
}

// ShellHpaBehavior configures scaling behavior.
type ShellHpaBehavior struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scale-down behavior.
	ScaleDown     *ShellHpaScaleDown `protobuf:"bytes,1,opt,name=scale_down,json=scaleDown,proto3" json:"scale_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellHpaBehavior) Reset() {
	*x = ShellHpaBehavior{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellHpaBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellHpaBehavior) ProtoMessage() {}

func (x *ShellHpaBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellHpaBehavior.ProtoReflect.Descriptor instead.
func (*ShellHpaBehavior) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{9}
}

func (x *ShellHpaBehavior) GetScaleDown() *ShellHpaScaleDown {
	if x != nil {
		return x.ScaleDown
	}
	return nil
}

// ShellHpaScaleDown configures scale-down behavior.
type ShellHpaScaleDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stabilization window, in seconds, before scaling down.
	StabilizationWindowSeconds uint32 `protobuf:"varint,1,opt,name=stabilization_window_seconds,json=stabilizationWindowSeconds,proto3" json:"stabilization_window_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ShellHpaScaleDown) Reset() {
	*x = ShellHpaScaleDown{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellHpaScaleDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellHpaScaleDown) ProtoMessage() {}

func (x *ShellHpaScaleDown) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellHpaScaleDown.ProtoReflect.Descriptor instead.
func (*ShellHpaScaleDown) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{10}
}

func (x *ShellHpaScaleDown) GetStabilizationWindowSeconds() uint32 {
	if x != nil {
		return x.StabilizationWindowSeconds
	}
	return 0
}

// ShellKeda configures KEDA autoscaling.
type ShellKeda struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether KEDA autoscaling is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Polling interval, in seconds.
	PollingInterval uint32 `protobuf:"varint,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	// Cooldown period, in seconds.
	CooldownPeriod uint32 `protobuf:"varint,3,opt,name=cooldown_period,json=cooldownPeriod,proto3" json:"cooldown_period,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShellKeda) Reset() {
	*x = ShellKeda{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellKeda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellKeda) ProtoMessage() {}

func (x *ShellKeda) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellKeda.ProtoReflect.Descriptor instead.
func (*ShellKeda) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{11}
}

func (x *ShellKeda) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellKeda) GetPollingInterval() uint32 {
	if x != nil {
		return x.PollingInterval
	}
	return 0
}

func (x *ShellKeda) GetCooldownPeriod() uint32 {
	if x != nil {
		return x.CooldownPeriod
	}
	return 0
}

// ShellDeployment configures the Deployment.
type ShellDeployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Grace period, in seconds, for pod termination.
	TerminationGracePeriodSeconds uint32 `protobuf:"varint,1,opt,name=termination_grace_period_seconds,json=terminationGracePeriodSeconds,proto3" json:"termination_grace_period_seconds,omitempty"`
	// Liveness probe configuration.
	LivenessProbe *ShellProbe `protobuf:"bytes,2,opt,name=liveness_probe,json=livenessProbe,proto3" json:"liveness_probe,omitempty"`
	// Readiness probe configuration.
	ReadinessProbe *ShellProbe `protobuf:"bytes,3,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	// Deployment update strategy.
	Strategy      *structpb.Struct `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellDeployment) Reset() {
	*x = ShellDeployment{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellDeployment) ProtoMessage() {}

func (x *ShellDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellDeployment.ProtoReflect.Descriptor instead.
func (*ShellDeployment) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{12}
}

func (x *ShellDeployment) GetTerminationGracePeriodSeconds() uint32 {
	if x != nil {
		return x.TerminationGracePeriodSeconds
	}
	return 0
}

func (x *ShellDeployment) GetLivenessProbe() *ShellProbe {
	if x != nil {
		return x.LivenessProbe
	}
	return nil
}

func (x *ShellDeployment) GetReadinessProbe() *ShellProbe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

func (x *ShellDeployment) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

// ShellProbe configures a liveness or readiness probe.
type ShellProbe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delay, in seconds, before the probe is first run.
	InitialDelaySeconds uint32 `protobuf:"varint,1,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"`
	// How often, in seconds, to run the probe.
	PeriodSeconds uint32 `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// Timeout, in seconds, for the probe.
	TimeoutSeconds uint32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Consecutive successes required for the probe to pass.
	SuccessThreshold uint32 `protobuf:"varint,4,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	// Consecutive failures required for the probe to fail.
	FailureThreshold uint32 `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShellProbe) Reset() {
	*x = ShellProbe{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellProbe) ProtoMessage() {}

func (x *ShellProbe) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellProbe.ProtoReflect.Descriptor instead.
func (*ShellProbe) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{13}
}

func (x *ShellProbe) GetInitialDelaySeconds() uint32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *ShellProbe) GetPeriodSeconds() uint32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *ShellProbe) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ShellProbe) GetSuccessThreshold() uint32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *ShellProbe) GetFailureThreshold() uint32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

// ShellLogging configures logging output.
type ShellLogging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log output format.
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// Log level for the SSH daemon.
	SshdLogLevel  string `protobuf:"bytes,2,opt,name=sshd_log_level,json=sshdLogLevel,proto3" json:"sshd_log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellLogging) Reset() {
	*x = ShellLogging{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellLogging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellLogging) ProtoMessage() {}

func (x *ShellLogging) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellLogging.ProtoReflect.Descriptor instead.
func (*ShellLogging) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{14}
}

func (x *ShellLogging) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ShellLogging) GetSshdLogLevel() string {
	if x != nil {
		return x.SshdLogLevel
	}
	return ""
}

// ShellConfig configures the gitlab-shell SSH daemon.
type ShellConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interval, in seconds, between client alive messages.
	ClientAliveInterval uint32 `protobuf:"varint,1,opt,name=client_alive_interval,json=clientAliveInterval,proto3" json:"client_alive_interval,omitempty"`
	// Grace time, in seconds, allowed for login.
	LoginGraceTime uint32 `protobuf:"varint,2,opt,name=login_grace_time,json=loginGraceTime,proto3" json:"login_grace_time,omitempty"`
	// Maximum concurrent unauthenticated connections.
	MaxStartups *ShellConfigMaxStartups `protobuf:"bytes,3,opt,name=max_startups,json=maxStartups,proto3" json:"max_startups,omitempty"`
	// Whether to enable PROXY protocol support.
	ProxyProtocol bool `protobuf:"varint,4,opt,name=proxy_protocol,json=proxyProtocol,proto3" json:"proxy_protocol,omitempty"`
	// PROXY protocol policy.
	ProxyPolicy string `protobuf:"bytes,5,opt,name=proxy_policy,json=proxyPolicy,proto3" json:"proxy_policy,omitempty"`
	// Timeout for reading the PROXY protocol header.
	ProxyHeaderTimeout string `protobuf:"bytes,6,opt,name=proxy_header_timeout,json=proxyHeaderTimeout,proto3" json:"proxy_header_timeout,omitempty"`
	// Allowed ciphers.
	Ciphers []string `protobuf:"bytes,7,rep,name=ciphers,proto3" json:"ciphers,omitempty"`
	// Allowed key exchange algorithms.
	KexAlgorithms []string `protobuf:"bytes,8,rep,name=kex_algorithms,json=kexAlgorithms,proto3" json:"kex_algorithms,omitempty"`
	// Allowed MAC algorithms.
	Macs []string `protobuf:"bytes,9,rep,name=macs,proto3" json:"macs,omitempty"`
	// Allowed public key algorithms.
	PublicKeyAlgorithms []string `protobuf:"bytes,10,rep,name=public_key_algorithms,json=publicKeyAlgorithms,proto3" json:"public_key_algorithms,omitempty"`
	// GSSAPI authentication configuration.
	Gssapi *ShellConfigGssapi `protobuf:"bytes,11,opt,name=gssapi,proto3" json:"gssapi,omitempty"`
	// Git LFS configuration.
	Lfs *ShellConfigLfs `protobuf:"bytes,12,opt,name=lfs,proto3" json:"lfs,omitempty"`
	// Personal access token configuration.
	Pat *ShellConfigPat `protobuf:"bytes,13,opt,name=pat,proto3" json:"pat,omitempty"`
	// Topology Service gRPC client (Cells routing) configuration.
	TopologyService *ShellConfigTopologyService `protobuf:"bytes,14,opt,name=topology_service,json=topologyService,proto3" json:"topology_service,omitempty"`
	// Trusted user CA keys for SSH certificate authentication (gitlab-sshd only).
	TrustedUserCaKeys *ShellConfigTrustedUserCaKeys `protobuf:"bytes,15,opt,name=trusted_user_ca_keys,json=trustedUserCaKeys,proto3" json:"trusted_user_ca_keys,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShellConfig) Reset() {
	*x = ShellConfig{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfig) ProtoMessage() {}

func (x *ShellConfig) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfig.ProtoReflect.Descriptor instead.
func (*ShellConfig) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{15}
}

func (x *ShellConfig) GetClientAliveInterval() uint32 {
	if x != nil {
		return x.ClientAliveInterval
	}
	return 0
}

func (x *ShellConfig) GetLoginGraceTime() uint32 {
	if x != nil {
		return x.LoginGraceTime
	}
	return 0
}

func (x *ShellConfig) GetMaxStartups() *ShellConfigMaxStartups {
	if x != nil {
		return x.MaxStartups
	}
	return nil
}

func (x *ShellConfig) GetProxyProtocol() bool {
	if x != nil {
		return x.ProxyProtocol
	}
	return false
}

func (x *ShellConfig) GetProxyPolicy() string {
	if x != nil {
		return x.ProxyPolicy
	}
	return ""
}

func (x *ShellConfig) GetProxyHeaderTimeout() string {
	if x != nil {
		return x.ProxyHeaderTimeout
	}
	return ""
}

func (x *ShellConfig) GetCiphers() []string {
	if x != nil {
		return x.Ciphers
	}
	return nil
}

func (x *ShellConfig) GetKexAlgorithms() []string {
	if x != nil {
		return x.KexAlgorithms
	}
	return nil
}

func (x *ShellConfig) GetMacs() []string {
	if x != nil {
		return x.Macs
	}
	return nil
}

func (x *ShellConfig) GetPublicKeyAlgorithms() []string {
	if x != nil {
		return x.PublicKeyAlgorithms
	}
	return nil
}

func (x *ShellConfig) GetGssapi() *ShellConfigGssapi {
	if x != nil {
		return x.Gssapi
	}
	return nil
}

func (x *ShellConfig) GetLfs() *ShellConfigLfs {
	if x != nil {
		return x.Lfs
	}
	return nil
}

func (x *ShellConfig) GetPat() *ShellConfigPat {
	if x != nil {
		return x.Pat
	}
	return nil
}

func (x *ShellConfig) GetTopologyService() *ShellConfigTopologyService {
	if x != nil {
		return x.TopologyService
	}
	return nil
}

func (x *ShellConfig) GetTrustedUserCaKeys() *ShellConfigTrustedUserCaKeys {
	if x != nil {
		return x.TrustedUserCaKeys
	}
	return nil
}

// ShellConfigMaxStartups configures unauthenticated connection throttling.
type ShellConfigMaxStartups struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of unauthenticated connections before throttling begins.
	Start uint32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// Percentage rate at which connections are dropped once throttling begins.
	Rate uint32 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	// Number of unauthenticated connections at which all new ones are dropped.
	Full          uint32 `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellConfigMaxStartups) Reset() {
	*x = ShellConfigMaxStartups{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigMaxStartups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigMaxStartups) ProtoMessage() {}

func (x *ShellConfigMaxStartups) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigMaxStartups.ProtoReflect.Descriptor instead.
func (*ShellConfigMaxStartups) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{16}
}

func (x *ShellConfigMaxStartups) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ShellConfigMaxStartups) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ShellConfigMaxStartups) GetFull() uint32 {
	if x != nil {
		return x.Full
	}
	return 0
}

// ShellConfigGssapi configures GSSAPI authentication.
type ShellConfigGssapi struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether GSSAPI authentication is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Path to the GSSAPI library.
	Libpath string `protobuf:"bytes,2,opt,name=libpath,proto3" json:"libpath,omitempty"`
	// Keytab secret reference.
	Keytab *ShellConfigGssapiKeytab `protobuf:"bytes,3,opt,name=keytab,proto3" json:"keytab,omitempty"`
	// Path to the Kerberos configuration.
	Krb5Config string `protobuf:"bytes,4,opt,name=krb5_config,json=krb5Config,proto3" json:"krb5_config,omitempty"`
	// Service principal name.
	ServicePrincipalName string `protobuf:"bytes,5,opt,name=service_principal_name,json=servicePrincipalName,proto3" json:"service_principal_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShellConfigGssapi) Reset() {
	*x = ShellConfigGssapi{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigGssapi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigGssapi) ProtoMessage() {}

func (x *ShellConfigGssapi) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigGssapi.ProtoReflect.Descriptor instead.
func (*ShellConfigGssapi) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{17}
}

func (x *ShellConfigGssapi) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellConfigGssapi) GetLibpath() string {
	if x != nil {
		return x.Libpath
	}
	return ""
}

func (x *ShellConfigGssapi) GetKeytab() *ShellConfigGssapiKeytab {
	if x != nil {
		return x.Keytab
	}
	return nil
}

func (x *ShellConfigGssapi) GetKrb5Config() string {
	if x != nil {
		return x.Krb5Config
	}
	return ""
}

func (x *ShellConfigGssapi) GetServicePrincipalName() string {
	if x != nil {
		return x.ServicePrincipalName
	}
	return ""
}

// ShellConfigGssapiKeytab references the GSSAPI keytab secret.
type ShellConfigGssapiKeytab struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the secret holding the keytab.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Key within the secret holding the keytab.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellConfigGssapiKeytab) Reset() {
	*x = ShellConfigGssapiKeytab{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigGssapiKeytab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigGssapiKeytab) ProtoMessage() {}

func (x *ShellConfigGssapiKeytab) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigGssapiKeytab.ProtoReflect.Descriptor instead.
func (*ShellConfigGssapiKeytab) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{18}
}

func (x *ShellConfigGssapiKeytab) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ShellConfigGssapiKeytab) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ShellConfigLfs configures Git LFS handling.
type ShellConfigLfs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to use the pure SSH protocol for LFS.
	PureSshProtocol bool `protobuf:"varint,1,opt,name=pure_ssh_protocol,json=pureSshProtocol,proto3" json:"pure_ssh_protocol,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShellConfigLfs) Reset() {
	*x = ShellConfigLfs{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigLfs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigLfs) ProtoMessage() {}

func (x *ShellConfigLfs) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigLfs.ProtoReflect.Descriptor instead.
func (*ShellConfigLfs) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{19}
}

func (x *ShellConfigLfs) GetPureSshProtocol() bool {
	if x != nil {
		return x.PureSshProtocol
	}
	return false
}

// ShellConfigPat configures personal access token support.
type ShellConfigPat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether personal access tokens are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Allowed token scopes.
	AllowedScopes []string `protobuf:"bytes,2,rep,name=allowed_scopes,json=allowedScopes,proto3" json:"allowed_scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellConfigPat) Reset() {
	*x = ShellConfigPat{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigPat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigPat) ProtoMessage() {}

func (x *ShellConfigPat) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigPat.ProtoReflect.Descriptor instead.
func (*ShellConfigPat) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{20}
}

func (x *ShellConfigPat) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellConfigPat) GetAllowedScopes() []string {
	if x != nil {
		return x.AllowedScopes
	}
	return nil
}

// ShellConfigTopologyService configures the Topology Service gRPC client.
type ShellConfigTopologyService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether GitLab Shell uses the Topology Service.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellConfigTopologyService) Reset() {
	*x = ShellConfigTopologyService{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigTopologyService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigTopologyService) ProtoMessage() {}

func (x *ShellConfigTopologyService) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigTopologyService.ProtoReflect.Descriptor instead.
func (*ShellConfigTopologyService) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{21}
}

func (x *ShellConfigTopologyService) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ShellConfigTrustedUserCaKeys configures trusted user CA keys.
type ShellConfigTrustedUserCaKeys struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the secret holding the trusted user CA keys.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Trusted user CA keys.
	Keys          []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellConfigTrustedUserCaKeys) Reset() {
	*x = ShellConfigTrustedUserCaKeys{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellConfigTrustedUserCaKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellConfigTrustedUserCaKeys) ProtoMessage() {}

func (x *ShellConfigTrustedUserCaKeys) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellConfigTrustedUserCaKeys.ProtoReflect.Descriptor instead.
func (*ShellConfigTrustedUserCaKeys) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{22}
}

func (x *ShellConfigTrustedUserCaKeys) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ShellConfigTrustedUserCaKeys) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// ShellServiceAccount configures the ServiceAccount.
type ShellServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deployment uses a ServiceAccount.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to create the ServiceAccount.
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Annotations applied to the ServiceAccount.
	Annotations   *structpb.Struct `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellServiceAccount) Reset() {
	*x = ShellServiceAccount{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellServiceAccount) ProtoMessage() {}

func (x *ShellServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellServiceAccount.ProtoReflect.Descriptor instead.
func (*ShellServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{23}
}

func (x *ShellServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *ShellServiceAccount) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ShellMetrics configures metrics and the ServiceMonitor.
type ShellMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Metrics port.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Metrics path.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// ServiceMonitor configuration.
	ServiceMonitor *ShellMetricsServiceMonitor `protobuf:"bytes,4,opt,name=service_monitor,json=serviceMonitor,proto3" json:"service_monitor,omitempty"`
	// Annotations applied to metrics resources (deprecated).
	Annotations   *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellMetrics) Reset() {
	*x = ShellMetrics{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellMetrics) ProtoMessage() {}

func (x *ShellMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellMetrics.ProtoReflect.Descriptor instead.
func (*ShellMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{24}
}

func (x *ShellMetrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellMetrics) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ShellMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ShellMetrics) GetServiceMonitor() *ShellMetricsServiceMonitor {
	if x != nil {
		return x.ServiceMonitor
	}
	return nil
}

func (x *ShellMetrics) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ShellMetricsServiceMonitor configures the Prometheus ServiceMonitor.
type ShellMetricsServiceMonitor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the ServiceMonitor is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Additional labels applied to the ServiceMonitor.
	AdditionalLabels *structpb.Struct `protobuf:"bytes,2,opt,name=additional_labels,json=additionalLabels,proto3" json:"additional_labels,omitempty"`
	// Additional endpoint configuration.
	EndpointConfig *structpb.Struct `protobuf:"bytes,3,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShellMetricsServiceMonitor) Reset() {
	*x = ShellMetricsServiceMonitor{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellMetricsServiceMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellMetricsServiceMonitor) ProtoMessage() {}

func (x *ShellMetricsServiceMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellMetricsServiceMonitor.ProtoReflect.Descriptor instead.
func (*ShellMetricsServiceMonitor) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{25}
}

func (x *ShellMetricsServiceMonitor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellMetricsServiceMonitor) GetAdditionalLabels() *structpb.Struct {
	if x != nil {
		return x.AdditionalLabels
	}
	return nil
}

func (x *ShellMetricsServiceMonitor) GetEndpointConfig() *structpb.Struct {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

// ShellNetworkPolicy configures the NetworkPolicy.
type ShellNetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the NetworkPolicy is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules.
	Egress *ShellNetworkPolicyEgress `protobuf:"bytes,2,opt,name=egress,proto3" json:"egress,omitempty"`
	// Ingress rules.
	Ingress *ShellNetworkPolicyIngress `protobuf:"bytes,3,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// Annotations applied to the NetworkPolicy.
	Annotations   *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellNetworkPolicy) Reset() {
	*x = ShellNetworkPolicy{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellNetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellNetworkPolicy) ProtoMessage() {}

func (x *ShellNetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellNetworkPolicy.ProtoReflect.Descriptor instead.
func (*ShellNetworkPolicy) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{26}
}

func (x *ShellNetworkPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellNetworkPolicy) GetEgress() *ShellNetworkPolicyEgress {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *ShellNetworkPolicy) GetIngress() *ShellNetworkPolicyIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *ShellNetworkPolicy) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ShellNetworkPolicyEgress configures egress rules.
type ShellNetworkPolicyEgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether egress restrictions are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules.
	Rules         []*structpb.Struct `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellNetworkPolicyEgress) Reset() {
	*x = ShellNetworkPolicyEgress{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellNetworkPolicyEgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellNetworkPolicyEgress) ProtoMessage() {}

func (x *ShellNetworkPolicyEgress) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellNetworkPolicyEgress.ProtoReflect.Descriptor instead.
func (*ShellNetworkPolicyEgress) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{27}
}

func (x *ShellNetworkPolicyEgress) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellNetworkPolicyEgress) GetRules() []*structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

// ShellNetworkPolicyIngress configures ingress rules.
type ShellNetworkPolicyIngress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether ingress restrictions are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Ingress rules.
	Rules         []*structpb.Struct `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellNetworkPolicyIngress) Reset() {
	*x = ShellNetworkPolicyIngress{}
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellNetworkPolicyIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellNetworkPolicyIngress) ProtoMessage() {}

func (x *ShellNetworkPolicyIngress) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_shell_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellNetworkPolicyIngress.ProtoReflect.Descriptor instead.
func (*ShellNetworkPolicyIngress) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_shell_proto_rawDescGZIP(), []int{28}
}

func (x *ShellNetworkPolicyIngress) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShellNetworkPolicyIngress) GetRules() []*structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_charts_values_v1_gitlab_shell_proto protoreflect.FileDescriptor

const file_charts_values_v1_gitlab_shell_proto_rawDesc = "" +
	"\n" +
	"#charts/values/v1/gitlab_shell.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1dcharts/values/v1/global.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x0e\n" +
	"\vShellValues\x122\n" +
	"\x05image\x18\x01 \x01(\v2\x1c.charts.values.v1.ShellImageR\x05image\x128\n" +
	"\aservice\x18\x02 \x01(\v2\x1e.charts.values.v1.ShellServiceR\aservice\x12/\n" +
	"\x04init\x18\x03 \x01(\v2\x1b.charts.values.v1.ShellInitR\x04init\x129\n" +
	"\vtolerations\x18\x04 \x03(\v2\x17.google.protobuf.StructR\vtolerations\x12.\n" +
	"\x13priority_class_name\x18\x05 \x01(\tR\x11priorityClassName\x126\n" +
	"\x06global\x18\x06 \x01(\v2\x1e.charts.values.v1.GlobalConfigR\x06global\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x129\n" +
	"\vannotations\x18\b \x01(\v2\x17.google.protobuf.StructR\vannotations\x126\n" +
	"\n" +
	"pod_labels\x18\t \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x125\n" +
	"\x06common\x18\n" +
	" \x01(\v2\x1d.charts.values.v1.ShellCommonR\x06common\x12>\n" +
	"\x0eservice_labels\x18\v \x01(\v2\x17.google.protobuf.StructR\rserviceLabels\x125\n" +
	"\tworkhorse\x18\f \x01(\v2\x17.google.protobuf.StructR\tworkhorse\x125\n" +
	"\tresources\x18\r \x01(\v2\x17.google.protobuf.StructR\tresources\x12'\n" +
	"\x0fmax_unavailable\x18\x0e \x01(\rR\x0emaxUnavailable\x12!\n" +
	"\fmin_replicas\x18\x0f \x01(\rR\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x10 \x01(\rR\vmaxReplicas\x12H\n" +
	"\rgateway_route\x18\x11 \x01(\v2#.charts.values.v1.ShellGatewayRouteR\fgatewayRoute\x128\n" +
	"\atraefik\x18\x12 \x01(\v2\x1e.charts.values.v1.ShellTraefikR\atraefik\x12,\n" +
	"\x03hpa\x18\x13 \x01(\v2\x1a.charts.values.v1.ShellHpaR\x03hpa\x12/\n" +
	"\x04keda\x18\x14 \x01(\v2\x1b.charts.values.v1.ShellKedaR\x04keda\x12A\n" +
	"\n" +
	"deployment\x18\x15 \x01(\v2!.charts.values.v1.ShellDeploymentR\n" +
	"deployment\x128\n" +
	"\alogging\x18\x16 \x01(\v2\x1e.charts.values.v1.ShellLoggingR\alogging\x125\n" +
	"\x06config\x18\x17 \x01(\v2\x1d.charts.values.v1.ShellConfigR\x06config\x12B\n" +
	"\x10security_context\x18\x18 \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\x19 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12N\n" +
	"\x0fservice_account\x18\x1a \x01(\v2%.charts.values.v1.ShellServiceAccountR\x0eserviceAccount\x128\n" +
	"\ametrics\x18\x1b \x01(\v2\x1e.charts.values.v1.ShellMetricsR\ametrics\x12J\n" +
	"\rnetworkpolicy\x18\x1c \x01(\v2$.charts.values.v1.ShellNetworkPolicyR\rnetworkpolicy\x12:\n" +
	"\n" +
	"ssh_daemon\x18\x1d \x01(\tB\x1b\xbaH\x18r\x16R\aopensshR\vgitlab-sshdR\tsshDaemon\x123\n" +
	"\baffinity\x18\x1e \x01(\v2\x17.google.protobuf.StructR\baffinity\x12W\n" +
	"\x1btopology_spread_constraints\x18\x1f \x03(\v2\x17.google.protobuf.StructR\x19topologySpreadConstraints:\x04\x88\xb5\x18\x01\"\xc5\x01\n" +
	"\n" +
	"ShellImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12C\n" +
	"\vpull_policy\x18\x02 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x03 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag:\x04\x88\xb5\x18\x01\"\xa6\x01\n" +
	"\fShellService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x120\n" +
	"\rinternal_port\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\finternalPort\x126\n" +
	"\x17external_traffic_policy\x18\x04 \x01(\tR\x15externalTrafficPolicy:\x04\x88\xb5\x18\x01\"\xce\x01\n" +
	"\tShellInit\x12-\n" +
	"\x05image\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05image\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tresources\x12U\n" +
	"\x1acontainer_security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext:\x04\x88\xb5\x18\x01\"D\n" +
	"\vShellCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01\"\xe1\x01\n" +
	"\x11ShellGatewayRoute\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fsection_name\x18\x02 \x01(\tR\vsectionName\x12!\n" +
	"\fgateway_name\x18\x03 \x01(\tR\vgatewayName\x12+\n" +
	"\x11gateway_namespace\x18\x04 \x01(\tR\x10gatewayNamespace\x129\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"\x87\x02\n" +
	"\fShellTraefik\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x01 \x01(\tR\n" +
	"entrypoint\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12,\n" +
	"\x12ingress_class_name\x18\x03 \x01(\tR\x10ingressClassName\x12@\n" +
	"\x0ftcp_annotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0etcpAnnotations\x12@\n" +
	"\x0ftcp_middlewares\x18\x05 \x03(\v2\x17.google.protobuf.StructR\x0etcpMiddlewares:\x04\x88\xb5\x18\x01\"\xc1\x01\n" +
	"\bShellHpa\x12/\n" +
	"\x03cpu\x18\x01 \x01(\v2\x1d.charts.values.v1.ShellHpaCpuR\x03cpu\x12>\n" +
	"\x0ecustom_metrics\x18\x02 \x03(\v2\x17.google.protobuf.StructR\rcustomMetrics\x12>\n" +
	"\bbehavior\x18\x03 \x01(\v2\".charts.values.v1.ShellHpaBehaviorR\bbehavior:\x04\x88\xb5\x18\x01\"f\n" +
	"\vShellHpaCpu\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x120\n" +
	"\x14target_average_value\x18\x02 \x01(\tR\x12targetAverageValue:\x04\x88\xb5\x18\x01\"\\\n" +
	"\x10ShellHpaBehavior\x12B\n" +
	"\n" +
	"scale_down\x18\x01 \x01(\v2#.charts.values.v1.ShellHpaScaleDownR\tscaleDown:\x04\x88\xb5\x18\x01\"[\n" +
	"\x11ShellHpaScaleDown\x12@\n" +
	"\x1cstabilization_window_seconds\x18\x01 \x01(\rR\x1astabilizationWindowSeconds:\x04\x88\xb5\x18\x01\"\x7f\n" +
	"\tShellKeda\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10polling_interval\x18\x02 \x01(\rR\x0fpollingInterval\x12'\n" +
	"\x0fcooldown_period\x18\x03 \x01(\rR\x0ecooldownPeriod:\x04\x88\xb5\x18\x01\"\xa1\x02\n" +
	"\x0fShellDeployment\x12G\n" +
	" termination_grace_period_seconds\x18\x01 \x01(\rR\x1dterminationGracePeriodSeconds\x12C\n" +
	"\x0eliveness_probe\x18\x02 \x01(\v2\x1c.charts.values.v1.ShellProbeR\rlivenessProbe\x12E\n" +
	"\x0freadiness_probe\x18\x03 \x01(\v2\x1c.charts.values.v1.ShellProbeR\x0ereadinessProbe\x123\n" +
	"\bstrategy\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bstrategy:\x04\x88\xb5\x18\x01\"\xf0\x01\n" +
	"\n" +
	"ShellProbe\x122\n" +
	"\x15initial_delay_seconds\x18\x01 \x01(\rR\x13initialDelaySeconds\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\rR\rperiodSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\x12+\n" +
	"\x11success_threshold\x18\x04 \x01(\rR\x10successThreshold\x12+\n" +
	"\x11failure_threshold\x18\x05 \x01(\rR\x10failureThreshold:\x04\x88\xb5\x18\x01\"R\n" +
	"\fShellLogging\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12$\n" +
	"\x0esshd_log_level\x18\x02 \x01(\tR\fsshdLogLevel:\x04\x88\xb5\x18\x01\"\xb9\x06\n" +
	"\vShellConfig\x122\n" +
	"\x15client_alive_interval\x18\x01 \x01(\rR\x13clientAliveInterval\x12(\n" +
	"\x10login_grace_time\x18\x02 \x01(\rR\x0eloginGraceTime\x12K\n" +
	"\fmax_startups\x18\x03 \x01(\v2(.charts.values.v1.ShellConfigMaxStartupsR\vmaxStartups\x12%\n" +
	"\x0eproxy_protocol\x18\x04 \x01(\bR\rproxyProtocol\x12!\n" +
	"\fproxy_policy\x18\x05 \x01(\tR\vproxyPolicy\x120\n" +
	"\x14proxy_header_timeout\x18\x06 \x01(\tR\x12proxyHeaderTimeout\x12\x18\n" +
	"\aciphers\x18\a \x03(\tR\aciphers\x12%\n" +
	"\x0ekex_algorithms\x18\b \x03(\tR\rkexAlgorithms\x12\x12\n" +
	"\x04macs\x18\t \x03(\tR\x04macs\x122\n" +
	"\x15public_key_algorithms\x18\n" +
	" \x03(\tR\x13publicKeyAlgorithms\x12;\n" +
	"\x06gssapi\x18\v \x01(\v2#.charts.values.v1.ShellConfigGssapiR\x06gssapi\x122\n" +
	"\x03lfs\x18\f \x01(\v2 .charts.values.v1.ShellConfigLfsR\x03lfs\x122\n" +
	"\x03pat\x18\r \x01(\v2 .charts.values.v1.ShellConfigPatR\x03pat\x12W\n" +
	"\x10topology_service\x18\x0e \x01(\v2,.charts.values.v1.ShellConfigTopologyServiceR\x0ftopologyService\x12v\n" +
	"\x14trusted_user_ca_keys\x18\x0f \x01(\v2..charts.values.v1.ShellConfigTrustedUserCaKeysB\x15\x92\xb5\x18\x11trustedUserCAKeysR\x11trustedUserCaKeys:\x04\x88\xb5\x18\x01\"\\\n" +
	"\x16ShellConfigMaxStartups\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\rR\x04rate\x12\x12\n" +
	"\x04full\x18\x03 \x01(\rR\x04full:\x04\x88\xb5\x18\x01\"\xe7\x01\n" +
	"\x11ShellConfigGssapi\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\alibpath\x18\x02 \x01(\tR\alibpath\x12A\n" +
	"\x06keytab\x18\x03 \x01(\v2).charts.values.v1.ShellConfigGssapiKeytabR\x06keytab\x12\x1f\n" +
	"\vkrb5_config\x18\x04 \x01(\tR\n" +
	"krb5Config\x124\n" +
	"\x16service_principal_name\x18\x05 \x01(\tR\x14servicePrincipalName:\x04\x88\xb5\x18\x01\"I\n" +
	"\x17ShellConfigGssapiKeytab\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key:\x04\x88\xb5\x18\x01\"W\n" +
	"\x0eShellConfigLfs\x12?\n" +
	"\x11pure_ssh_protocol\x18\x01 \x01(\bB\x13\x92\xb5\x18\x0fpureSSHProtocolR\x0fpureSshProtocol:\x04\x88\xb5\x18\x01\"W\n" +
	"\x0eShellConfigPat\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12%\n" +
	"\x0eallowed_scopes\x18\x02 \x03(\tR\rallowedScopes:\x04\x88\xb5\x18\x01\"<\n" +
	"\x1aShellConfigTopologyService\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled:\x04\x88\xb5\x18\x01\"P\n" +
	"\x1cShellConfigTrustedUserCaKeys\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys:\x04\x88\xb5\x18\x01\"\x88\x01\n" +
	"\x13ShellServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x129\n" +
	"\vannotations\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"\xfb\x01\n" +
	"\fShellMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12U\n" +
	"\x0fservice_monitor\x18\x04 \x01(\v2,.charts.values.v1.ShellMetricsServiceMonitorR\x0eserviceMonitor\x12?\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x04\x98\xb5\x18\x05R\vannotations:\x04\x88\xb5\x18\x01\"\xc4\x01\n" +
	"\x1aShellMetricsServiceMonitor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x11additional_labels\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10additionalLabels\x12@\n" +
	"\x0fendpoint_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eendpointConfig:\x04\x88\xb5\x18\x01\"\xfa\x01\n" +
	"\x12ShellNetworkPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12B\n" +
	"\x06egress\x18\x02 \x01(\v2*.charts.values.v1.ShellNetworkPolicyEgressR\x06egress\x12E\n" +
	"\aingress\x18\x03 \x01(\v2+.charts.values.v1.ShellNetworkPolicyIngressR\aingress\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"i\n" +
	"\x18ShellNetworkPolicyEgress\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01\"j\n" +
	"\x19ShellNetworkPolicyIngress\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_gitlab_shell_proto_rawDescOnce sync.Once
	file_charts_values_v1_gitlab_shell_proto_rawDescData []byte
)

func file_charts_values_v1_gitlab_shell_proto_rawDescGZIP() []byte {
	file_charts_values_v1_gitlab_shell_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_gitlab_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_shell_proto_rawDesc), len(file_charts_values_v1_gitlab_shell_proto_rawDesc)))
	})
	return file_charts_values_v1_gitlab_shell_proto_rawDescData
}

var file_charts_values_v1_gitlab_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_charts_values_v1_gitlab_shell_proto_goTypes = []any{
	(*ShellValues)(nil),                  // 0: charts.values.v1.ShellValues
	(*ShellImage)(nil),                   // 1: charts.values.v1.ShellImage
	(*ShellService)(nil),                 // 2: charts.values.v1.ShellService
	(*ShellInit)(nil),                    // 3: charts.values.v1.ShellInit
	(*ShellCommon)(nil),                  // 4: charts.values.v1.ShellCommon
	(*ShellGatewayRoute)(nil),            // 5: charts.values.v1.ShellGatewayRoute
	(*ShellTraefik)(nil),                 // 6: charts.values.v1.ShellTraefik
	(*ShellHpa)(nil),                     // 7: charts.values.v1.ShellHpa
	(*ShellHpaCpu)(nil),                  // 8: charts.values.v1.ShellHpaCpu
	(*ShellHpaBehavior)(nil),             // 9: charts.values.v1.ShellHpaBehavior
	(*ShellHpaScaleDown)(nil),            // 10: charts.values.v1.ShellHpaScaleDown
	(*ShellKeda)(nil),                    // 11: charts.values.v1.ShellKeda
	(*ShellDeployment)(nil),              // 12: charts.values.v1.ShellDeployment
	(*ShellProbe)(nil),                   // 13: charts.values.v1.ShellProbe
	(*ShellLogging)(nil),                 // 14: charts.values.v1.ShellLogging
	(*ShellConfig)(nil),                  // 15: charts.values.v1.ShellConfig
	(*ShellConfigMaxStartups)(nil),       // 16: charts.values.v1.ShellConfigMaxStartups
	(*ShellConfigGssapi)(nil),            // 17: charts.values.v1.ShellConfigGssapi
	(*ShellConfigGssapiKeytab)(nil),      // 18: charts.values.v1.ShellConfigGssapiKeytab
	(*ShellConfigLfs)(nil),               // 19: charts.values.v1.ShellConfigLfs
	(*ShellConfigPat)(nil),               // 20: charts.values.v1.ShellConfigPat
	(*ShellConfigTopologyService)(nil),   // 21: charts.values.v1.ShellConfigTopologyService
	(*ShellConfigTrustedUserCaKeys)(nil), // 22: charts.values.v1.ShellConfigTrustedUserCaKeys
	(*ShellServiceAccount)(nil),          // 23: charts.values.v1.ShellServiceAccount
	(*ShellMetrics)(nil),                 // 24: charts.values.v1.ShellMetrics
	(*ShellMetricsServiceMonitor)(nil),   // 25: charts.values.v1.ShellMetricsServiceMonitor
	(*ShellNetworkPolicy)(nil),           // 26: charts.values.v1.ShellNetworkPolicy
	(*ShellNetworkPolicyEgress)(nil),     // 27: charts.values.v1.ShellNetworkPolicyEgress
	(*ShellNetworkPolicyIngress)(nil),    // 28: charts.values.v1.ShellNetworkPolicyIngress
	(*structpb.Struct)(nil),              // 29: google.protobuf.Struct
	(*GlobalConfig)(nil),                 // 30: charts.values.v1.GlobalConfig
}
var file_charts_values_v1_gitlab_shell_proto_depIdxs = []int32{
	1,  // 0: charts.values.v1.ShellValues.image:type_name -> charts.values.v1.ShellImage
	2,  // 1: charts.values.v1.ShellValues.service:type_name -> charts.values.v1.ShellService
	3,  // 2: charts.values.v1.ShellValues.init:type_name -> charts.values.v1.ShellInit
	29, // 3: charts.values.v1.ShellValues.tolerations:type_name -> google.protobuf.Struct
	30, // 4: charts.values.v1.ShellValues.global:type_name -> charts.values.v1.GlobalConfig
	29, // 5: charts.values.v1.ShellValues.annotations:type_name -> google.protobuf.Struct
	29, // 6: charts.values.v1.ShellValues.pod_labels:type_name -> google.protobuf.Struct
	4,  // 7: charts.values.v1.ShellValues.common:type_name -> charts.values.v1.ShellCommon
	29, // 8: charts.values.v1.ShellValues.service_labels:type_name -> google.protobuf.Struct
	29, // 9: charts.values.v1.ShellValues.workhorse:type_name -> google.protobuf.Struct
	29, // 10: charts.values.v1.ShellValues.resources:type_name -> google.protobuf.Struct
	5,  // 11: charts.values.v1.ShellValues.gateway_route:type_name -> charts.values.v1.ShellGatewayRoute
	6,  // 12: charts.values.v1.ShellValues.traefik:type_name -> charts.values.v1.ShellTraefik
	7,  // 13: charts.values.v1.ShellValues.hpa:type_name -> charts.values.v1.ShellHpa
	11, // 14: charts.values.v1.ShellValues.keda:type_name -> charts.values.v1.ShellKeda
	12, // 15: charts.values.v1.ShellValues.deployment:type_name -> charts.values.v1.ShellDeployment
	14, // 16: charts.values.v1.ShellValues.logging:type_name -> charts.values.v1.ShellLogging
	15, // 17: charts.values.v1.ShellValues.config:type_name -> charts.values.v1.ShellConfig
	29, // 18: charts.values.v1.ShellValues.security_context:type_name -> google.protobuf.Struct
	29, // 19: charts.values.v1.ShellValues.container_security_context:type_name -> google.protobuf.Struct
	23, // 20: charts.values.v1.ShellValues.service_account:type_name -> charts.values.v1.ShellServiceAccount
	24, // 21: charts.values.v1.ShellValues.metrics:type_name -> charts.values.v1.ShellMetrics
	26, // 22: charts.values.v1.ShellValues.networkpolicy:type_name -> charts.values.v1.ShellNetworkPolicy
	29, // 23: charts.values.v1.ShellValues.affinity:type_name -> google.protobuf.Struct
	29, // 24: charts.values.v1.ShellValues.topology_spread_constraints:type_name -> google.protobuf.Struct
	29, // 25: charts.values.v1.ShellImage.pull_secrets:type_name -> google.protobuf.Struct
	29, // 26: charts.values.v1.ShellInit.image:type_name -> google.protobuf.Struct
	29, // 27: charts.values.v1.ShellInit.resources:type_name -> google.protobuf.Struct
	29, // 28: charts.values.v1.ShellInit.container_security_context:type_name -> google.protobuf.Struct
	29, // 29: charts.values.v1.ShellCommon.labels:type_name -> google.protobuf.Struct
	29, // 30: charts.values.v1.ShellGatewayRoute.annotations:type_name -> google.protobuf.Struct
	29, // 31: charts.values.v1.ShellTraefik.tcp_annotations:type_name -> google.protobuf.Struct
	29, // 32: charts.values.v1.ShellTraefik.tcp_middlewares:type_name -> google.protobuf.Struct
	8,  // 33: charts.values.v1.ShellHpa.cpu:type_name -> charts.values.v1.ShellHpaCpu
	29, // 34: charts.values.v1.ShellHpa.custom_metrics:type_name -> google.protobuf.Struct
	9,  // 35: charts.values.v1.ShellHpa.behavior:type_name -> charts.values.v1.ShellHpaBehavior
	10, // 36: charts.values.v1.ShellHpaBehavior.scale_down:type_name -> charts.values.v1.ShellHpaScaleDown
	13, // 37: charts.values.v1.ShellDeployment.liveness_probe:type_name -> charts.values.v1.ShellProbe
	13, // 38: charts.values.v1.ShellDeployment.readiness_probe:type_name -> charts.values.v1.ShellProbe
	29, // 39: charts.values.v1.ShellDeployment.strategy:type_name -> google.protobuf.Struct
	16, // 40: charts.values.v1.ShellConfig.max_startups:type_name -> charts.values.v1.ShellConfigMaxStartups
	17, // 41: charts.values.v1.ShellConfig.gssapi:type_name -> charts.values.v1.ShellConfigGssapi
	19, // 42: charts.values.v1.ShellConfig.lfs:type_name -> charts.values.v1.ShellConfigLfs
	20, // 43: charts.values.v1.ShellConfig.pat:type_name -> charts.values.v1.ShellConfigPat
	21, // 44: charts.values.v1.ShellConfig.topology_service:type_name -> charts.values.v1.ShellConfigTopologyService
	22, // 45: charts.values.v1.ShellConfig.trusted_user_ca_keys:type_name -> charts.values.v1.ShellConfigTrustedUserCaKeys
	18, // 46: charts.values.v1.ShellConfigGssapi.keytab:type_name -> charts.values.v1.ShellConfigGssapiKeytab
	29, // 47: charts.values.v1.ShellServiceAccount.annotations:type_name -> google.protobuf.Struct
	25, // 48: charts.values.v1.ShellMetrics.service_monitor:type_name -> charts.values.v1.ShellMetricsServiceMonitor
	29, // 49: charts.values.v1.ShellMetrics.annotations:type_name -> google.protobuf.Struct
	29, // 50: charts.values.v1.ShellMetricsServiceMonitor.additional_labels:type_name -> google.protobuf.Struct
	29, // 51: charts.values.v1.ShellMetricsServiceMonitor.endpoint_config:type_name -> google.protobuf.Struct
	27, // 52: charts.values.v1.ShellNetworkPolicy.egress:type_name -> charts.values.v1.ShellNetworkPolicyEgress
	28, // 53: charts.values.v1.ShellNetworkPolicy.ingress:type_name -> charts.values.v1.ShellNetworkPolicyIngress
	29, // 54: charts.values.v1.ShellNetworkPolicy.annotations:type_name -> google.protobuf.Struct
	29, // 55: charts.values.v1.ShellNetworkPolicyEgress.rules:type_name -> google.protobuf.Struct
	29, // 56: charts.values.v1.ShellNetworkPolicyIngress.rules:type_name -> google.protobuf.Struct
	57, // [57:57] is the sub-list for method output_type
	57, // [57:57] is the sub-list for method input_type
	57, // [57:57] is the sub-list for extension type_name
	57, // [57:57] is the sub-list for extension extendee
	0,  // [0:57] is the sub-list for field type_name
}

func init() { file_charts_values_v1_gitlab_shell_proto_init() }
func file_charts_values_v1_gitlab_shell_proto_init() {
	if File_charts_values_v1_gitlab_shell_proto != nil {
		return
	}
	file_charts_values_v1_global_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_shell_proto_rawDesc), len(file_charts_values_v1_gitlab_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_gitlab_shell_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_gitlab_shell_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_gitlab_shell_proto_msgTypes,
	}.Build()
	File_charts_values_v1_gitlab_shell_proto = out.File
	file_charts_values_v1_gitlab_shell_proto_goTypes = nil
	file_charts_values_v1_gitlab_shell_proto_depIdxs = nil
}
