// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/gitlab_exporter.proto

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExporterValues is the top-level schema for the gitlab-exporter sub-chart values.
type ExporterValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image configuration.
	Image *ExporterImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Address the exporter listens on.
	ListenAddr string `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	// Kubernetes Service configuration.
	Service *ExporterService `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// Metrics and ServiceMonitor configuration.
	Metrics *ExporterMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Whether the gitlab-exporter sub-chart is enabled.
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// TLS configuration.
	Tls *ExporterTls `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	// Tolerations for pod scheduling.
	Tolerations []*structpb.Struct `protobuf:"bytes,7,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// Annotations applied to gitlab-exporter resources.
	Annotations *structpb.Struct `protobuf:"bytes,8,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Priority class assigned to pods.
	PriorityClassName string `protobuf:"bytes,9,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Labels applied to pods.
	PodLabels *structpb.Struct `protobuf:"bytes,10,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Common settings such as shared labels.
	Common *ExporterCommon `protobuf:"bytes,11,opt,name=common,proto3" json:"common,omitempty"`
	// Labels applied to the Service.
	ServiceLabels *structpb.Struct `protobuf:"bytes,12,opt,name=service_labels,json=serviceLabels,proto3" json:"service_labels,omitempty"`
	// Init container configuration.
	Init *ExporterInit `protobuf:"bytes,13,opt,name=init,proto3" json:"init,omitempty"`
	// Global settings shared with the gitlab-exporter sub-chart.
	Global *GlobalConfig `protobuf:"bytes,14,opt,name=global,proto3" json:"global,omitempty"`
	// Redis configuration.
	Redis *ExporterRedis `protobuf:"bytes,15,opt,name=redis,proto3" json:"redis,omitempty"`
	// PostgreSQL configuration.
	Psql *structpb.Struct `protobuf:"bytes,16,opt,name=psql,proto3" json:"psql,omitempty"`
	// Compute resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,17,opt,name=resources,proto3" json:"resources,omitempty"`
	// Pod-level security context.
	SecurityContext *structpb.Struct `protobuf:"bytes,18,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	// Container-level security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,19,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// ServiceAccount configuration.
	ServiceAccount *ExporterServiceAccount `protobuf:"bytes,20,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Additional environment variables to set.
	ExtraEnv *structpb.Struct `protobuf:"bytes,21,opt,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty"`
	// Deployment configuration.
	Deployment *ExporterDeployment `protobuf:"bytes,22,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Pod affinity/anti-affinity rules.
	Affinity      *structpb.Struct `protobuf:"bytes,23,opt,name=affinity,proto3" json:"affinity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterValues) Reset() {
	*x = ExporterValues{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterValues) ProtoMessage() {}

func (x *ExporterValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterValues.ProtoReflect.Descriptor instead.
func (*ExporterValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{0}
}

func (x *ExporterValues) GetImage() *ExporterImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ExporterValues) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *ExporterValues) GetService() *ExporterService {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ExporterValues) GetMetrics() *ExporterMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ExporterValues) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExporterValues) GetTls() *ExporterTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *ExporterValues) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *ExporterValues) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ExporterValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *ExporterValues) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *ExporterValues) GetCommon() *ExporterCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *ExporterValues) GetServiceLabels() *structpb.Struct {
	if x != nil {
		return x.ServiceLabels
	}
	return nil
}

func (x *ExporterValues) GetInit() *ExporterInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *ExporterValues) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ExporterValues) GetRedis() *ExporterRedis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *ExporterValues) GetPsql() *structpb.Struct {
	if x != nil {
		return x.Psql
	}
	return nil
}

func (x *ExporterValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ExporterValues) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *ExporterValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *ExporterValues) GetServiceAccount() *ExporterServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *ExporterValues) GetExtraEnv() *structpb.Struct {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

func (x *ExporterValues) GetDeployment() *ExporterDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *ExporterValues) GetAffinity() *structpb.Struct {
	if x != nil {
		return x.Affinity
	}
	return nil
}

// ExporterImage configures the container image.
type ExporterImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image repository.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Image pull policy.
	PullPolicy string `protobuf:"bytes,2,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	// Image pull secrets.
	PullSecrets []*structpb.Struct `protobuf:"bytes,3,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	// Container image tag.
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterImage) Reset() {
	*x = ExporterImage{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterImage) ProtoMessage() {}

func (x *ExporterImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterImage.ProtoReflect.Descriptor instead.
func (*ExporterImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{1}
}

func (x *ExporterImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ExporterImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *ExporterImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

func (x *ExporterImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// ExporterService configures the Kubernetes Service.
type ExporterService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Service type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// External port.
	ExternalPort uint32 `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	// Internal port.
	InternalPort  uint32 `protobuf:"varint,4,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterService) Reset() {
	*x = ExporterService{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterService) ProtoMessage() {}

func (x *ExporterService) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterService.ProtoReflect.Descriptor instead.
func (*ExporterService) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{2}
}

func (x *ExporterService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExporterService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExporterService) GetExternalPort() uint32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *ExporterService) GetInternalPort() uint32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

// ExporterMetrics configures metrics and the ServiceMonitor.
type ExporterMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Metrics port.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Metrics path.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// ServiceMonitor configuration.
	ServiceMonitor *ExporterMetricsServiceMonitor `protobuf:"bytes,4,opt,name=service_monitor,json=serviceMonitor,proto3" json:"service_monitor,omitempty"`
	// Annotations applied to metrics resources (deprecated).
	Annotations   *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterMetrics) Reset() {
	*x = ExporterMetrics{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterMetrics) ProtoMessage() {}

func (x *ExporterMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterMetrics.ProtoReflect.Descriptor instead.
func (*ExporterMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{3}
}

func (x *ExporterMetrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExporterMetrics) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExporterMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExporterMetrics) GetServiceMonitor() *ExporterMetricsServiceMonitor {
	if x != nil {
		return x.ServiceMonitor
	}
	return nil
}

func (x *ExporterMetrics) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ExporterMetricsServiceMonitor configures the Prometheus ServiceMonitor.
type ExporterMetricsServiceMonitor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the ServiceMonitor is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Additional labels applied to the ServiceMonitor.
	AdditionalLabels *structpb.Struct `protobuf:"bytes,2,opt,name=additional_labels,json=additionalLabels,proto3" json:"additional_labels,omitempty"`
	// Additional endpoint configuration.
	EndpointConfig *structpb.Struct `protobuf:"bytes,3,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExporterMetricsServiceMonitor) Reset() {
	*x = ExporterMetricsServiceMonitor{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterMetricsServiceMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterMetricsServiceMonitor) ProtoMessage() {}

func (x *ExporterMetricsServiceMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterMetricsServiceMonitor.ProtoReflect.Descriptor instead.
func (*ExporterMetricsServiceMonitor) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{4}
}

func (x *ExporterMetricsServiceMonitor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExporterMetricsServiceMonitor) GetAdditionalLabels() *structpb.Struct {
	if x != nil {
		return x.AdditionalLabels
	}
	return nil
}

func (x *ExporterMetricsServiceMonitor) GetEndpointConfig() *structpb.Struct {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

// ExporterTls configures TLS.
type ExporterTls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether TLS is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Name of the secret holding the TLS certificate.
	SecretName    string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterTls) Reset() {
	*x = ExporterTls{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterTls) ProtoMessage() {}

func (x *ExporterTls) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterTls.ProtoReflect.Descriptor instead.
func (*ExporterTls) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{5}
}

func (x *ExporterTls) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExporterTls) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

// ExporterCommon holds settings shared across gitlab-exporter resources.
type ExporterCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Labels applied to all resources.
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterCommon) Reset() {
	*x = ExporterCommon{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterCommon) ProtoMessage() {}

func (x *ExporterCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterCommon.ProtoReflect.Descriptor instead.
func (*ExporterCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{6}
}

func (x *ExporterCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ExporterInit configures the init container.
type ExporterInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image override.
	Image *structpb.Struct `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Init container security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,3,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExporterInit) Reset() {
	*x = ExporterInit{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterInit) ProtoMessage() {}

func (x *ExporterInit) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterInit.ProtoReflect.Descriptor instead.
func (*ExporterInit) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{7}
}

func (x *ExporterInit) GetImage() *structpb.Struct {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ExporterInit) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ExporterInit) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

// ExporterRedis configures Redis access.
type ExporterRedis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis authentication configuration.
	Auth          *structpb.Struct `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterRedis) Reset() {
	*x = ExporterRedis{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterRedis) ProtoMessage() {}

func (x *ExporterRedis) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterRedis.ProtoReflect.Descriptor instead.
func (*ExporterRedis) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{8}
}

func (x *ExporterRedis) GetAuth() *structpb.Struct {
	if x != nil {
		return x.Auth
	}
	return nil
}

// ExporterServiceAccount configures the ServiceAccount.
type ExporterServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deployment uses a ServiceAccount.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to create the ServiceAccount.
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Annotations applied to the ServiceAccount.
	Annotations   *structpb.Struct `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterServiceAccount) Reset() {
	*x = ExporterServiceAccount{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterServiceAccount) ProtoMessage() {}

func (x *ExporterServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterServiceAccount.ProtoReflect.Descriptor instead.
func (*ExporterServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{9}
}

func (x *ExporterServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExporterServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *ExporterServiceAccount) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// ExporterDeployment configures the Deployment.
type ExporterDeployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment update strategy.
	Strategy      *structpb.Struct `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterDeployment) Reset() {
	*x = ExporterDeployment{}
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterDeployment) ProtoMessage() {}

func (x *ExporterDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_exporter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterDeployment.ProtoReflect.Descriptor instead.
func (*ExporterDeployment) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP(), []int{10}
}

func (x *ExporterDeployment) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

var File_charts_values_v1_gitlab_exporter_proto protoreflect.FileDescriptor

const file_charts_values_v1_gitlab_exporter_proto_rawDesc = "" +
	"\n" +
	"&charts/values/v1/gitlab_exporter.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1dcharts/values/v1/global.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb1\n" +
	"\n" +
	"\x0eExporterValues\x125\n" +
	"\x05image\x18\x01 \x01(\v2\x1f.charts.values.v1.ExporterImageR\x05image\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12;\n" +
	"\aservice\x18\x03 \x01(\v2!.charts.values.v1.ExporterServiceR\aservice\x12;\n" +
	"\ametrics\x18\x04 \x01(\v2!.charts.values.v1.ExporterMetricsR\ametrics\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12/\n" +
	"\x03tls\x18\x06 \x01(\v2\x1d.charts.values.v1.ExporterTlsR\x03tls\x129\n" +
	"\vtolerations\x18\a \x03(\v2\x17.google.protobuf.StructR\vtolerations\x129\n" +
	"\vannotations\x18\b \x01(\v2\x17.google.protobuf.StructR\vannotations\x12.\n" +
	"\x13priority_class_name\x18\t \x01(\tR\x11priorityClassName\x126\n" +
	"\n" +
	"pod_labels\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x128\n" +
	"\x06common\x18\v \x01(\v2 .charts.values.v1.ExporterCommonR\x06common\x12>\n" +
	"\x0eservice_labels\x18\f \x01(\v2\x17.google.protobuf.StructR\rserviceLabels\x122\n" +
	"\x04init\x18\r \x01(\v2\x1e.charts.values.v1.ExporterInitR\x04init\x126\n" +
	"\x06global\x18\x0e \x01(\v2\x1e.charts.values.v1.GlobalConfigR\x06global\x125\n" +
	"\x05redis\x18\x0f \x01(\v2\x1f.charts.values.v1.ExporterRedisR\x05redis\x12+\n" +
	"\x04psql\x18\x10 \x01(\v2\x17.google.protobuf.StructR\x04psql\x125\n" +
	"\tresources\x18\x11 \x01(\v2\x17.google.protobuf.StructR\tresources\x12B\n" +
	"\x10security_context\x18\x12 \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12Q\n" +
	"\x0fservice_account\x18\x14 \x01(\v2(.charts.values.v1.ExporterServiceAccountR\x0eserviceAccount\x124\n" +
	"\textra_env\x18\x15 \x01(\v2\x17.google.protobuf.StructR\bextraEnv\x12D\n" +
	"\n" +
	"deployment\x18\x16 \x01(\v2$.charts.values.v1.ExporterDeploymentR\n" +
	"deployment\x123\n" +
	"\baffinity\x18\x17 \x01(\v2\x17.google.protobuf.StructR\baffinity:\x04\x88\xb5\x18\x01\"\xc8\x01\n" +
	"\rExporterImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12C\n" +
	"\vpull_policy\x18\x02 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x03 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag:\x04\x88\xb5\x18\x01\"\xa3\x01\n" +
	"\x0fExporterService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x120\n" +
	"\rexternal_port\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\fexternalPort\x120\n" +
	"\rinternal_port\x18\x04 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\finternalPort:\x04\x88\xb5\x18\x01\"\x81\x02\n" +
	"\x0fExporterMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12X\n" +
	"\x0fservice_monitor\x18\x04 \x01(\v2/.charts.values.v1.ExporterMetricsServiceMonitorR\x0eserviceMonitor\x12?\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x04\x98\xb5\x18\x05R\vannotations:\x04\x88\xb5\x18\x01\"\xc7\x01\n" +
	"\x1dExporterMetricsServiceMonitor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x11additional_labels\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10additionalLabels\x12@\n" +
	"\x0fendpoint_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eendpointConfig:\x04\x88\xb5\x18\x01\"N\n" +
	"\vExporterTls\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName:\x04\x88\xb5\x18\x01\"G\n" +
	"\x0eExporterCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01\"\xd1\x01\n" +
	"\fExporterInit\x12-\n" +
	"\x05image\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05image\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tresources\x12U\n" +
	"\x1acontainer_security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext:\x04\x88\xb5\x18\x01\"B\n" +
	"\rExporterRedis\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04auth:\x04\x88\xb5\x18\x01\"\x8b\x01\n" +
	"\x16ExporterServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x129\n" +
	"\vannotations\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"O\n" +
	"\x12ExporterDeployment\x123\n" +
	"\bstrategy\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bstrategy:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_gitlab_exporter_proto_rawDescOnce sync.Once
	file_charts_values_v1_gitlab_exporter_proto_rawDescData []byte
)

func file_charts_values_v1_gitlab_exporter_proto_rawDescGZIP() []byte {
	file_charts_values_v1_gitlab_exporter_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_gitlab_exporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_exporter_proto_rawDesc), len(file_charts_values_v1_gitlab_exporter_proto_rawDesc)))
	})
	return file_charts_values_v1_gitlab_exporter_proto_rawDescData
}

var file_charts_values_v1_gitlab_exporter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_charts_values_v1_gitlab_exporter_proto_goTypes = []any{
	(*ExporterValues)(nil),                // 0: charts.values.v1.ExporterValues
	(*ExporterImage)(nil),                 // 1: charts.values.v1.ExporterImage
	(*ExporterService)(nil),               // 2: charts.values.v1.ExporterService
	(*ExporterMetrics)(nil),               // 3: charts.values.v1.ExporterMetrics
	(*ExporterMetricsServiceMonitor)(nil), // 4: charts.values.v1.ExporterMetricsServiceMonitor
	(*ExporterTls)(nil),                   // 5: charts.values.v1.ExporterTls
	(*ExporterCommon)(nil),                // 6: charts.values.v1.ExporterCommon
	(*ExporterInit)(nil),                  // 7: charts.values.v1.ExporterInit
	(*ExporterRedis)(nil),                 // 8: charts.values.v1.ExporterRedis
	(*ExporterServiceAccount)(nil),        // 9: charts.values.v1.ExporterServiceAccount
	(*ExporterDeployment)(nil),            // 10: charts.values.v1.ExporterDeployment
	(*structpb.Struct)(nil),               // 11: google.protobuf.Struct
	(*GlobalConfig)(nil),                  // 12: charts.values.v1.GlobalConfig
}
var file_charts_values_v1_gitlab_exporter_proto_depIdxs = []int32{
	1,  // 0: charts.values.v1.ExporterValues.image:type_name -> charts.values.v1.ExporterImage
	2,  // 1: charts.values.v1.ExporterValues.service:type_name -> charts.values.v1.ExporterService
	3,  // 2: charts.values.v1.ExporterValues.metrics:type_name -> charts.values.v1.ExporterMetrics
	5,  // 3: charts.values.v1.ExporterValues.tls:type_name -> charts.values.v1.ExporterTls
	11, // 4: charts.values.v1.ExporterValues.tolerations:type_name -> google.protobuf.Struct
	11, // 5: charts.values.v1.ExporterValues.annotations:type_name -> google.protobuf.Struct
	11, // 6: charts.values.v1.ExporterValues.pod_labels:type_name -> google.protobuf.Struct
	6,  // 7: charts.values.v1.ExporterValues.common:type_name -> charts.values.v1.ExporterCommon
	11, // 8: charts.values.v1.ExporterValues.service_labels:type_name -> google.protobuf.Struct
	7,  // 9: charts.values.v1.ExporterValues.init:type_name -> charts.values.v1.ExporterInit
	12, // 10: charts.values.v1.ExporterValues.global:type_name -> charts.values.v1.GlobalConfig
	8,  // 11: charts.values.v1.ExporterValues.redis:type_name -> charts.values.v1.ExporterRedis
	11, // 12: charts.values.v1.ExporterValues.psql:type_name -> google.protobuf.Struct
	11, // 13: charts.values.v1.ExporterValues.resources:type_name -> google.protobuf.Struct
	11, // 14: charts.values.v1.ExporterValues.security_context:type_name -> google.protobuf.Struct
	11, // 15: charts.values.v1.ExporterValues.container_security_context:type_name -> google.protobuf.Struct
	9,  // 16: charts.values.v1.ExporterValues.service_account:type_name -> charts.values.v1.ExporterServiceAccount
	11, // 17: charts.values.v1.ExporterValues.extra_env:type_name -> google.protobuf.Struct
	10, // 18: charts.values.v1.ExporterValues.deployment:type_name -> charts.values.v1.ExporterDeployment
	11, // 19: charts.values.v1.ExporterValues.affinity:type_name -> google.protobuf.Struct
	11, // 20: charts.values.v1.ExporterImage.pull_secrets:type_name -> google.protobuf.Struct
	4,  // 21: charts.values.v1.ExporterMetrics.service_monitor:type_name -> charts.values.v1.ExporterMetricsServiceMonitor
	11, // 22: charts.values.v1.ExporterMetrics.annotations:type_name -> google.protobuf.Struct
	11, // 23: charts.values.v1.ExporterMetricsServiceMonitor.additional_labels:type_name -> google.protobuf.Struct
	11, // 24: charts.values.v1.ExporterMetricsServiceMonitor.endpoint_config:type_name -> google.protobuf.Struct
	11, // 25: charts.values.v1.ExporterCommon.labels:type_name -> google.protobuf.Struct
	11, // 26: charts.values.v1.ExporterInit.image:type_name -> google.protobuf.Struct
	11, // 27: charts.values.v1.ExporterInit.resources:type_name -> google.protobuf.Struct
	11, // 28: charts.values.v1.ExporterInit.container_security_context:type_name -> google.protobuf.Struct
	11, // 29: charts.values.v1.ExporterRedis.auth:type_name -> google.protobuf.Struct
	11, // 30: charts.values.v1.ExporterServiceAccount.annotations:type_name -> google.protobuf.Struct
	11, // 31: charts.values.v1.ExporterDeployment.strategy:type_name -> google.protobuf.Struct
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_charts_values_v1_gitlab_exporter_proto_init() }
func file_charts_values_v1_gitlab_exporter_proto_init() {
	if File_charts_values_v1_gitlab_exporter_proto != nil {
		return
	}
	file_charts_values_v1_global_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_exporter_proto_rawDesc), len(file_charts_values_v1_gitlab_exporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_gitlab_exporter_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_gitlab_exporter_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_gitlab_exporter_proto_msgTypes,
	}.Build()
	File_charts_values_v1_gitlab_exporter_proto = out.File
	file_charts_values_v1_gitlab_exporter_proto_goTypes = nil
	file_charts_values_v1_gitlab_exporter_proto_depIdxs = nil
}
