// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/gitlab_pages.proto

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PagesValues is the top-level schema for the gitlab-pages sub-chart values.
type PagesValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global settings shared with the gitlab-pages sub-chart.
	Global *GlobalConfig `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	// Horizontal Pod Autoscaler configuration.
	Hpa *PagesHpa `protobuf:"bytes,2,opt,name=hpa,proto3" json:"hpa,omitempty"`
	// KEDA autoscaling configuration.
	Keda *PagesKeda `protobuf:"bytes,3,opt,name=keda,proto3" json:"keda,omitempty"`
	// NetworkPolicy configuration.
	Networkpolicy *PagesNetworkPolicy `protobuf:"bytes,4,opt,name=networkpolicy,proto3" json:"networkpolicy,omitempty"`
	// Container image configuration.
	Image *PagesImage `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	// Kubernetes Service configuration.
	Service *PagesService `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	// Init container configuration.
	Init *PagesInit `protobuf:"bytes,7,opt,name=init,proto3" json:"init,omitempty"`
	// Deployment configuration.
	Deployment *PagesDeployment `protobuf:"bytes,8,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Ingress configuration.
	Ingress *PagesIngress `protobuf:"bytes,9,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// Gateway API route configuration.
	GatewayRoute *PagesGatewayRoute `protobuf:"bytes,10,opt,name=gateway_route,json=gatewayRoute,proto3" json:"gateway_route,omitempty"`
	// Tolerations for pod scheduling.
	Tolerations []*structpb.Struct `protobuf:"bytes,11,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// Whether pages runs in cluster mode.
	Cluster bool `protobuf:"varint,12,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Annotations applied to pages resources.
	Annotations *structpb.Struct `protobuf:"bytes,13,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Labels applied to pods.
	PodLabels *structpb.Struct `protobuf:"bytes,14,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Common settings such as shared labels.
	Common *PagesCommon `protobuf:"bytes,15,opt,name=common,proto3" json:"common,omitempty"`
	// Labels applied to the Service.
	ServiceLabels *structpb.Struct `protobuf:"bytes,16,opt,name=service_labels,json=serviceLabels,proto3" json:"service_labels,omitempty"`
	// Additional environment variables to set.
	ExtraEnv *structpb.Struct `protobuf:"bytes,17,opt,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty"`
	// Maximum number of pods unavailable during a disruption.
	MaxUnavailable uint32 `protobuf:"varint,18,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	// Compute resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,19,opt,name=resources,proto3" json:"resources,omitempty"`
	// Pod-level security context.
	SecurityContext *structpb.Struct `protobuf:"bytes,20,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	// Container-level security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,21,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// ServiceAccount configuration.
	ServiceAccount *PagesServiceAccount `protobuf:"bytes,22,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Pod priorityClassName used for eviction ordering.
	PriorityClassName string `protobuf:"bytes,23,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Timeout, in seconds, for requests to the artifacts server.
	ArtifactsServerTimeout uint32 `protobuf:"varint,24,opt,name=artifacts_server_timeout,json=artifactsServerTimeout,proto3" json:"artifacts_server_timeout,omitempty"`
	// URL of the artifacts server.
	ArtifactsServerUrl string `protobuf:"bytes,25,opt,name=artifacts_server_url,json=artifactsServerUrl,proto3" json:"artifacts_server_url,omitempty"`
	// HTTP client timeout for requests to the GitLab server.
	GitlabClientHttpTimeout string `protobuf:"bytes,26,opt,name=gitlab_client_http_timeout,json=gitlabClientHttpTimeout,proto3" json:"gitlab_client_http_timeout,omitempty"`
	// Expiry for the GitLab client JWT.
	GitlabClientJwtExpiry string `protobuf:"bytes,27,opt,name=gitlab_client_jwt_expiry,json=gitlabClientJwtExpiry,proto3" json:"gitlab_client_jwt_expiry,omitempty"`
	// Public GitLab server URL.
	GitlabServer string `protobuf:"bytes,28,opt,name=gitlab_server,json=gitlabServer,proto3" json:"gitlab_server,omitempty"`
	// Extra HTTP response headers, as a list of strings.
	Headers []string `protobuf:"bytes,29,rep,name=headers,proto3" json:"headers,omitempty"`
	// Whether to allow insecure ciphers.
	InsecureCiphers bool `protobuf:"varint,30,opt,name=insecure_ciphers,json=insecureCiphers,proto3" json:"insecure_ciphers,omitempty"`
	// Internal GitLab server URL.
	InternalGitlabServer string `protobuf:"bytes,31,opt,name=internal_gitlab_server,json=internalGitlabServer,proto3" json:"internal_gitlab_server,omitempty"`
	// Log output format.
	LogFormat string `protobuf:"bytes,32,opt,name=log_format,json=logFormat,proto3" json:"log_format,omitempty"`
	// Whether to enable verbose logging.
	LogVerbose bool `protobuf:"varint,33,opt,name=log_verbose,json=logVerbose,proto3" json:"log_verbose,omitempty"`
	// Maximum number of concurrent connections.
	MaxConnections uint32 `protobuf:"varint,34,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	// Whether to redirect HTTP requests to HTTPS.
	RedirectHttp bool `protobuf:"varint,35,opt,name=redirect_http,json=redirectHttp,proto3" json:"redirect_http,omitempty"`
	// Sentry error reporting configuration.
	Sentry *PagesSentry `protobuf:"bytes,36,opt,name=sentry,proto3" json:"sentry,omitempty"`
	// URI used for the readiness/status endpoint.
	StatusUri string `protobuf:"bytes,37,opt,name=status_uri,json=statusUri,proto3" json:"status_uri,omitempty"`
	// TLS version bounds.
	Tls *PagesTls `protobuf:"bytes,38,opt,name=tls,proto3" json:"tls,omitempty"`
	// Whether to use an HTTP proxy.
	UseHttpProxy bool `protobuf:"varint,39,opt,name=use_http_proxy,json=useHttpProxy,proto3" json:"use_http_proxy,omitempty"`
	// Whether to use the PROXY protocol v2.
	UseProxyV2 bool `protobuf:"varint,40,opt,name=use_proxy_v2,json=useProxyV2,proto3" json:"use_proxy_v2,omitempty"`
	// Metrics and ServiceMonitor configuration.
	Metrics *PagesMetrics `protobuf:"bytes,41,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Workhorse connection settings (defaults to being part of Webservice).
	Workhorse *structpb.Struct `protobuf:"bytes,42,opt,name=workhorse,proto3" json:"workhorse,omitempty"`
	// Pod affinity/anti-affinity rules.
	Affinity *structpb.Struct `protobuf:"bytes,43,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Topology spread constraints for pod scheduling.
	TopologySpreadConstraints []*structpb.Struct `protobuf:"bytes,44,rep,name=topology_spread_constraints,json=topologySpreadConstraints,proto3" json:"topology_spread_constraints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PagesValues) Reset() {
	*x = PagesValues{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesValues) ProtoMessage() {}

func (x *PagesValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesValues.ProtoReflect.Descriptor instead.
func (*PagesValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{0}
}

func (x *PagesValues) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *PagesValues) GetHpa() *PagesHpa {
	if x != nil {
		return x.Hpa
	}
	return nil
}

func (x *PagesValues) GetKeda() *PagesKeda {
	if x != nil {
		return x.Keda
	}
	return nil
}

func (x *PagesValues) GetNetworkpolicy() *PagesNetworkPolicy {
	if x != nil {
		return x.Networkpolicy
	}
	return nil
}

func (x *PagesValues) GetImage() *PagesImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *PagesValues) GetService() *PagesService {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *PagesValues) GetInit() *PagesInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *PagesValues) GetDeployment() *PagesDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *PagesValues) GetIngress() *PagesIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *PagesValues) GetGatewayRoute() *PagesGatewayRoute {
	if x != nil {
		return x.GatewayRoute
	}
	return nil
}

func (x *PagesValues) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *PagesValues) GetCluster() bool {
	if x != nil {
		return x.Cluster
	}
	return false
}

func (x *PagesValues) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PagesValues) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *PagesValues) GetCommon() *PagesCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *PagesValues) GetServiceLabels() *structpb.Struct {
	if x != nil {
		return x.ServiceLabels
	}
	return nil
}

func (x *PagesValues) GetExtraEnv() *structpb.Struct {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

func (x *PagesValues) GetMaxUnavailable() uint32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *PagesValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PagesValues) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *PagesValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *PagesValues) GetServiceAccount() *PagesServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *PagesValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *PagesValues) GetArtifactsServerTimeout() uint32 {
	if x != nil {
		return x.ArtifactsServerTimeout
	}
	return 0
}

func (x *PagesValues) GetArtifactsServerUrl() string {
	if x != nil {
		return x.ArtifactsServerUrl
	}
	return ""
}

func (x *PagesValues) GetGitlabClientHttpTimeout() string {
	if x != nil {
		return x.GitlabClientHttpTimeout
	}
	return ""
}

func (x *PagesValues) GetGitlabClientJwtExpiry() string {
	if x != nil {
		return x.GitlabClientJwtExpiry
	}
	return ""
}

func (x *PagesValues) GetGitlabServer() string {
	if x != nil {
		return x.GitlabServer
	}
	return ""
}

func (x *PagesValues) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PagesValues) GetInsecureCiphers() bool {
	if x != nil {
		return x.InsecureCiphers
	}
	return false
}

func (x *PagesValues) GetInternalGitlabServer() string {
	if x != nil {
		return x.InternalGitlabServer
	}
	return ""
}

func (x *PagesValues) GetLogFormat() string {
	if x != nil {
		return x.LogFormat
	}
	return ""
}

func (x *PagesValues) GetLogVerbose() bool {
	if x != nil {
		return x.LogVerbose
	}
	return false
}

func (x *PagesValues) GetMaxConnections() uint32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *PagesValues) GetRedirectHttp() bool {
	if x != nil {
		return x.RedirectHttp
	}
	return false
}

func (x *PagesValues) GetSentry() *PagesSentry {
	if x != nil {
		return x.Sentry
	}
	return nil
}

func (x *PagesValues) GetStatusUri() string {
	if x != nil {
		return x.StatusUri
	}
	return ""
}

func (x *PagesValues) GetTls() *PagesTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *PagesValues) GetUseHttpProxy() bool {
	if x != nil {
		return x.UseHttpProxy
	}
	return false
}

func (x *PagesValues) GetUseProxyV2() bool {
	if x != nil {
		return x.UseProxyV2
	}
	return false
}

func (x *PagesValues) GetMetrics() *PagesMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PagesValues) GetWorkhorse() *structpb.Struct {
	if x != nil {
		return x.Workhorse
	}
	return nil
}

func (x *PagesValues) GetAffinity() *structpb.Struct {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *PagesValues) GetTopologySpreadConstraints() []*structpb.Struct {
	if x != nil {
		return x.TopologySpreadConstraints
	}
	return nil
}

// PagesHpa configures the Horizontal Pod Autoscaler.
type PagesHpa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of replicas.
	MaxReplicas uint32 `protobuf:"varint,1,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// Minimum number of replicas.
	MinReplicas uint32 `protobuf:"varint,2,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// CPU-based scaling target.
	Cpu *PagesHpaCpu `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Overrides the HPA metrics definition.
	CustomMetrics []*structpb.Struct `protobuf:"bytes,4,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty"`
	// Scaling behavior configuration.
	Behavior      *PagesHpaBehavior `protobuf:"bytes,5,opt,name=behavior,proto3" json:"behavior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesHpa) Reset() {
	*x = PagesHpa{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesHpa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesHpa) ProtoMessage() {}

func (x *PagesHpa) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesHpa.ProtoReflect.Descriptor instead.
func (*PagesHpa) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{1}
}

func (x *PagesHpa) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *PagesHpa) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *PagesHpa) GetCpu() *PagesHpaCpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *PagesHpa) GetCustomMetrics() []*structpb.Struct {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

func (x *PagesHpa) GetBehavior() *PagesHpaBehavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

// PagesHpaCpu configures CPU-based autoscaling.
type PagesHpaCpu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target type: Utilization or AverageValue.
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Target average CPU value.
	TargetAverageValue string `protobuf:"bytes,2,opt,name=target_average_value,json=targetAverageValue,proto3" json:"target_average_value,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PagesHpaCpu) Reset() {
	*x = PagesHpaCpu{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesHpaCpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesHpaCpu) ProtoMessage() {}

func (x *PagesHpaCpu) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesHpaCpu.ProtoReflect.Descriptor instead.
func (*PagesHpaCpu) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{2}
}

func (x *PagesHpaCpu) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *PagesHpaCpu) GetTargetAverageValue() string {
	if x != nil {
		return x.TargetAverageValue
	}
	return ""
}

// PagesHpaBehavior configures scaling behavior.
type PagesHpaBehavior struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scale-down behavior.
	ScaleDown     *PagesHpaScaleDown `protobuf:"bytes,1,opt,name=scale_down,json=scaleDown,proto3" json:"scale_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesHpaBehavior) Reset() {
	*x = PagesHpaBehavior{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesHpaBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesHpaBehavior) ProtoMessage() {}

func (x *PagesHpaBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesHpaBehavior.ProtoReflect.Descriptor instead.
func (*PagesHpaBehavior) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{3}
}

func (x *PagesHpaBehavior) GetScaleDown() *PagesHpaScaleDown {
	if x != nil {
		return x.ScaleDown
	}
	return nil
}

// PagesHpaScaleDown configures scale-down behavior.
type PagesHpaScaleDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stabilization window, in seconds, before scaling down.
	StabilizationWindowSeconds uint32 `protobuf:"varint,1,opt,name=stabilization_window_seconds,json=stabilizationWindowSeconds,proto3" json:"stabilization_window_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PagesHpaScaleDown) Reset() {
	*x = PagesHpaScaleDown{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesHpaScaleDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesHpaScaleDown) ProtoMessage() {}

func (x *PagesHpaScaleDown) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesHpaScaleDown.ProtoReflect.Descriptor instead.
func (*PagesHpaScaleDown) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{4}
}

func (x *PagesHpaScaleDown) GetStabilizationWindowSeconds() uint32 {
	if x != nil {
		return x.StabilizationWindowSeconds
	}
	return 0
}

// PagesKeda configures KEDA autoscaling.
type PagesKeda struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether KEDA autoscaling is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Polling interval, in seconds.
	PollingInterval uint32 `protobuf:"varint,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	// Cooldown period, in seconds.
	CooldownPeriod uint32 `protobuf:"varint,3,opt,name=cooldown_period,json=cooldownPeriod,proto3" json:"cooldown_period,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PagesKeda) Reset() {
	*x = PagesKeda{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesKeda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesKeda) ProtoMessage() {}

func (x *PagesKeda) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesKeda.ProtoReflect.Descriptor instead.
func (*PagesKeda) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{5}
}

func (x *PagesKeda) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesKeda) GetPollingInterval() uint32 {
	if x != nil {
		return x.PollingInterval
	}
	return 0
}

func (x *PagesKeda) GetCooldownPeriod() uint32 {
	if x != nil {
		return x.CooldownPeriod
	}
	return 0
}

// PagesNetworkPolicy configures the NetworkPolicy.
type PagesNetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the NetworkPolicy is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules.
	Egress *PagesNetworkPolicyEgress `protobuf:"bytes,2,opt,name=egress,proto3" json:"egress,omitempty"`
	// Ingress rules.
	Ingress *PagesNetworkPolicyIngress `protobuf:"bytes,3,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// Annotations applied to the NetworkPolicy.
	Annotations   *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesNetworkPolicy) Reset() {
	*x = PagesNetworkPolicy{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesNetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesNetworkPolicy) ProtoMessage() {}

func (x *PagesNetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesNetworkPolicy.ProtoReflect.Descriptor instead.
func (*PagesNetworkPolicy) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{6}
}

func (x *PagesNetworkPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesNetworkPolicy) GetEgress() *PagesNetworkPolicyEgress {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *PagesNetworkPolicy) GetIngress() *PagesNetworkPolicyIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *PagesNetworkPolicy) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// PagesNetworkPolicyEgress configures egress rules.
type PagesNetworkPolicyEgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether egress restrictions are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules.
	Rules         []*structpb.Struct `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesNetworkPolicyEgress) Reset() {
	*x = PagesNetworkPolicyEgress{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesNetworkPolicyEgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesNetworkPolicyEgress) ProtoMessage() {}

func (x *PagesNetworkPolicyEgress) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesNetworkPolicyEgress.ProtoReflect.Descriptor instead.
func (*PagesNetworkPolicyEgress) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{7}
}

func (x *PagesNetworkPolicyEgress) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesNetworkPolicyEgress) GetRules() []*structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

// PagesNetworkPolicyIngress configures ingress rules.
type PagesNetworkPolicyIngress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether ingress restrictions are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Ingress rules.
	Rules         []*structpb.Struct `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesNetworkPolicyIngress) Reset() {
	*x = PagesNetworkPolicyIngress{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesNetworkPolicyIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesNetworkPolicyIngress) ProtoMessage() {}

func (x *PagesNetworkPolicyIngress) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesNetworkPolicyIngress.ProtoReflect.Descriptor instead.
func (*PagesNetworkPolicyIngress) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{8}
}

func (x *PagesNetworkPolicyIngress) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesNetworkPolicyIngress) GetRules() []*structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

// PagesImage configures the container image.
type PagesImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image repository.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Container image tag.
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Image pull policy.
	PullPolicy string `protobuf:"bytes,3,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	// Image pull secrets.
	PullSecrets   []*structpb.Struct `protobuf:"bytes,4,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesImage) Reset() {
	*x = PagesImage{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesImage) ProtoMessage() {}

func (x *PagesImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesImage.ProtoReflect.Descriptor instead.
func (*PagesImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{9}
}

func (x *PagesImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PagesImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PagesImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *PagesImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

// PagesService configures the Kubernetes Service.
type PagesService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service type.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// External port.
	ExternalPort uint32 `protobuf:"varint,2,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	// Internal port.
	InternalPort uint32 `protobuf:"varint,3,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	// Annotations applied to the Service.
	Annotations *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Custom domains Service configuration.
	CustomDomains *PagesServiceCustomDomains `protobuf:"bytes,5,opt,name=custom_domains,json=customDomains,proto3" json:"custom_domains,omitempty"`
	// Metrics Service configuration.
	Metrics *PagesServiceMetrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Primary Service configuration.
	Primary *PagesServicePrimary `protobuf:"bytes,7,opt,name=primary,proto3" json:"primary,omitempty"`
	// Session affinity mode.
	SessionAffinity string `protobuf:"bytes,8,opt,name=session_affinity,json=sessionAffinity,proto3" json:"session_affinity,omitempty"`
	// Session affinity configuration.
	SessionAffinityConfig *structpb.Struct `protobuf:"bytes,9,opt,name=session_affinity_config,json=sessionAffinityConfig,proto3" json:"session_affinity_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PagesService) Reset() {
	*x = PagesService{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesService) ProtoMessage() {}

func (x *PagesService) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesService.ProtoReflect.Descriptor instead.
func (*PagesService) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{10}
}

func (x *PagesService) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PagesService) GetExternalPort() uint32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *PagesService) GetInternalPort() uint32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *PagesService) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PagesService) GetCustomDomains() *PagesServiceCustomDomains {
	if x != nil {
		return x.CustomDomains
	}
	return nil
}

func (x *PagesService) GetMetrics() *PagesServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PagesService) GetPrimary() *PagesServicePrimary {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *PagesService) GetSessionAffinity() string {
	if x != nil {
		return x.SessionAffinity
	}
	return ""
}

func (x *PagesService) GetSessionAffinityConfig() *structpb.Struct {
	if x != nil {
		return x.SessionAffinityConfig
	}
	return nil
}

// PagesServiceCustomDomains configures the custom domains Service.
type PagesServiceCustomDomains struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service type.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Internal HTTPS port.
	InternalHttpsPort uint32 `protobuf:"varint,2,opt,name=internal_https_port,json=internalHttpsPort,proto3" json:"internal_https_port,omitempty"`
	// NodePort configuration.
	NodePort *structpb.Struct `protobuf:"bytes,3,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	// Annotations applied to the Service.
	Annotations   *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesServiceCustomDomains) Reset() {
	*x = PagesServiceCustomDomains{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesServiceCustomDomains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesServiceCustomDomains) ProtoMessage() {}

func (x *PagesServiceCustomDomains) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesServiceCustomDomains.ProtoReflect.Descriptor instead.
func (*PagesServiceCustomDomains) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{11}
}

func (x *PagesServiceCustomDomains) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PagesServiceCustomDomains) GetInternalHttpsPort() uint32 {
	if x != nil {
		return x.InternalHttpsPort
	}
	return 0
}

func (x *PagesServiceCustomDomains) GetNodePort() *structpb.Struct {
	if x != nil {
		return x.NodePort
	}
	return nil
}

func (x *PagesServiceCustomDomains) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// PagesServiceMetrics configures the metrics Service.
type PagesServiceMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotations applied to the metrics Service.
	Annotations   *structpb.Struct `protobuf:"bytes,1,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesServiceMetrics) Reset() {
	*x = PagesServiceMetrics{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesServiceMetrics) ProtoMessage() {}

func (x *PagesServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesServiceMetrics.ProtoReflect.Descriptor instead.
func (*PagesServiceMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{12}
}

func (x *PagesServiceMetrics) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// PagesServicePrimary configures the primary Service.
type PagesServicePrimary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotations applied to the primary Service.
	Annotations   *structpb.Struct `protobuf:"bytes,1,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesServicePrimary) Reset() {
	*x = PagesServicePrimary{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesServicePrimary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesServicePrimary) ProtoMessage() {}

func (x *PagesServicePrimary) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesServicePrimary.ProtoReflect.Descriptor instead.
func (*PagesServicePrimary) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{13}
}

func (x *PagesServicePrimary) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// PagesInit configures the init container.
type PagesInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image override.
	Image *structpb.Struct `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Init container security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,3,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PagesInit) Reset() {
	*x = PagesInit{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesInit) ProtoMessage() {}

func (x *PagesInit) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesInit.ProtoReflect.Descriptor instead.
func (*PagesInit) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{14}
}

func (x *PagesInit) GetImage() *structpb.Struct {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *PagesInit) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PagesInit) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

// PagesDeployment configures the Deployment.
type PagesDeployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment update strategy.
	Strategy *structpb.Struct `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Readiness probe configuration.
	ReadinessProbe *PagesReadinessProbe `protobuf:"bytes,2,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PagesDeployment) Reset() {
	*x = PagesDeployment{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesDeployment) ProtoMessage() {}

func (x *PagesDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesDeployment.ProtoReflect.Descriptor instead.
func (*PagesDeployment) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{15}
}

func (x *PagesDeployment) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *PagesDeployment) GetReadinessProbe() *PagesReadinessProbe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

// PagesReadinessProbe configures the readiness probe.
type PagesReadinessProbe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delay, in seconds, before the probe is first run.
	InitialDelaySeconds uint32 `protobuf:"varint,1,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"`
	// How often, in seconds, to run the probe.
	PeriodSeconds uint32 `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// Timeout, in seconds, for the probe.
	TimeoutSeconds uint32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Consecutive successes required to be considered ready.
	SuccessThreshold uint32 `protobuf:"varint,4,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	// Consecutive failures required to be considered not ready.
	FailureThreshold uint32 `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PagesReadinessProbe) Reset() {
	*x = PagesReadinessProbe{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesReadinessProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesReadinessProbe) ProtoMessage() {}

func (x *PagesReadinessProbe) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesReadinessProbe.ProtoReflect.Descriptor instead.
func (*PagesReadinessProbe) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{16}
}

func (x *PagesReadinessProbe) GetInitialDelaySeconds() uint32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *PagesReadinessProbe) GetPeriodSeconds() uint32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *PagesReadinessProbe) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *PagesReadinessProbe) GetSuccessThreshold() uint32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *PagesReadinessProbe) GetFailureThreshold() uint32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

// PagesIngress configures the Ingress.
type PagesIngress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ingress apiVersion override.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Annotations applied to the Ingress.
	Annotations *structpb.Struct `protobuf:"bytes,2,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Whether to configure cert-manager for the Ingress.
	ConfigureCertmanager bool `protobuf:"varint,3,opt,name=configure_certmanager,json=configureCertmanager,proto3" json:"configure_certmanager,omitempty"`
	// TLS configuration.
	Tls *structpb.Struct `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	// Ingress path.
	Path          string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesIngress) Reset() {
	*x = PagesIngress{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesIngress) ProtoMessage() {}

func (x *PagesIngress) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesIngress.ProtoReflect.Descriptor instead.
func (*PagesIngress) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{17}
}

func (x *PagesIngress) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PagesIngress) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PagesIngress) GetConfigureCertmanager() bool {
	if x != nil {
		return x.ConfigureCertmanager
	}
	return false
}

func (x *PagesIngress) GetTls() *structpb.Struct {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *PagesIngress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// PagesGatewayRoute configures the Gateway API route.
type PagesGatewayRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the Gateway API route is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Gateway listener section name.
	SectionName string `protobuf:"bytes,2,opt,name=section_name,json=sectionName,proto3" json:"section_name,omitempty"`
	// Gateway name.
	GatewayName string `protobuf:"bytes,3,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// Gateway namespace.
	GatewayNamespace string `protobuf:"bytes,4,opt,name=gateway_namespace,json=gatewayNamespace,proto3" json:"gateway_namespace,omitempty"`
	// Annotations applied to the route.
	Annotations *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Route timeouts.
	Timeouts *structpb.Struct `protobuf:"bytes,6,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	// Route filters.
	Filters       []*structpb.Struct `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesGatewayRoute) Reset() {
	*x = PagesGatewayRoute{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesGatewayRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesGatewayRoute) ProtoMessage() {}

func (x *PagesGatewayRoute) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesGatewayRoute.ProtoReflect.Descriptor instead.
func (*PagesGatewayRoute) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{18}
}

func (x *PagesGatewayRoute) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesGatewayRoute) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *PagesGatewayRoute) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *PagesGatewayRoute) GetGatewayNamespace() string {
	if x != nil {
		return x.GatewayNamespace
	}
	return ""
}

func (x *PagesGatewayRoute) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PagesGatewayRoute) GetTimeouts() *structpb.Struct {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

func (x *PagesGatewayRoute) GetFilters() []*structpb.Struct {
	if x != nil {
		return x.Filters
	}
	return nil
}

// PagesCommon holds settings shared across pages resources.
type PagesCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Labels applied to all resources.
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesCommon) Reset() {
	*x = PagesCommon{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesCommon) ProtoMessage() {}

func (x *PagesCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesCommon.ProtoReflect.Descriptor instead.
func (*PagesCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{19}
}

func (x *PagesCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

// PagesSentry configures Sentry error reporting.
type PagesSentry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Sentry reporting is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Sentry DSN.
	Dsn string `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// Sentry environment.
	Environment   string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesSentry) Reset() {
	*x = PagesSentry{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesSentry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesSentry) ProtoMessage() {}

func (x *PagesSentry) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesSentry.ProtoReflect.Descriptor instead.
func (*PagesSentry) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{20}
}

func (x *PagesSentry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesSentry) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *PagesSentry) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// PagesTls configures TLS version bounds.
type PagesTls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum TLS version.
	MinVersion string `protobuf:"bytes,1,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	// Maximum TLS version.
	MaxVersion    string `protobuf:"bytes,2,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesTls) Reset() {
	*x = PagesTls{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesTls) ProtoMessage() {}

func (x *PagesTls) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesTls.ProtoReflect.Descriptor instead.
func (*PagesTls) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{21}
}

func (x *PagesTls) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *PagesTls) GetMaxVersion() string {
	if x != nil {
		return x.MaxVersion
	}
	return ""
}

// PagesMetrics configures metrics and the ServiceMonitor.
type PagesMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Metrics port.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Metrics path.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Metrics TLS configuration.
	Tls *PagesMetricsTls `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	// ServiceMonitor configuration.
	ServiceMonitor *PagesMetricsServiceMonitor `protobuf:"bytes,5,opt,name=service_monitor,json=serviceMonitor,proto3" json:"service_monitor,omitempty"`
	// Annotations applied to metrics resources (deprecated).
	Annotations   *structpb.Struct `protobuf:"bytes,6,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesMetrics) Reset() {
	*x = PagesMetrics{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesMetrics) ProtoMessage() {}

func (x *PagesMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesMetrics.ProtoReflect.Descriptor instead.
func (*PagesMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{22}
}

func (x *PagesMetrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesMetrics) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PagesMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PagesMetrics) GetTls() *PagesMetricsTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *PagesMetrics) GetServiceMonitor() *PagesMetricsServiceMonitor {
	if x != nil {
		return x.ServiceMonitor
	}
	return nil
}

func (x *PagesMetrics) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// PagesMetricsTls configures TLS for the metrics endpoint.
type PagesMetricsTls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics TLS is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Name of the secret holding the metrics TLS certificate.
	SecretName    string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesMetricsTls) Reset() {
	*x = PagesMetricsTls{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesMetricsTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesMetricsTls) ProtoMessage() {}

func (x *PagesMetricsTls) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesMetricsTls.ProtoReflect.Descriptor instead.
func (*PagesMetricsTls) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{23}
}

func (x *PagesMetricsTls) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesMetricsTls) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

// PagesMetricsServiceMonitor configures the Prometheus ServiceMonitor.
type PagesMetricsServiceMonitor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the ServiceMonitor is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Additional labels applied to the ServiceMonitor.
	AdditionalLabels *structpb.Struct `protobuf:"bytes,2,opt,name=additional_labels,json=additionalLabels,proto3" json:"additional_labels,omitempty"`
	// Additional endpoint configuration.
	EndpointConfig *structpb.Struct `protobuf:"bytes,3,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PagesMetricsServiceMonitor) Reset() {
	*x = PagesMetricsServiceMonitor{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesMetricsServiceMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesMetricsServiceMonitor) ProtoMessage() {}

func (x *PagesMetricsServiceMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesMetricsServiceMonitor.ProtoReflect.Descriptor instead.
func (*PagesMetricsServiceMonitor) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{24}
}

func (x *PagesMetricsServiceMonitor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesMetricsServiceMonitor) GetAdditionalLabels() *structpb.Struct {
	if x != nil {
		return x.AdditionalLabels
	}
	return nil
}

func (x *PagesMetricsServiceMonitor) GetEndpointConfig() *structpb.Struct {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

// PagesServiceAccount configures the ServiceAccount.
type PagesServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deployment uses a ServiceAccount.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to create the ServiceAccount.
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Annotations applied to the ServiceAccount.
	Annotations   *structpb.Struct `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesServiceAccount) Reset() {
	*x = PagesServiceAccount{}
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesServiceAccount) ProtoMessage() {}

func (x *PagesServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_gitlab_pages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesServiceAccount.ProtoReflect.Descriptor instead.
func (*PagesServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_gitlab_pages_proto_rawDescGZIP(), []int{25}
}

func (x *PagesServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PagesServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *PagesServiceAccount) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_charts_values_v1_gitlab_pages_proto protoreflect.FileDescriptor

const file_charts_values_v1_gitlab_pages_proto_rawDesc = "" +
	"\n" +
	"#charts/values/v1/gitlab_pages.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1dcharts/values/v1/global.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x12\n" +
	"\vPagesValues\x126\n" +
	"\x06global\x18\x01 \x01(\v2\x1e.charts.values.v1.GlobalConfigR\x06global\x12,\n" +
	"\x03hpa\x18\x02 \x01(\v2\x1a.charts.values.v1.PagesHpaR\x03hpa\x12/\n" +
	"\x04keda\x18\x03 \x01(\v2\x1b.charts.values.v1.PagesKedaR\x04keda\x12J\n" +
	"\rnetworkpolicy\x18\x04 \x01(\v2$.charts.values.v1.PagesNetworkPolicyR\rnetworkpolicy\x122\n" +
	"\x05image\x18\x05 \x01(\v2\x1c.charts.values.v1.PagesImageR\x05image\x128\n" +
	"\aservice\x18\x06 \x01(\v2\x1e.charts.values.v1.PagesServiceR\aservice\x12/\n" +
	"\x04init\x18\a \x01(\v2\x1b.charts.values.v1.PagesInitR\x04init\x12A\n" +
	"\n" +
	"deployment\x18\b \x01(\v2!.charts.values.v1.PagesDeploymentR\n" +
	"deployment\x128\n" +
	"\aingress\x18\t \x01(\v2\x1e.charts.values.v1.PagesIngressR\aingress\x12H\n" +
	"\rgateway_route\x18\n" +
	" \x01(\v2#.charts.values.v1.PagesGatewayRouteR\fgatewayRoute\x129\n" +
	"\vtolerations\x18\v \x03(\v2\x17.google.protobuf.StructR\vtolerations\x12\x18\n" +
	"\acluster\x18\f \x01(\bR\acluster\x129\n" +
	"\vannotations\x18\r \x01(\v2\x17.google.protobuf.StructR\vannotations\x126\n" +
	"\n" +
	"pod_labels\x18\x0e \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x125\n" +
	"\x06common\x18\x0f \x01(\v2\x1d.charts.values.v1.PagesCommonR\x06common\x12>\n" +
	"\x0eservice_labels\x18\x10 \x01(\v2\x17.google.protobuf.StructR\rserviceLabels\x124\n" +
	"\textra_env\x18\x11 \x01(\v2\x17.google.protobuf.StructR\bextraEnv\x12'\n" +
	"\x0fmax_unavailable\x18\x12 \x01(\rR\x0emaxUnavailable\x125\n" +
	"\tresources\x18\x13 \x01(\v2\x17.google.protobuf.StructR\tresources\x12B\n" +
	"\x10security_context\x18\x14 \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\x15 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12N\n" +
	"\x0fservice_account\x18\x16 \x01(\v2%.charts.values.v1.PagesServiceAccountR\x0eserviceAccount\x12.\n" +
	"\x13priority_class_name\x18\x17 \x01(\tR\x11priorityClassName\x128\n" +
	"\x18artifacts_server_timeout\x18\x18 \x01(\rR\x16artifactsServerTimeout\x120\n" +
	"\x14artifacts_server_url\x18\x19 \x01(\tR\x12artifactsServerUrl\x12;\n" +
	"\x1agitlab_client_http_timeout\x18\x1a \x01(\tR\x17gitlabClientHttpTimeout\x127\n" +
	"\x18gitlab_client_jwt_expiry\x18\x1b \x01(\tR\x15gitlabClientJwtExpiry\x12#\n" +
	"\rgitlab_server\x18\x1c \x01(\tR\fgitlabServer\x12\x18\n" +
	"\aheaders\x18\x1d \x03(\tR\aheaders\x12)\n" +
	"\x10insecure_ciphers\x18\x1e \x01(\bR\x0finsecureCiphers\x124\n" +
	"\x16internal_gitlab_server\x18\x1f \x01(\tR\x14internalGitlabServer\x12\x1d\n" +
	"\n" +
	"log_format\x18  \x01(\tR\tlogFormat\x12\x1f\n" +
	"\vlog_verbose\x18! \x01(\bR\n" +
	"logVerbose\x12'\n" +
	"\x0fmax_connections\x18\" \x01(\rR\x0emaxConnections\x12#\n" +
	"\rredirect_http\x18# \x01(\bR\fredirectHttp\x125\n" +
	"\x06sentry\x18$ \x01(\v2\x1d.charts.values.v1.PagesSentryR\x06sentry\x12\x1d\n" +
	"\n" +
	"status_uri\x18% \x01(\tR\tstatusUri\x12,\n" +
	"\x03tls\x18& \x01(\v2\x1a.charts.values.v1.PagesTlsR\x03tls\x126\n" +
	"\x0euse_http_proxy\x18' \x01(\bB\x10\x92\xb5\x18\fuseHTTPProxyR\fuseHttpProxy\x12 \n" +
	"\fuse_proxy_v2\x18( \x01(\bR\n" +
	"useProxyV2\x128\n" +
	"\ametrics\x18) \x01(\v2\x1e.charts.values.v1.PagesMetricsR\ametrics\x125\n" +
	"\tworkhorse\x18* \x01(\v2\x17.google.protobuf.StructR\tworkhorse\x123\n" +
	"\baffinity\x18+ \x01(\v2\x17.google.protobuf.StructR\baffinity\x12W\n" +
	"\x1btopology_spread_constraints\x18, \x03(\v2\x17.google.protobuf.StructR\x19topologySpreadConstraints:\x04\x88\xb5\x18\x01\"\x87\x02\n" +
	"\bPagesHpa\x12!\n" +
	"\fmax_replicas\x18\x01 \x01(\rR\vmaxReplicas\x12!\n" +
	"\fmin_replicas\x18\x02 \x01(\rR\vminReplicas\x12/\n" +
	"\x03cpu\x18\x03 \x01(\v2\x1d.charts.values.v1.PagesHpaCpuR\x03cpu\x12>\n" +
	"\x0ecustom_metrics\x18\x04 \x03(\v2\x17.google.protobuf.StructR\rcustomMetrics\x12>\n" +
	"\bbehavior\x18\x05 \x01(\v2\".charts.values.v1.PagesHpaBehaviorR\bbehavior:\x04\x88\xb5\x18\x01\"f\n" +
	"\vPagesHpaCpu\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x120\n" +
	"\x14target_average_value\x18\x02 \x01(\tR\x12targetAverageValue:\x04\x88\xb5\x18\x01\"\\\n" +
	"\x10PagesHpaBehavior\x12B\n" +
	"\n" +
	"scale_down\x18\x01 \x01(\v2#.charts.values.v1.PagesHpaScaleDownR\tscaleDown:\x04\x88\xb5\x18\x01\"[\n" +
	"\x11PagesHpaScaleDown\x12@\n" +
	"\x1cstabilization_window_seconds\x18\x01 \x01(\rR\x1astabilizationWindowSeconds:\x04\x88\xb5\x18\x01\"\x7f\n" +
	"\tPagesKeda\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10polling_interval\x18\x02 \x01(\rR\x0fpollingInterval\x12'\n" +
	"\x0fcooldown_period\x18\x03 \x01(\rR\x0ecooldownPeriod:\x04\x88\xb5\x18\x01\"\xfa\x01\n" +
	"\x12PagesNetworkPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12B\n" +
	"\x06egress\x18\x02 \x01(\v2*.charts.values.v1.PagesNetworkPolicyEgressR\x06egress\x12E\n" +
	"\aingress\x18\x03 \x01(\v2+.charts.values.v1.PagesNetworkPolicyIngressR\aingress\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"i\n" +
	"\x18PagesNetworkPolicyEgress\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01\"j\n" +
	"\x19PagesNetworkPolicyIngress\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01\"\xc5\x01\n" +
	"\n" +
	"PagesImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12C\n" +
	"\vpull_policy\x18\x03 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x04 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets:\x04\x88\xb5\x18\x01\"\x99\x04\n" +
	"\fPagesService\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x120\n" +
	"\rexternal_port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\fexternalPort\x120\n" +
	"\rinternal_port\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\finternalPort\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations\x12R\n" +
	"\x0ecustom_domains\x18\x05 \x01(\v2+.charts.values.v1.PagesServiceCustomDomainsR\rcustomDomains\x12?\n" +
	"\ametrics\x18\x06 \x01(\v2%.charts.values.v1.PagesServiceMetricsR\ametrics\x12?\n" +
	"\aprimary\x18\a \x01(\v2%.charts.values.v1.PagesServicePrimaryR\aprimary\x12)\n" +
	"\x10session_affinity\x18\b \x01(\tR\x0fsessionAffinity\x12O\n" +
	"\x17session_affinity_config\x18\t \x01(\v2\x17.google.protobuf.StructR\x15sessionAffinityConfig:\x04\x88\xb5\x18\x01\"\xe3\x01\n" +
	"\x19PagesServiceCustomDomains\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12;\n" +
	"\x13internal_https_port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x11internalHttpsPort\x124\n" +
	"\tnode_port\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bnodePort\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"V\n" +
	"\x13PagesServiceMetrics\x129\n" +
	"\vannotations\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"V\n" +
	"\x13PagesServicePrimary\x129\n" +
	"\vannotations\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"\xce\x01\n" +
	"\tPagesInit\x12-\n" +
	"\x05image\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05image\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tresources\x12U\n" +
	"\x1acontainer_security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext:\x04\x88\xb5\x18\x01\"\x9c\x01\n" +
	"\x0fPagesDeployment\x123\n" +
	"\bstrategy\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bstrategy\x12N\n" +
	"\x0freadiness_probe\x18\x02 \x01(\v2%.charts.values.v1.PagesReadinessProbeR\x0ereadinessProbe:\x04\x88\xb5\x18\x01\"\xf9\x01\n" +
	"\x13PagesReadinessProbe\x122\n" +
	"\x15initial_delay_seconds\x18\x01 \x01(\rR\x13initialDelaySeconds\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\rR\rperiodSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\x12+\n" +
	"\x11success_threshold\x18\x04 \x01(\rR\x10successThreshold\x12+\n" +
	"\x11failure_threshold\x18\x05 \x01(\rR\x10failureThreshold:\x04\x88\xb5\x18\x01\"\xe4\x01\n" +
	"\fPagesIngress\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x129\n" +
	"\vannotations\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vannotations\x123\n" +
	"\x15configure_certmanager\x18\x03 \x01(\bR\x14configureCertmanager\x12)\n" +
	"\x03tls\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x03tls\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path:\x04\x88\xb5\x18\x01\"\xc9\x02\n" +
	"\x11PagesGatewayRoute\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fsection_name\x18\x02 \x01(\tR\vsectionName\x12!\n" +
	"\fgateway_name\x18\x03 \x01(\tR\vgatewayName\x12+\n" +
	"\x11gateway_namespace\x18\x04 \x01(\tR\x10gatewayNamespace\x129\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructR\vannotations\x123\n" +
	"\btimeouts\x18\x06 \x01(\v2\x17.google.protobuf.StructR\btimeouts\x121\n" +
	"\afilters\x18\a \x03(\v2\x17.google.protobuf.StructR\afilters:\x04\x88\xb5\x18\x01\"D\n" +
	"\vPagesCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01\"a\n" +
	"\vPagesSentry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment:\x04\x88\xb5\x18\x01\"R\n" +
	"\bPagesTls\x12\x1f\n" +
	"\vmin_version\x18\x01 \x01(\tR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\x02 \x01(\tR\n" +
	"maxVersion:\x04\x88\xb5\x18\x01\"\xb0\x02\n" +
	"\fPagesMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x123\n" +
	"\x03tls\x18\x04 \x01(\v2!.charts.values.v1.PagesMetricsTlsR\x03tls\x12U\n" +
	"\x0fservice_monitor\x18\x05 \x01(\v2,.charts.values.v1.PagesMetricsServiceMonitorR\x0eserviceMonitor\x12?\n" +
	"\vannotations\x18\x06 \x01(\v2\x17.google.protobuf.StructB\x04\x98\xb5\x18\x05R\vannotations:\x04\x88\xb5\x18\x01\"R\n" +
	"\x0fPagesMetricsTls\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName:\x04\x88\xb5\x18\x01\"\xc4\x01\n" +
	"\x1aPagesMetricsServiceMonitor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x11additional_labels\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10additionalLabels\x12@\n" +
	"\x0fendpoint_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eendpointConfig:\x04\x88\xb5\x18\x01\"\x88\x01\n" +
	"\x13PagesServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x129\n" +
	"\vannotations\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_gitlab_pages_proto_rawDescOnce sync.Once
	file_charts_values_v1_gitlab_pages_proto_rawDescData []byte
)

func file_charts_values_v1_gitlab_pages_proto_rawDescGZIP() []byte {
	file_charts_values_v1_gitlab_pages_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_gitlab_pages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_pages_proto_rawDesc), len(file_charts_values_v1_gitlab_pages_proto_rawDesc)))
	})
	return file_charts_values_v1_gitlab_pages_proto_rawDescData
}

var file_charts_values_v1_gitlab_pages_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_charts_values_v1_gitlab_pages_proto_goTypes = []any{
	(*PagesValues)(nil),                // 0: charts.values.v1.PagesValues
	(*PagesHpa)(nil),                   // 1: charts.values.v1.PagesHpa
	(*PagesHpaCpu)(nil),                // 2: charts.values.v1.PagesHpaCpu
	(*PagesHpaBehavior)(nil),           // 3: charts.values.v1.PagesHpaBehavior
	(*PagesHpaScaleDown)(nil),          // 4: charts.values.v1.PagesHpaScaleDown
	(*PagesKeda)(nil),                  // 5: charts.values.v1.PagesKeda
	(*PagesNetworkPolicy)(nil),         // 6: charts.values.v1.PagesNetworkPolicy
	(*PagesNetworkPolicyEgress)(nil),   // 7: charts.values.v1.PagesNetworkPolicyEgress
	(*PagesNetworkPolicyIngress)(nil),  // 8: charts.values.v1.PagesNetworkPolicyIngress
	(*PagesImage)(nil),                 // 9: charts.values.v1.PagesImage
	(*PagesService)(nil),               // 10: charts.values.v1.PagesService
	(*PagesServiceCustomDomains)(nil),  // 11: charts.values.v1.PagesServiceCustomDomains
	(*PagesServiceMetrics)(nil),        // 12: charts.values.v1.PagesServiceMetrics
	(*PagesServicePrimary)(nil),        // 13: charts.values.v1.PagesServicePrimary
	(*PagesInit)(nil),                  // 14: charts.values.v1.PagesInit
	(*PagesDeployment)(nil),            // 15: charts.values.v1.PagesDeployment
	(*PagesReadinessProbe)(nil),        // 16: charts.values.v1.PagesReadinessProbe
	(*PagesIngress)(nil),               // 17: charts.values.v1.PagesIngress
	(*PagesGatewayRoute)(nil),          // 18: charts.values.v1.PagesGatewayRoute
	(*PagesCommon)(nil),                // 19: charts.values.v1.PagesCommon
	(*PagesSentry)(nil),                // 20: charts.values.v1.PagesSentry
	(*PagesTls)(nil),                   // 21: charts.values.v1.PagesTls
	(*PagesMetrics)(nil),               // 22: charts.values.v1.PagesMetrics
	(*PagesMetricsTls)(nil),            // 23: charts.values.v1.PagesMetricsTls
	(*PagesMetricsServiceMonitor)(nil), // 24: charts.values.v1.PagesMetricsServiceMonitor
	(*PagesServiceAccount)(nil),        // 25: charts.values.v1.PagesServiceAccount
	(*GlobalConfig)(nil),               // 26: charts.values.v1.GlobalConfig
	(*structpb.Struct)(nil),            // 27: google.protobuf.Struct
}
var file_charts_values_v1_gitlab_pages_proto_depIdxs = []int32{
	26, // 0: charts.values.v1.PagesValues.global:type_name -> charts.values.v1.GlobalConfig
	1,  // 1: charts.values.v1.PagesValues.hpa:type_name -> charts.values.v1.PagesHpa
	5,  // 2: charts.values.v1.PagesValues.keda:type_name -> charts.values.v1.PagesKeda
	6,  // 3: charts.values.v1.PagesValues.networkpolicy:type_name -> charts.values.v1.PagesNetworkPolicy
	9,  // 4: charts.values.v1.PagesValues.image:type_name -> charts.values.v1.PagesImage
	10, // 5: charts.values.v1.PagesValues.service:type_name -> charts.values.v1.PagesService
	14, // 6: charts.values.v1.PagesValues.init:type_name -> charts.values.v1.PagesInit
	15, // 7: charts.values.v1.PagesValues.deployment:type_name -> charts.values.v1.PagesDeployment
	17, // 8: charts.values.v1.PagesValues.ingress:type_name -> charts.values.v1.PagesIngress
	18, // 9: charts.values.v1.PagesValues.gateway_route:type_name -> charts.values.v1.PagesGatewayRoute
	27, // 10: charts.values.v1.PagesValues.tolerations:type_name -> google.protobuf.Struct
	27, // 11: charts.values.v1.PagesValues.annotations:type_name -> google.protobuf.Struct
	27, // 12: charts.values.v1.PagesValues.pod_labels:type_name -> google.protobuf.Struct
	19, // 13: charts.values.v1.PagesValues.common:type_name -> charts.values.v1.PagesCommon
	27, // 14: charts.values.v1.PagesValues.service_labels:type_name -> google.protobuf.Struct
	27, // 15: charts.values.v1.PagesValues.extra_env:type_name -> google.protobuf.Struct
	27, // 16: charts.values.v1.PagesValues.resources:type_name -> google.protobuf.Struct
	27, // 17: charts.values.v1.PagesValues.security_context:type_name -> google.protobuf.Struct
	27, // 18: charts.values.v1.PagesValues.container_security_context:type_name -> google.protobuf.Struct
	25, // 19: charts.values.v1.PagesValues.service_account:type_name -> charts.values.v1.PagesServiceAccount
	20, // 20: charts.values.v1.PagesValues.sentry:type_name -> charts.values.v1.PagesSentry
	21, // 21: charts.values.v1.PagesValues.tls:type_name -> charts.values.v1.PagesTls
	22, // 22: charts.values.v1.PagesValues.metrics:type_name -> charts.values.v1.PagesMetrics
	27, // 23: charts.values.v1.PagesValues.workhorse:type_name -> google.protobuf.Struct
	27, // 24: charts.values.v1.PagesValues.affinity:type_name -> google.protobuf.Struct
	27, // 25: charts.values.v1.PagesValues.topology_spread_constraints:type_name -> google.protobuf.Struct
	2,  // 26: charts.values.v1.PagesHpa.cpu:type_name -> charts.values.v1.PagesHpaCpu
	27, // 27: charts.values.v1.PagesHpa.custom_metrics:type_name -> google.protobuf.Struct
	3,  // 28: charts.values.v1.PagesHpa.behavior:type_name -> charts.values.v1.PagesHpaBehavior
	4,  // 29: charts.values.v1.PagesHpaBehavior.scale_down:type_name -> charts.values.v1.PagesHpaScaleDown
	7,  // 30: charts.values.v1.PagesNetworkPolicy.egress:type_name -> charts.values.v1.PagesNetworkPolicyEgress
	8,  // 31: charts.values.v1.PagesNetworkPolicy.ingress:type_name -> charts.values.v1.PagesNetworkPolicyIngress
	27, // 32: charts.values.v1.PagesNetworkPolicy.annotations:type_name -> google.protobuf.Struct
	27, // 33: charts.values.v1.PagesNetworkPolicyEgress.rules:type_name -> google.protobuf.Struct
	27, // 34: charts.values.v1.PagesNetworkPolicyIngress.rules:type_name -> google.protobuf.Struct
	27, // 35: charts.values.v1.PagesImage.pull_secrets:type_name -> google.protobuf.Struct
	27, // 36: charts.values.v1.PagesService.annotations:type_name -> google.protobuf.Struct
	11, // 37: charts.values.v1.PagesService.custom_domains:type_name -> charts.values.v1.PagesServiceCustomDomains
	12, // 38: charts.values.v1.PagesService.metrics:type_name -> charts.values.v1.PagesServiceMetrics
	13, // 39: charts.values.v1.PagesService.primary:type_name -> charts.values.v1.PagesServicePrimary
	27, // 40: charts.values.v1.PagesService.session_affinity_config:type_name -> google.protobuf.Struct
	27, // 41: charts.values.v1.PagesServiceCustomDomains.node_port:type_name -> google.protobuf.Struct
	27, // 42: charts.values.v1.PagesServiceCustomDomains.annotations:type_name -> google.protobuf.Struct
	27, // 43: charts.values.v1.PagesServiceMetrics.annotations:type_name -> google.protobuf.Struct
	27, // 44: charts.values.v1.PagesServicePrimary.annotations:type_name -> google.protobuf.Struct
	27, // 45: charts.values.v1.PagesInit.image:type_name -> google.protobuf.Struct
	27, // 46: charts.values.v1.PagesInit.resources:type_name -> google.protobuf.Struct
	27, // 47: charts.values.v1.PagesInit.container_security_context:type_name -> google.protobuf.Struct
	27, // 48: charts.values.v1.PagesDeployment.strategy:type_name -> google.protobuf.Struct
	16, // 49: charts.values.v1.PagesDeployment.readiness_probe:type_name -> charts.values.v1.PagesReadinessProbe
	27, // 50: charts.values.v1.PagesIngress.annotations:type_name -> google.protobuf.Struct
	27, // 51: charts.values.v1.PagesIngress.tls:type_name -> google.protobuf.Struct
	27, // 52: charts.values.v1.PagesGatewayRoute.annotations:type_name -> google.protobuf.Struct
	27, // 53: charts.values.v1.PagesGatewayRoute.timeouts:type_name -> google.protobuf.Struct
	27, // 54: charts.values.v1.PagesGatewayRoute.filters:type_name -> google.protobuf.Struct
	27, // 55: charts.values.v1.PagesCommon.labels:type_name -> google.protobuf.Struct
	23, // 56: charts.values.v1.PagesMetrics.tls:type_name -> charts.values.v1.PagesMetricsTls
	24, // 57: charts.values.v1.PagesMetrics.service_monitor:type_name -> charts.values.v1.PagesMetricsServiceMonitor
	27, // 58: charts.values.v1.PagesMetrics.annotations:type_name -> google.protobuf.Struct
	27, // 59: charts.values.v1.PagesMetricsServiceMonitor.additional_labels:type_name -> google.protobuf.Struct
	27, // 60: charts.values.v1.PagesMetricsServiceMonitor.endpoint_config:type_name -> google.protobuf.Struct
	27, // 61: charts.values.v1.PagesServiceAccount.annotations:type_name -> google.protobuf.Struct
	62, // [62:62] is the sub-list for method output_type
	62, // [62:62] is the sub-list for method input_type
	62, // [62:62] is the sub-list for extension type_name
	62, // [62:62] is the sub-list for extension extendee
	0,  // [0:62] is the sub-list for field type_name
}

func init() { file_charts_values_v1_gitlab_pages_proto_init() }
func file_charts_values_v1_gitlab_pages_proto_init() {
	if File_charts_values_v1_gitlab_pages_proto != nil {
		return
	}
	file_charts_values_v1_global_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_gitlab_pages_proto_rawDesc), len(file_charts_values_v1_gitlab_pages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_gitlab_pages_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_gitlab_pages_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_gitlab_pages_proto_msgTypes,
	}.Build()
	File_charts_values_v1_gitlab_pages_proto = out.File
	file_charts_values_v1_gitlab_pages_proto_goTypes = nil
	file_charts_values_v1_gitlab_pages_proto_depIdxs = nil
}
