// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/mailroom.proto

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MailroomValues is the top-level schema for the mailroom sub-chart values.
type MailroomValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image configuration.
	Image *MailroomImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Whether the mailroom sub-chart is enabled.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Init container configuration.
	Init *MailroomInit `protobuf:"bytes,3,opt,name=init,proto3" json:"init,omitempty"`
	// Annotations applied to resources.
	Annotations *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Tolerations for pod scheduling.
	Tolerations []*structpb.Struct `protobuf:"bytes,5,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// Labels applied to pods.
	PodLabels *structpb.Struct `protobuf:"bytes,6,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Common chart settings.
	Common *MailroomCommon `protobuf:"bytes,7,opt,name=common,proto3" json:"common,omitempty"`
	// Workhorse connection configuration.
	Workhorse *MailroomWorkhorse `protobuf:"bytes,8,opt,name=workhorse,proto3" json:"workhorse,omitempty"`
	// Global settings consumed by the sub-chart.
	Global *GlobalConfig `protobuf:"bytes,9,opt,name=global,proto3" json:"global,omitempty"`
	// Horizontal Pod Autoscaler configuration.
	Hpa *MailroomHpa `protobuf:"bytes,10,opt,name=hpa,proto3" json:"hpa,omitempty"`
	// KEDA autoscaling configuration.
	Keda *MailroomKeda `protobuf:"bytes,11,opt,name=keda,proto3" json:"keda,omitempty"`
	// Network policy configuration.
	Networkpolicy *MailroomNetworkpolicy `protobuf:"bytes,12,opt,name=networkpolicy,proto3" json:"networkpolicy,omitempty"`
	// Redis connection configuration.
	Redis *MailroomRedis `protobuf:"bytes,13,opt,name=redis,proto3" json:"redis,omitempty"`
	// Pod resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	// Pod-level security context.
	SecurityContext *structpb.Struct `protobuf:"bytes,15,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	// Container-level security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,16,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// ServiceAccount configuration.
	ServiceAccount *MailroomServiceAccount `protobuf:"bytes,17,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Deployment settings.
	Deployment *MailroomDeployment `protobuf:"bytes,18,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Pod affinity/anti-affinity rules.
	Affinity *structpb.Struct `protobuf:"bytes,19,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Priority class assigned to pods.
	PriorityClassName string `protobuf:"bytes,20,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Topology spread constraints for pod scheduling.
	TopologySpreadConstraints []*structpb.Struct `protobuf:"bytes,21,rep,name=topology_spread_constraints,json=topologySpreadConstraints,proto3" json:"topology_spread_constraints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MailroomValues) Reset() {
	*x = MailroomValues{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomValues) ProtoMessage() {}

func (x *MailroomValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomValues.ProtoReflect.Descriptor instead.
func (*MailroomValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{0}
}

func (x *MailroomValues) GetImage() *MailroomImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *MailroomValues) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomValues) GetInit() *MailroomInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *MailroomValues) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *MailroomValues) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *MailroomValues) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *MailroomValues) GetCommon() *MailroomCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *MailroomValues) GetWorkhorse() *MailroomWorkhorse {
	if x != nil {
		return x.Workhorse
	}
	return nil
}

func (x *MailroomValues) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *MailroomValues) GetHpa() *MailroomHpa {
	if x != nil {
		return x.Hpa
	}
	return nil
}

func (x *MailroomValues) GetKeda() *MailroomKeda {
	if x != nil {
		return x.Keda
	}
	return nil
}

func (x *MailroomValues) GetNetworkpolicy() *MailroomNetworkpolicy {
	if x != nil {
		return x.Networkpolicy
	}
	return nil
}

func (x *MailroomValues) GetRedis() *MailroomRedis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *MailroomValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *MailroomValues) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *MailroomValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *MailroomValues) GetServiceAccount() *MailroomServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *MailroomValues) GetDeployment() *MailroomDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *MailroomValues) GetAffinity() *structpb.Struct {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *MailroomValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *MailroomValues) GetTopologySpreadConstraints() []*structpb.Struct {
	if x != nil {
		return x.TopologySpreadConstraints
	}
	return nil
}

// MailroomImage configures the container image.
type MailroomImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image registry host.
	Registry string `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	// Container image repository.
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	// Container image tag.
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// Image pull policy.
	PullPolicy string `protobuf:"bytes,4,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	// Image pull secrets.
	PullSecrets   []*structpb.Struct `protobuf:"bytes,5,rep,name=pull_secrets,json=pullSecrets,proto3" json:"pull_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomImage) Reset() {
	*x = MailroomImage{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomImage) ProtoMessage() {}

func (x *MailroomImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomImage.ProtoReflect.Descriptor instead.
func (*MailroomImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{1}
}

func (x *MailroomImage) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *MailroomImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *MailroomImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MailroomImage) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

func (x *MailroomImage) GetPullSecrets() []*structpb.Struct {
	if x != nil {
		return x.PullSecrets
	}
	return nil
}

// MailroomInit configures the init container.
type MailroomInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image configuration.
	Image *MailroomInitImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Init container security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,3,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MailroomInit) Reset() {
	*x = MailroomInit{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomInit) ProtoMessage() {}

func (x *MailroomInit) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomInit.ProtoReflect.Descriptor instead.
func (*MailroomInit) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{2}
}

func (x *MailroomInit) GetImage() *MailroomInitImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *MailroomInit) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *MailroomInit) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

// MailroomInitImage configures the init container image.
type MailroomInitImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image repository.
	Repository string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	// Init container image tag.
	Tag           string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomInitImage) Reset() {
	*x = MailroomInitImage{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomInitImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomInitImage) ProtoMessage() {}

func (x *MailroomInitImage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomInitImage.ProtoReflect.Descriptor instead.
func (*MailroomInitImage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{3}
}

func (x *MailroomInitImage) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *MailroomInitImage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// MailroomSecretRef references a key within a Kubernetes secret.
type MailroomSecretRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Kubernetes secret.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Key within the secret.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomSecretRef) Reset() {
	*x = MailroomSecretRef{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomSecretRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomSecretRef) ProtoMessage() {}

func (x *MailroomSecretRef) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomSecretRef.ProtoReflect.Descriptor instead.
func (*MailroomSecretRef) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{4}
}

func (x *MailroomSecretRef) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MailroomSecretRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// MailroomCommon holds settings shared across chart resources.
type MailroomCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common labels applied to resources.
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomCommon) Reset() {
	*x = MailroomCommon{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomCommon) ProtoMessage() {}

func (x *MailroomCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomCommon.ProtoReflect.Descriptor instead.
func (*MailroomCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{5}
}

func (x *MailroomCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

// MailroomWorkhorse configures the Workhorse connection.
type MailroomWorkhorse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection scheme (http or https).
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Workhorse host.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// Workhorse service name.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Workhorse port.
	Port          uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomWorkhorse) Reset() {
	*x = MailroomWorkhorse{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomWorkhorse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomWorkhorse) ProtoMessage() {}

func (x *MailroomWorkhorse) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomWorkhorse.ProtoReflect.Descriptor instead.
func (*MailroomWorkhorse) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{6}
}

func (x *MailroomWorkhorse) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *MailroomWorkhorse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MailroomWorkhorse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MailroomWorkhorse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// MailroomEmailConfig configures an IMAP-based email integration.
type MailroomEmailConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the email integration is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Email address to poll.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// IMAP server host.
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// IMAP server port.
	Port uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// Whether to use SSL.
	Ssl bool `protobuf:"varint,5,opt,name=ssl,proto3" json:"ssl,omitempty"`
	// Whether to use STARTTLS.
	StartTls bool `protobuf:"varint,6,opt,name=start_tls,json=startTls,proto3" json:"start_tls,omitempty"`
	// IMAP username.
	User string `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	// Reference to the IMAP password secret.
	Password *MailroomSecretRef `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	// Whether to delete mail after delivery.
	DeleteAfterDelivery bool `protobuf:"varint,9,opt,name=delete_after_delivery,json=deleteAfterDelivery,proto3" json:"delete_after_delivery,omitempty"`
	// Whether to expunge deleted mail.
	ExpungeDeleted bool `protobuf:"varint,10,opt,name=expunge_deleted,json=expungeDeleted,proto3" json:"expunge_deleted,omitempty"`
	// Logger configuration.
	Logger *MailroomEmailLogger `protobuf:"bytes,11,opt,name=logger,proto3" json:"logger,omitempty"`
	// Mailbox to poll.
	Mailbox string `protobuf:"bytes,12,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	// Idle timeout in seconds.
	IdleTimeout uint32 `protobuf:"varint,13,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	// Method used to read the inbox.
	InboxMethod string `protobuf:"bytes,14,opt,name=inbox_method,json=inboxMethod,proto3" json:"inbox_method,omitempty"`
	// Reference to the OAuth client secret.
	ClientSecret *MailroomSecretRef `protobuf:"bytes,15,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Poll interval in seconds.
	PollInterval uint32 `protobuf:"varint,16,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	// Delivery method.
	DeliveryMethod string `protobuf:"bytes,17,opt,name=delivery_method,json=deliveryMethod,proto3" json:"delivery_method,omitempty"`
	// Reference to the auth token secret.
	AuthToken     *MailroomSecretRef `protobuf:"bytes,18,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomEmailConfig) Reset() {
	*x = MailroomEmailConfig{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomEmailConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomEmailConfig) ProtoMessage() {}

func (x *MailroomEmailConfig) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomEmailConfig.ProtoReflect.Descriptor instead.
func (*MailroomEmailConfig) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{7}
}

func (x *MailroomEmailConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomEmailConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MailroomEmailConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MailroomEmailConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MailroomEmailConfig) GetSsl() bool {
	if x != nil {
		return x.Ssl
	}
	return false
}

func (x *MailroomEmailConfig) GetStartTls() bool {
	if x != nil {
		return x.StartTls
	}
	return false
}

func (x *MailroomEmailConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MailroomEmailConfig) GetPassword() *MailroomSecretRef {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *MailroomEmailConfig) GetDeleteAfterDelivery() bool {
	if x != nil {
		return x.DeleteAfterDelivery
	}
	return false
}

func (x *MailroomEmailConfig) GetExpungeDeleted() bool {
	if x != nil {
		return x.ExpungeDeleted
	}
	return false
}

func (x *MailroomEmailConfig) GetLogger() *MailroomEmailLogger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *MailroomEmailConfig) GetMailbox() string {
	if x != nil {
		return x.Mailbox
	}
	return ""
}

func (x *MailroomEmailConfig) GetIdleTimeout() uint32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

func (x *MailroomEmailConfig) GetInboxMethod() string {
	if x != nil {
		return x.InboxMethod
	}
	return ""
}

func (x *MailroomEmailConfig) GetClientSecret() *MailroomSecretRef {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

func (x *MailroomEmailConfig) GetPollInterval() uint32 {
	if x != nil {
		return x.PollInterval
	}
	return 0
}

func (x *MailroomEmailConfig) GetDeliveryMethod() string {
	if x != nil {
		return x.DeliveryMethod
	}
	return ""
}

func (x *MailroomEmailConfig) GetAuthToken() *MailroomSecretRef {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

// MailroomEmailLogger configures email integration logging.
type MailroomEmailLogger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path the logger writes to.
	LogPath       string `protobuf:"bytes,1,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomEmailLogger) Reset() {
	*x = MailroomEmailLogger{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomEmailLogger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomEmailLogger) ProtoMessage() {}

func (x *MailroomEmailLogger) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomEmailLogger.ProtoReflect.Descriptor instead.
func (*MailroomEmailLogger) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{8}
}

func (x *MailroomEmailLogger) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

// MailroomHpa configures the Horizontal Pod Autoscaler.
type MailroomHpa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum number of replicas.
	MinReplicas uint32 `protobuf:"varint,1,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// Maximum number of replicas.
	MaxReplicas uint32 `protobuf:"varint,2,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// CPU-based scaling target.
	Cpu *MailroomHpaMetric `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Custom metrics overriding the HPA metrics definition.
	CustomMetrics []*structpb.Struct `protobuf:"bytes,4,rep,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty"`
	// Scaling behavior configuration.
	Behavior      *MailroomHpaBehavior `protobuf:"bytes,5,opt,name=behavior,proto3" json:"behavior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomHpa) Reset() {
	*x = MailroomHpa{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomHpa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomHpa) ProtoMessage() {}

func (x *MailroomHpa) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomHpa.ProtoReflect.Descriptor instead.
func (*MailroomHpa) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{9}
}

func (x *MailroomHpa) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *MailroomHpa) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *MailroomHpa) GetCpu() *MailroomHpaMetric {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MailroomHpa) GetCustomMetrics() []*structpb.Struct {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

func (x *MailroomHpa) GetBehavior() *MailroomHpaBehavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

// MailroomHpaMetric configures a single autoscaling metric target.
type MailroomHpaMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target type (Utilization or AverageValue).
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Target average utilization percentage.
	TargetAverageUtilization uint32 `protobuf:"varint,2,opt,name=target_average_utilization,json=targetAverageUtilization,proto3" json:"target_average_utilization,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MailroomHpaMetric) Reset() {
	*x = MailroomHpaMetric{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomHpaMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomHpaMetric) ProtoMessage() {}

func (x *MailroomHpaMetric) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomHpaMetric.ProtoReflect.Descriptor instead.
func (*MailroomHpaMetric) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{10}
}

func (x *MailroomHpaMetric) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *MailroomHpaMetric) GetTargetAverageUtilization() uint32 {
	if x != nil {
		return x.TargetAverageUtilization
	}
	return 0
}

// MailroomHpaBehavior configures autoscaling behavior.
type MailroomHpaBehavior struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scale-down behavior.
	ScaleDown     *MailroomHpaScaleDown `protobuf:"bytes,1,opt,name=scale_down,json=scaleDown,proto3" json:"scale_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomHpaBehavior) Reset() {
	*x = MailroomHpaBehavior{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomHpaBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomHpaBehavior) ProtoMessage() {}

func (x *MailroomHpaBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomHpaBehavior.ProtoReflect.Descriptor instead.
func (*MailroomHpaBehavior) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{11}
}

func (x *MailroomHpaBehavior) GetScaleDown() *MailroomHpaScaleDown {
	if x != nil {
		return x.ScaleDown
	}
	return nil
}

// MailroomHpaScaleDown configures scale-down behavior.
type MailroomHpaScaleDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stabilization window in seconds.
	StabilizationWindowSeconds uint32 `protobuf:"varint,1,opt,name=stabilization_window_seconds,json=stabilizationWindowSeconds,proto3" json:"stabilization_window_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *MailroomHpaScaleDown) Reset() {
	*x = MailroomHpaScaleDown{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomHpaScaleDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomHpaScaleDown) ProtoMessage() {}

func (x *MailroomHpaScaleDown) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomHpaScaleDown.ProtoReflect.Descriptor instead.
func (*MailroomHpaScaleDown) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{12}
}

func (x *MailroomHpaScaleDown) GetStabilizationWindowSeconds() uint32 {
	if x != nil {
		return x.StabilizationWindowSeconds
	}
	return 0
}

// MailroomKeda configures KEDA-based autoscaling.
type MailroomKeda struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether KEDA autoscaling is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Polling interval in seconds.
	PollingInterval uint32 `protobuf:"varint,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	// Cooldown period in seconds.
	CooldownPeriod uint32 `protobuf:"varint,3,opt,name=cooldown_period,json=cooldownPeriod,proto3" json:"cooldown_period,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MailroomKeda) Reset() {
	*x = MailroomKeda{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomKeda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomKeda) ProtoMessage() {}

func (x *MailroomKeda) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomKeda.ProtoReflect.Descriptor instead.
func (*MailroomKeda) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{13}
}

func (x *MailroomKeda) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomKeda) GetPollingInterval() uint32 {
	if x != nil {
		return x.PollingInterval
	}
	return 0
}

func (x *MailroomKeda) GetCooldownPeriod() uint32 {
	if x != nil {
		return x.CooldownPeriod
	}
	return 0
}

// MailroomNetworkpolicy configures the NetworkPolicy.
type MailroomNetworkpolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the NetworkPolicy is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules configuration.
	Egress *MailroomNetworkpolicyRule `protobuf:"bytes,2,opt,name=egress,proto3" json:"egress,omitempty"`
	// Ingress rules configuration.
	Ingress *MailroomNetworkpolicyRule `protobuf:"bytes,3,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// Annotations applied to the NetworkPolicy.
	Annotations   *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomNetworkpolicy) Reset() {
	*x = MailroomNetworkpolicy{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomNetworkpolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomNetworkpolicy) ProtoMessage() {}

func (x *MailroomNetworkpolicy) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomNetworkpolicy.ProtoReflect.Descriptor instead.
func (*MailroomNetworkpolicy) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{14}
}

func (x *MailroomNetworkpolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomNetworkpolicy) GetEgress() *MailroomNetworkpolicyRule {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *MailroomNetworkpolicy) GetIngress() *MailroomNetworkpolicyRule {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *MailroomNetworkpolicy) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// MailroomNetworkpolicyRule configures a set of network policy rules.
type MailroomNetworkpolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this rule set is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Network policy rules.
	Rules         []*structpb.Struct `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomNetworkpolicyRule) Reset() {
	*x = MailroomNetworkpolicyRule{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomNetworkpolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomNetworkpolicyRule) ProtoMessage() {}

func (x *MailroomNetworkpolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomNetworkpolicyRule.ProtoReflect.Descriptor instead.
func (*MailroomNetworkpolicyRule) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{15}
}

func (x *MailroomNetworkpolicyRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomNetworkpolicyRule) GetRules() []*structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

// MailroomRedis configures the Redis connection.
type MailroomRedis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis authentication configuration.
	Auth          *structpb.Struct `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomRedis) Reset() {
	*x = MailroomRedis{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomRedis) ProtoMessage() {}

func (x *MailroomRedis) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomRedis.ProtoReflect.Descriptor instead.
func (*MailroomRedis) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{16}
}

func (x *MailroomRedis) GetAuth() *structpb.Struct {
	if x != nil {
		return x.Auth
	}
	return nil
}

// MailroomServiceAccount configures the ServiceAccount.
type MailroomServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the sub-chart uses a ServiceAccount.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to create the ServiceAccount.
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Annotations applied to the ServiceAccount.
	Annotations   *structpb.Struct `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomServiceAccount) Reset() {
	*x = MailroomServiceAccount{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomServiceAccount) ProtoMessage() {}

func (x *MailroomServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomServiceAccount.ProtoReflect.Descriptor instead.
func (*MailroomServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{17}
}

func (x *MailroomServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MailroomServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *MailroomServiceAccount) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// MailroomDeployment configures the Deployment.
type MailroomDeployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment update strategy.
	Strategy      *structpb.Struct `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailroomDeployment) Reset() {
	*x = MailroomDeployment{}
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailroomDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailroomDeployment) ProtoMessage() {}

func (x *MailroomDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_mailroom_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailroomDeployment.ProtoReflect.Descriptor instead.
func (*MailroomDeployment) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_mailroom_proto_rawDescGZIP(), []int{18}
}

func (x *MailroomDeployment) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

var File_charts_values_v1_mailroom_proto protoreflect.FileDescriptor

const file_charts_values_v1_mailroom_proto_rawDesc = "" +
	"\n" +
	"\x1fcharts/values/v1/mailroom.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1dcharts/values/v1/global.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x92\n" +
	"\n" +
	"\x0eMailroomValues\x125\n" +
	"\x05image\x18\x01 \x01(\v2\x1f.charts.values.v1.MailroomImageR\x05image\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x122\n" +
	"\x04init\x18\x03 \x01(\v2\x1e.charts.values.v1.MailroomInitR\x04init\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations\x129\n" +
	"\vtolerations\x18\x05 \x03(\v2\x17.google.protobuf.StructR\vtolerations\x126\n" +
	"\n" +
	"pod_labels\x18\x06 \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x128\n" +
	"\x06common\x18\a \x01(\v2 .charts.values.v1.MailroomCommonR\x06common\x12A\n" +
	"\tworkhorse\x18\b \x01(\v2#.charts.values.v1.MailroomWorkhorseR\tworkhorse\x126\n" +
	"\x06global\x18\t \x01(\v2\x1e.charts.values.v1.GlobalConfigR\x06global\x12/\n" +
	"\x03hpa\x18\n" +
	" \x01(\v2\x1d.charts.values.v1.MailroomHpaR\x03hpa\x122\n" +
	"\x04keda\x18\v \x01(\v2\x1e.charts.values.v1.MailroomKedaR\x04keda\x12M\n" +
	"\rnetworkpolicy\x18\f \x01(\v2'.charts.values.v1.MailroomNetworkpolicyR\rnetworkpolicy\x125\n" +
	"\x05redis\x18\r \x01(\v2\x1f.charts.values.v1.MailroomRedisR\x05redis\x125\n" +
	"\tresources\x18\x0e \x01(\v2\x17.google.protobuf.StructR\tresources\x12B\n" +
	"\x10security_context\x18\x0f \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\x10 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12Q\n" +
	"\x0fservice_account\x18\x11 \x01(\v2(.charts.values.v1.MailroomServiceAccountR\x0eserviceAccount\x12D\n" +
	"\n" +
	"deployment\x18\x12 \x01(\v2$.charts.values.v1.MailroomDeploymentR\n" +
	"deployment\x123\n" +
	"\baffinity\x18\x13 \x01(\v2\x17.google.protobuf.StructR\baffinity\x12.\n" +
	"\x13priority_class_name\x18\x14 \x01(\tR\x11priorityClassName\x12W\n" +
	"\x1btopology_spread_constraints\x18\x15 \x03(\v2\x17.google.protobuf.StructR\x19topologySpreadConstraints:\x04\x88\xb5\x18\x01\"\xe4\x01\n" +
	"\rMailroomImage\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12C\n" +
	"\vpull_policy\x18\x04 \x01(\tB\"\xbaH\x1fr\x1dR\x06AlwaysR\x05NeverR\fIfNotPresentR\n" +
	"pullPolicy\x12:\n" +
	"\fpull_secrets\x18\x05 \x03(\v2\x17.google.protobuf.StructR\vpullSecrets:\x04\x88\xb5\x18\x01\"\xdd\x01\n" +
	"\fMailroomInit\x129\n" +
	"\x05image\x18\x01 \x01(\v2#.charts.values.v1.MailroomInitImageR\x05image\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tresources\x12U\n" +
	"\x1acontainer_security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext:\x04\x88\xb5\x18\x01\"K\n" +
	"\x11MailroomInitImage\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag:\x04\x88\xb5\x18\x01\"C\n" +
	"\x11MailroomSecretRef\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key:\x04\x88\xb5\x18\x01\"G\n" +
	"\x0eMailroomCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01\"\x89\x01\n" +
	"\x11MailroomWorkhorse\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\x04port\x18\x04 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port:\x04\x88\xb5\x18\x01\"\xe0\x05\n" +
	"\x13MailroomEmailConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1f\n" +
	"\x04port\x18\x04 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x10\n" +
	"\x03ssl\x18\x05 \x01(\bR\x03ssl\x12\x1b\n" +
	"\tstart_tls\x18\x06 \x01(\bR\bstartTls\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12?\n" +
	"\bpassword\x18\b \x01(\v2#.charts.values.v1.MailroomSecretRefR\bpassword\x122\n" +
	"\x15delete_after_delivery\x18\t \x01(\bR\x13deleteAfterDelivery\x12'\n" +
	"\x0fexpunge_deleted\x18\n" +
	" \x01(\bR\x0eexpungeDeleted\x12=\n" +
	"\x06logger\x18\v \x01(\v2%.charts.values.v1.MailroomEmailLoggerR\x06logger\x12\x18\n" +
	"\amailbox\x18\f \x01(\tR\amailbox\x12!\n" +
	"\fidle_timeout\x18\r \x01(\rR\vidleTimeout\x12!\n" +
	"\finbox_method\x18\x0e \x01(\tR\vinboxMethod\x12H\n" +
	"\rclient_secret\x18\x0f \x01(\v2#.charts.values.v1.MailroomSecretRefR\fclientSecret\x12#\n" +
	"\rpoll_interval\x18\x10 \x01(\rR\fpollInterval\x12'\n" +
	"\x0fdelivery_method\x18\x11 \x01(\tR\x0edeliveryMethod\x12B\n" +
	"\n" +
	"auth_token\x18\x12 \x01(\v2#.charts.values.v1.MailroomSecretRefR\tauthToken:\x04\x88\xb5\x18\x01\"6\n" +
	"\x13MailroomEmailLogger\x12\x19\n" +
	"\blog_path\x18\x01 \x01(\tR\alogPath:\x04\x88\xb5\x18\x01\"\x93\x02\n" +
	"\vMailroomHpa\x12!\n" +
	"\fmin_replicas\x18\x01 \x01(\rR\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x02 \x01(\rR\vmaxReplicas\x125\n" +
	"\x03cpu\x18\x03 \x01(\v2#.charts.values.v1.MailroomHpaMetricR\x03cpu\x12>\n" +
	"\x0ecustom_metrics\x18\x04 \x03(\v2\x17.google.protobuf.StructR\rcustomMetrics\x12A\n" +
	"\bbehavior\x18\x05 \x01(\v2%.charts.values.v1.MailroomHpaBehaviorR\bbehavior:\x04\x88\xb5\x18\x01\"x\n" +
	"\x11MailroomHpaMetric\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12<\n" +
	"\x1atarget_average_utilization\x18\x02 \x01(\rR\x18targetAverageUtilization:\x04\x88\xb5\x18\x01\"b\n" +
	"\x13MailroomHpaBehavior\x12E\n" +
	"\n" +
	"scale_down\x18\x01 \x01(\v2&.charts.values.v1.MailroomHpaScaleDownR\tscaleDown:\x04\x88\xb5\x18\x01\"^\n" +
	"\x14MailroomHpaScaleDown\x12@\n" +
	"\x1cstabilization_window_seconds\x18\x01 \x01(\rR\x1astabilizationWindowSeconds:\x04\x88\xb5\x18\x01\"\x82\x01\n" +
	"\fMailroomKeda\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10polling_interval\x18\x02 \x01(\rR\x0fpollingInterval\x12'\n" +
	"\x0fcooldown_period\x18\x03 \x01(\rR\x0ecooldownPeriod:\x04\x88\xb5\x18\x01\"\xfe\x01\n" +
	"\x15MailroomNetworkpolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12C\n" +
	"\x06egress\x18\x02 \x01(\v2+.charts.values.v1.MailroomNetworkpolicyRuleR\x06egress\x12E\n" +
	"\aingress\x18\x03 \x01(\v2+.charts.values.v1.MailroomNetworkpolicyRuleR\aingress\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"j\n" +
	"\x19MailroomNetworkpolicyRule\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01\"B\n" +
	"\rMailroomRedis\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04auth:\x04\x88\xb5\x18\x01\"\x8b\x01\n" +
	"\x16MailroomServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x129\n" +
	"\vannotations\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"O\n" +
	"\x12MailroomDeployment\x123\n" +
	"\bstrategy\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bstrategy:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_mailroom_proto_rawDescOnce sync.Once
	file_charts_values_v1_mailroom_proto_rawDescData []byte
)

func file_charts_values_v1_mailroom_proto_rawDescGZIP() []byte {
	file_charts_values_v1_mailroom_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_mailroom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_mailroom_proto_rawDesc), len(file_charts_values_v1_mailroom_proto_rawDesc)))
	})
	return file_charts_values_v1_mailroom_proto_rawDescData
}

var file_charts_values_v1_mailroom_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_charts_values_v1_mailroom_proto_goTypes = []any{
	(*MailroomValues)(nil),            // 0: charts.values.v1.MailroomValues
	(*MailroomImage)(nil),             // 1: charts.values.v1.MailroomImage
	(*MailroomInit)(nil),              // 2: charts.values.v1.MailroomInit
	(*MailroomInitImage)(nil),         // 3: charts.values.v1.MailroomInitImage
	(*MailroomSecretRef)(nil),         // 4: charts.values.v1.MailroomSecretRef
	(*MailroomCommon)(nil),            // 5: charts.values.v1.MailroomCommon
	(*MailroomWorkhorse)(nil),         // 6: charts.values.v1.MailroomWorkhorse
	(*MailroomEmailConfig)(nil),       // 7: charts.values.v1.MailroomEmailConfig
	(*MailroomEmailLogger)(nil),       // 8: charts.values.v1.MailroomEmailLogger
	(*MailroomHpa)(nil),               // 9: charts.values.v1.MailroomHpa
	(*MailroomHpaMetric)(nil),         // 10: charts.values.v1.MailroomHpaMetric
	(*MailroomHpaBehavior)(nil),       // 11: charts.values.v1.MailroomHpaBehavior
	(*MailroomHpaScaleDown)(nil),      // 12: charts.values.v1.MailroomHpaScaleDown
	(*MailroomKeda)(nil),              // 13: charts.values.v1.MailroomKeda
	(*MailroomNetworkpolicy)(nil),     // 14: charts.values.v1.MailroomNetworkpolicy
	(*MailroomNetworkpolicyRule)(nil), // 15: charts.values.v1.MailroomNetworkpolicyRule
	(*MailroomRedis)(nil),             // 16: charts.values.v1.MailroomRedis
	(*MailroomServiceAccount)(nil),    // 17: charts.values.v1.MailroomServiceAccount
	(*MailroomDeployment)(nil),        // 18: charts.values.v1.MailroomDeployment
	(*structpb.Struct)(nil),           // 19: google.protobuf.Struct
	(*GlobalConfig)(nil),              // 20: charts.values.v1.GlobalConfig
}
var file_charts_values_v1_mailroom_proto_depIdxs = []int32{
	1,  // 0: charts.values.v1.MailroomValues.image:type_name -> charts.values.v1.MailroomImage
	2,  // 1: charts.values.v1.MailroomValues.init:type_name -> charts.values.v1.MailroomInit
	19, // 2: charts.values.v1.MailroomValues.annotations:type_name -> google.protobuf.Struct
	19, // 3: charts.values.v1.MailroomValues.tolerations:type_name -> google.protobuf.Struct
	19, // 4: charts.values.v1.MailroomValues.pod_labels:type_name -> google.protobuf.Struct
	5,  // 5: charts.values.v1.MailroomValues.common:type_name -> charts.values.v1.MailroomCommon
	6,  // 6: charts.values.v1.MailroomValues.workhorse:type_name -> charts.values.v1.MailroomWorkhorse
	20, // 7: charts.values.v1.MailroomValues.global:type_name -> charts.values.v1.GlobalConfig
	9,  // 8: charts.values.v1.MailroomValues.hpa:type_name -> charts.values.v1.MailroomHpa
	13, // 9: charts.values.v1.MailroomValues.keda:type_name -> charts.values.v1.MailroomKeda
	14, // 10: charts.values.v1.MailroomValues.networkpolicy:type_name -> charts.values.v1.MailroomNetworkpolicy
	16, // 11: charts.values.v1.MailroomValues.redis:type_name -> charts.values.v1.MailroomRedis
	19, // 12: charts.values.v1.MailroomValues.resources:type_name -> google.protobuf.Struct
	19, // 13: charts.values.v1.MailroomValues.security_context:type_name -> google.protobuf.Struct
	19, // 14: charts.values.v1.MailroomValues.container_security_context:type_name -> google.protobuf.Struct
	17, // 15: charts.values.v1.MailroomValues.service_account:type_name -> charts.values.v1.MailroomServiceAccount
	18, // 16: charts.values.v1.MailroomValues.deployment:type_name -> charts.values.v1.MailroomDeployment
	19, // 17: charts.values.v1.MailroomValues.affinity:type_name -> google.protobuf.Struct
	19, // 18: charts.values.v1.MailroomValues.topology_spread_constraints:type_name -> google.protobuf.Struct
	19, // 19: charts.values.v1.MailroomImage.pull_secrets:type_name -> google.protobuf.Struct
	3,  // 20: charts.values.v1.MailroomInit.image:type_name -> charts.values.v1.MailroomInitImage
	19, // 21: charts.values.v1.MailroomInit.resources:type_name -> google.protobuf.Struct
	19, // 22: charts.values.v1.MailroomInit.container_security_context:type_name -> google.protobuf.Struct
	19, // 23: charts.values.v1.MailroomCommon.labels:type_name -> google.protobuf.Struct
	4,  // 24: charts.values.v1.MailroomEmailConfig.password:type_name -> charts.values.v1.MailroomSecretRef
	8,  // 25: charts.values.v1.MailroomEmailConfig.logger:type_name -> charts.values.v1.MailroomEmailLogger
	4,  // 26: charts.values.v1.MailroomEmailConfig.client_secret:type_name -> charts.values.v1.MailroomSecretRef
	4,  // 27: charts.values.v1.MailroomEmailConfig.auth_token:type_name -> charts.values.v1.MailroomSecretRef
	10, // 28: charts.values.v1.MailroomHpa.cpu:type_name -> charts.values.v1.MailroomHpaMetric
	19, // 29: charts.values.v1.MailroomHpa.custom_metrics:type_name -> google.protobuf.Struct
	11, // 30: charts.values.v1.MailroomHpa.behavior:type_name -> charts.values.v1.MailroomHpaBehavior
	12, // 31: charts.values.v1.MailroomHpaBehavior.scale_down:type_name -> charts.values.v1.MailroomHpaScaleDown
	15, // 32: charts.values.v1.MailroomNetworkpolicy.egress:type_name -> charts.values.v1.MailroomNetworkpolicyRule
	15, // 33: charts.values.v1.MailroomNetworkpolicy.ingress:type_name -> charts.values.v1.MailroomNetworkpolicyRule
	19, // 34: charts.values.v1.MailroomNetworkpolicy.annotations:type_name -> google.protobuf.Struct
	19, // 35: charts.values.v1.MailroomNetworkpolicyRule.rules:type_name -> google.protobuf.Struct
	19, // 36: charts.values.v1.MailroomRedis.auth:type_name -> google.protobuf.Struct
	19, // 37: charts.values.v1.MailroomServiceAccount.annotations:type_name -> google.protobuf.Struct
	19, // 38: charts.values.v1.MailroomDeployment.strategy:type_name -> google.protobuf.Struct
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_charts_values_v1_mailroom_proto_init() }
func file_charts_values_v1_mailroom_proto_init() {
	if File_charts_values_v1_mailroom_proto != nil {
		return
	}
	file_charts_values_v1_global_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_mailroom_proto_rawDesc), len(file_charts_values_v1_mailroom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_mailroom_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_mailroom_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_mailroom_proto_msgTypes,
	}.Build()
	File_charts_values_v1_mailroom_proto = out.File
	file_charts_values_v1_mailroom_proto_goTypes = nil
	file_charts_values_v1_mailroom_proto_depIdxs = nil
}
