// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: charts/values/v1/sidekiq.proto

package valuesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "gitlab.com/gitlab-org/charts/gitlab/pkg/values/gitlab/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SidekiqValues is the top-level schema for the sidekiq sub-chart values.yaml.
type SidekiqValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container image configuration (repository, tag, pullPolicy, pullSecrets).
	Image *structpb.Struct `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container configuration.
	Init *SidekiqInit `protobuf:"bytes,2,opt,name=init,proto3" json:"init,omitempty"`
	// Tolerations for pod scheduling.
	Tolerations []*structpb.Struct `protobuf:"bytes,3,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	// Whether the sidekiq sub-chart is enabled.
	Enabled bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Annotations applied to the deployment.
	Annotations *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Labels applied to pods.
	PodLabels *structpb.Struct `protobuf:"bytes,6,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Common labels configuration.
	Common *SidekiqCommon `protobuf:"bytes,7,opt,name=common,proto3" json:"common,omitempty"`
	// Logging configuration.
	Logging *SidekiqLogging `protobuf:"bytes,8,opt,name=logging,proto3" json:"logging,omitempty"`
	// Network policy configuration.
	Networkpolicy *SidekiqNetworkPolicy `protobuf:"bytes,9,opt,name=networkpolicy,proto3" json:"networkpolicy,omitempty"`
	// Metrics/monitoring configuration.
	Metrics *SidekiqMetrics `protobuf:"bytes,10,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Health check listener configuration.
	HealthChecks *SidekiqHealthChecks `protobuf:"bytes,11,opt,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	// Redis connection configuration.
	Redis *SidekiqRedis `protobuf:"bytes,12,opt,name=redis,proto3" json:"redis,omitempty"`
	// PostgreSQL connection overrides.
	Psql *structpb.Struct `protobuf:"bytes,13,opt,name=psql,proto3" json:"psql,omitempty"`
	// Sidekiq memory killer configuration.
	MemoryKiller *SidekiqMemoryKiller `protobuf:"bytes,14,opt,name=memory_killer,json=memoryKiller,proto3" json:"memory_killer,omitempty"`
	// Liveness probe configuration.
	LivenessProbe *SidekiqProbe `protobuf:"bytes,15,opt,name=liveness_probe,json=livenessProbe,proto3" json:"liveness_probe,omitempty"`
	// Readiness probe configuration.
	ReadinessProbe *SidekiqProbe `protobuf:"bytes,16,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	// Global settings shared across sub-charts.
	Global *GlobalConfig `protobuf:"bytes,17,opt,name=global,proto3" json:"global,omitempty"`
	// Gitaly connection configuration.
	Gitaly *SidekiqGitaly `protobuf:"bytes,18,opt,name=gitaly,proto3" json:"gitaly,omitempty"`
	// Additional freeform configuration passthrough.
	Extra *structpb.Struct `protobuf:"bytes,19,opt,name=extra,proto3" json:"extra,omitempty"`
	// Additional environment variables applied to every container in the pod.
	ExtraEnv *structpb.Struct `protobuf:"bytes,20,opt,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty"`
	// Rack::Attack configuration.
	RackAttack *SidekiqRackAttack `protobuf:"bytes,21,opt,name=rack_attack,json=rackAttack,proto3" json:"rack_attack,omitempty"`
	// Trusted proxies for the deployment.
	TrustedProxies []string `protobuf:"bytes,22,rep,name=trusted_proxies,json=trustedProxies,proto3" json:"trusted_proxies,omitempty"`
	// Minimum number of pod replicas.
	MinReplicas uint32 `protobuf:"varint,23,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// Maximum number of pod replicas.
	MaxReplicas uint32 `protobuf:"varint,24,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// Sidekiq concurrency (number of threads).
	Concurrency uint32 `protobuf:"varint,25,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Deployment strategy configuration.
	Deployment *SidekiqDeployment `protobuf:"bytes,26,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Horizontal Pod Autoscaler configuration.
	Hpa *SidekiqHpa `protobuf:"bytes,27,opt,name=hpa,proto3" json:"hpa,omitempty"`
	// KEDA autoscaling configuration.
	Keda *SidekiqKeda `protobuf:"bytes,28,opt,name=keda,proto3" json:"keda,omitempty"`
	// Sidekiq shutdown timeout in seconds.
	Timeout uint32 `protobuf:"varint,29,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,30,opt,name=resources,proto3" json:"resources,omitempty"`
	// Maximum number of unavailable pods during disruption.
	MaxUnavailable uint32 `protobuf:"varint,31,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	// Queue groups partitioned into pods.
	Pods []*SidekiqPod `protobuf:"bytes,32,rep,name=pods,proto3" json:"pods,omitempty"`
	// Pod-level security context.
	SecurityContext *structpb.Struct `protobuf:"bytes,33,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	// Container-level security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,34,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	// Service account configuration.
	ServiceAccount *SidekiqServiceAccount `protobuf:"bytes,35,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Priority class assigned to pods.
	PriorityClassName string `protobuf:"bytes,36,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// Anti-affinity mode: "hard" or "soft".
	AntiAffinity string `protobuf:"bytes,37,opt,name=anti_affinity,json=antiAffinity,proto3" json:"anti_affinity,omitempty"`
	// Pod affinity/anti-affinity configuration.
	Affinity *structpb.Struct `protobuf:"bytes,38,opt,name=affinity,proto3" json:"affinity,omitempty"`
	// Topology spread constraints.
	TopologySpreadConstraints *structpb.Struct `protobuf:"bytes,39,opt,name=topology_spread_constraints,json=topologySpreadConstraints,proto3" json:"topology_spread_constraints,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SidekiqValues) Reset() {
	*x = SidekiqValues{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqValues) ProtoMessage() {}

func (x *SidekiqValues) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqValues.ProtoReflect.Descriptor instead.
func (*SidekiqValues) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{0}
}

func (x *SidekiqValues) GetImage() *structpb.Struct {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SidekiqValues) GetInit() *SidekiqInit {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *SidekiqValues) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

func (x *SidekiqValues) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqValues) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *SidekiqValues) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *SidekiqValues) GetCommon() *SidekiqCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SidekiqValues) GetLogging() *SidekiqLogging {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *SidekiqValues) GetNetworkpolicy() *SidekiqNetworkPolicy {
	if x != nil {
		return x.Networkpolicy
	}
	return nil
}

func (x *SidekiqValues) GetMetrics() *SidekiqMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SidekiqValues) GetHealthChecks() *SidekiqHealthChecks {
	if x != nil {
		return x.HealthChecks
	}
	return nil
}

func (x *SidekiqValues) GetRedis() *SidekiqRedis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *SidekiqValues) GetPsql() *structpb.Struct {
	if x != nil {
		return x.Psql
	}
	return nil
}

func (x *SidekiqValues) GetMemoryKiller() *SidekiqMemoryKiller {
	if x != nil {
		return x.MemoryKiller
	}
	return nil
}

func (x *SidekiqValues) GetLivenessProbe() *SidekiqProbe {
	if x != nil {
		return x.LivenessProbe
	}
	return nil
}

func (x *SidekiqValues) GetReadinessProbe() *SidekiqProbe {
	if x != nil {
		return x.ReadinessProbe
	}
	return nil
}

func (x *SidekiqValues) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *SidekiqValues) GetGitaly() *SidekiqGitaly {
	if x != nil {
		return x.Gitaly
	}
	return nil
}

func (x *SidekiqValues) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *SidekiqValues) GetExtraEnv() *structpb.Struct {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

func (x *SidekiqValues) GetRackAttack() *SidekiqRackAttack {
	if x != nil {
		return x.RackAttack
	}
	return nil
}

func (x *SidekiqValues) GetTrustedProxies() []string {
	if x != nil {
		return x.TrustedProxies
	}
	return nil
}

func (x *SidekiqValues) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *SidekiqValues) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *SidekiqValues) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *SidekiqValues) GetDeployment() *SidekiqDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *SidekiqValues) GetHpa() *SidekiqHpa {
	if x != nil {
		return x.Hpa
	}
	return nil
}

func (x *SidekiqValues) GetKeda() *SidekiqKeda {
	if x != nil {
		return x.Keda
	}
	return nil
}

func (x *SidekiqValues) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SidekiqValues) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SidekiqValues) GetMaxUnavailable() uint32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

func (x *SidekiqValues) GetPods() []*SidekiqPod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *SidekiqValues) GetSecurityContext() *structpb.Struct {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *SidekiqValues) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

func (x *SidekiqValues) GetServiceAccount() *SidekiqServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *SidekiqValues) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *SidekiqValues) GetAntiAffinity() string {
	if x != nil {
		return x.AntiAffinity
	}
	return ""
}

func (x *SidekiqValues) GetAffinity() *structpb.Struct {
	if x != nil {
		return x.Affinity
	}
	return nil
}

func (x *SidekiqValues) GetTopologySpreadConstraints() *structpb.Struct {
	if x != nil {
		return x.TopologySpreadConstraints
	}
	return nil
}

// SidekiqInit configures the init container.
type SidekiqInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Init container image configuration.
	Image *structpb.Struct `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Init container resource requests and limits.
	Resources *structpb.Struct `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Init container security context.
	ContainerSecurityContext *structpb.Struct `protobuf:"bytes,3,opt,name=container_security_context,json=containerSecurityContext,proto3" json:"container_security_context,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SidekiqInit) Reset() {
	*x = SidekiqInit{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqInit) ProtoMessage() {}

func (x *SidekiqInit) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqInit.ProtoReflect.Descriptor instead.
func (*SidekiqInit) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{1}
}

func (x *SidekiqInit) GetImage() *structpb.Struct {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SidekiqInit) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SidekiqInit) GetContainerSecurityContext() *structpb.Struct {
	if x != nil {
		return x.ContainerSecurityContext
	}
	return nil
}

// SidekiqCommon holds labels shared across resources.
type SidekiqCommon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common labels applied to resources.
	Labels        *structpb.Struct `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqCommon) Reset() {
	*x = SidekiqCommon{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqCommon) ProtoMessage() {}

func (x *SidekiqCommon) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqCommon.ProtoReflect.Descriptor instead.
func (*SidekiqCommon) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{2}
}

func (x *SidekiqCommon) GetLabels() *structpb.Struct {
	if x != nil {
		return x.Labels
	}
	return nil
}

// SidekiqLogging configures log output.
type SidekiqLogging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log format; set to "json" for structured logs.
	Format        string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqLogging) Reset() {
	*x = SidekiqLogging{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqLogging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqLogging) ProtoMessage() {}

func (x *SidekiqLogging) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqLogging.ProtoReflect.Descriptor instead.
func (*SidekiqLogging) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{3}
}

func (x *SidekiqLogging) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// SidekiqNetworkPolicy configures the network policy.
type SidekiqNetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the network policy is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Egress rules configuration.
	Egress *SidekiqNetworkPolicyRuleSet `protobuf:"bytes,2,opt,name=egress,proto3" json:"egress,omitempty"`
	// Ingress rules configuration.
	Ingress *SidekiqNetworkPolicyRuleSet `protobuf:"bytes,3,opt,name=ingress,proto3" json:"ingress,omitempty"`
	// Annotations applied to the network policy.
	Annotations   *structpb.Struct `protobuf:"bytes,4,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqNetworkPolicy) Reset() {
	*x = SidekiqNetworkPolicy{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqNetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqNetworkPolicy) ProtoMessage() {}

func (x *SidekiqNetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqNetworkPolicy.ProtoReflect.Descriptor instead.
func (*SidekiqNetworkPolicy) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{4}
}

func (x *SidekiqNetworkPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqNetworkPolicy) GetEgress() *SidekiqNetworkPolicyRuleSet {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *SidekiqNetworkPolicy) GetIngress() *SidekiqNetworkPolicyRuleSet {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *SidekiqNetworkPolicy) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// SidekiqNetworkPolicyRuleSet configures one direction of network rules.
type SidekiqNetworkPolicyRuleSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this rule set is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Network policy rules.
	Rules         *structpb.Struct `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqNetworkPolicyRuleSet) Reset() {
	*x = SidekiqNetworkPolicyRuleSet{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqNetworkPolicyRuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqNetworkPolicyRuleSet) ProtoMessage() {}

func (x *SidekiqNetworkPolicyRuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqNetworkPolicyRuleSet.ProtoReflect.Descriptor instead.
func (*SidekiqNetworkPolicyRuleSet) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{5}
}

func (x *SidekiqNetworkPolicyRuleSet) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqNetworkPolicyRuleSet) GetRules() *structpb.Struct {
	if x != nil {
		return x.Rules
	}
	return nil
}

// SidekiqMetrics configures metrics exposure and monitoring.
type SidekiqMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics are enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Address the metrics endpoint binds to.
	ListenAddr string `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	// Port the metrics endpoint listens on.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// HTTP path for metrics.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Whether metrics request logging is enabled.
	LogEnabled bool `protobuf:"varint,5,opt,name=log_enabled,json=logEnabled,proto3" json:"log_enabled,omitempty"`
	// PodMonitor configuration.
	PodMonitor *SidekiqPodMonitor `protobuf:"bytes,6,opt,name=pod_monitor,json=podMonitor,proto3" json:"pod_monitor,omitempty"`
	// DEPRECATED: annotations applied to the metrics service.
	Annotations *structpb.Struct `protobuf:"bytes,7,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// TLS configuration for the metrics endpoint.
	Tls           *SidekiqMetricsTls `protobuf:"bytes,8,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqMetrics) Reset() {
	*x = SidekiqMetrics{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqMetrics) ProtoMessage() {}

func (x *SidekiqMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqMetrics.ProtoReflect.Descriptor instead.
func (*SidekiqMetrics) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{6}
}

func (x *SidekiqMetrics) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqMetrics) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *SidekiqMetrics) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SidekiqMetrics) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SidekiqMetrics) GetLogEnabled() bool {
	if x != nil {
		return x.LogEnabled
	}
	return false
}

func (x *SidekiqMetrics) GetPodMonitor() *SidekiqPodMonitor {
	if x != nil {
		return x.PodMonitor
	}
	return nil
}

func (x *SidekiqMetrics) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *SidekiqMetrics) GetTls() *SidekiqMetricsTls {
	if x != nil {
		return x.Tls
	}
	return nil
}

// SidekiqPodMonitor configures a Prometheus PodMonitor.
type SidekiqPodMonitor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the PodMonitor is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Additional labels for the PodMonitor.
	AdditionalLabels *structpb.Struct `protobuf:"bytes,2,opt,name=additional_labels,json=additionalLabels,proto3" json:"additional_labels,omitempty"`
	// Endpoint configuration for the PodMonitor.
	EndpointConfig *structpb.Struct `protobuf:"bytes,3,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SidekiqPodMonitor) Reset() {
	*x = SidekiqPodMonitor{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqPodMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqPodMonitor) ProtoMessage() {}

func (x *SidekiqPodMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqPodMonitor.ProtoReflect.Descriptor instead.
func (*SidekiqPodMonitor) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{7}
}

func (x *SidekiqPodMonitor) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqPodMonitor) GetAdditionalLabels() *structpb.Struct {
	if x != nil {
		return x.AdditionalLabels
	}
	return nil
}

func (x *SidekiqPodMonitor) GetEndpointConfig() *structpb.Struct {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

// SidekiqMetricsTls configures TLS for the metrics endpoint.
type SidekiqMetricsTls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether metrics TLS is enabled.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqMetricsTls) Reset() {
	*x = SidekiqMetricsTls{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqMetricsTls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqMetricsTls) ProtoMessage() {}

func (x *SidekiqMetricsTls) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqMetricsTls.ProtoReflect.Descriptor instead.
func (*SidekiqMetricsTls) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{8}
}

func (x *SidekiqMetricsTls) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SidekiqHealthChecks configures the health check listener.
type SidekiqHealthChecks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address the health check endpoint binds to.
	ListenAddr string `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	// Port the health check endpoint listens on.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqHealthChecks) Reset() {
	*x = SidekiqHealthChecks{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqHealthChecks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqHealthChecks) ProtoMessage() {}

func (x *SidekiqHealthChecks) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqHealthChecks.ProtoReflect.Descriptor instead.
func (*SidekiqHealthChecks) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{9}
}

func (x *SidekiqHealthChecks) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *SidekiqHealthChecks) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// SidekiqRedis configures the Redis connection.
type SidekiqRedis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis authentication configuration.
	Auth          *structpb.Struct `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqRedis) Reset() {
	*x = SidekiqRedis{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqRedis) ProtoMessage() {}

func (x *SidekiqRedis) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqRedis.ProtoReflect.Descriptor instead.
func (*SidekiqRedis) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{10}
}

func (x *SidekiqRedis) GetAuth() *structpb.Struct {
	if x != nil {
		return x.Auth
	}
	return nil
}

// SidekiqMemoryKiller configures the Sidekiq memory killer.
type SidekiqMemoryKiller struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the memory killer runs in daemon mode.
	DaemonMode bool `protobuf:"varint,1,opt,name=daemon_mode,json=daemonMode,proto3" json:"daemon_mode,omitempty"`
	// Maximum RSS in bytes before a restart is triggered.
	MaxRss uint32 `protobuf:"varint,2,opt,name=max_rss,json=maxRss,proto3" json:"max_rss,omitempty"`
	// Grace time in seconds before the process is killed.
	GraceTime uint32 `protobuf:"varint,3,opt,name=grace_time,json=graceTime,proto3" json:"grace_time,omitempty"`
	// Time in seconds to wait after signalling shutdown.
	ShutdownWait uint32 `protobuf:"varint,4,opt,name=shutdown_wait,json=shutdownWait,proto3" json:"shutdown_wait,omitempty"`
	// Interval in seconds between RSS checks.
	CheckInterval uint32 `protobuf:"varint,5,opt,name=check_interval,json=checkInterval,proto3" json:"check_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqMemoryKiller) Reset() {
	*x = SidekiqMemoryKiller{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqMemoryKiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqMemoryKiller) ProtoMessage() {}

func (x *SidekiqMemoryKiller) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqMemoryKiller.ProtoReflect.Descriptor instead.
func (*SidekiqMemoryKiller) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{11}
}

func (x *SidekiqMemoryKiller) GetDaemonMode() bool {
	if x != nil {
		return x.DaemonMode
	}
	return false
}

func (x *SidekiqMemoryKiller) GetMaxRss() uint32 {
	if x != nil {
		return x.MaxRss
	}
	return 0
}

func (x *SidekiqMemoryKiller) GetGraceTime() uint32 {
	if x != nil {
		return x.GraceTime
	}
	return 0
}

func (x *SidekiqMemoryKiller) GetShutdownWait() uint32 {
	if x != nil {
		return x.ShutdownWait
	}
	return 0
}

func (x *SidekiqMemoryKiller) GetCheckInterval() uint32 {
	if x != nil {
		return x.CheckInterval
	}
	return 0
}

// SidekiqProbe configures a liveness or readiness probe.
type SidekiqProbe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delay before the probe is initiated.
	InitialDelaySeconds uint32 `protobuf:"varint,1,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"`
	// Interval between probe attempts.
	PeriodSeconds uint32 `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// Probe timeout.
	TimeoutSeconds uint32 `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Consecutive successes for the probe to be considered successful.
	SuccessThreshold uint32 `protobuf:"varint,4,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	// Consecutive failures for the probe to be considered failed.
	FailureThreshold uint32 `protobuf:"varint,5,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SidekiqProbe) Reset() {
	*x = SidekiqProbe{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqProbe) ProtoMessage() {}

func (x *SidekiqProbe) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqProbe.ProtoReflect.Descriptor instead.
func (*SidekiqProbe) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{12}
}

func (x *SidekiqProbe) GetInitialDelaySeconds() uint32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

func (x *SidekiqProbe) GetPeriodSeconds() uint32 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *SidekiqProbe) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *SidekiqProbe) GetSuccessThreshold() uint32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

func (x *SidekiqProbe) GetFailureThreshold() uint32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

// SidekiqGitaly configures the Gitaly connection.
type SidekiqGitaly struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gitaly auth token secret reference.
	AuthToken     *structpb.Struct `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqGitaly) Reset() {
	*x = SidekiqGitaly{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqGitaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqGitaly) ProtoMessage() {}

func (x *SidekiqGitaly) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqGitaly.ProtoReflect.Descriptor instead.
func (*SidekiqGitaly) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{13}
}

func (x *SidekiqGitaly) GetAuthToken() *structpb.Struct {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

// SidekiqRackAttack configures Rack::Attack throttling.
type SidekiqRackAttack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Git basic auth throttling configuration.
	GitBasicAuth  *SidekiqGitBasicAuth `protobuf:"bytes,1,opt,name=git_basic_auth,json=gitBasicAuth,proto3" json:"git_basic_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqRackAttack) Reset() {
	*x = SidekiqRackAttack{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqRackAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqRackAttack) ProtoMessage() {}

func (x *SidekiqRackAttack) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqRackAttack.ProtoReflect.Descriptor instead.
func (*SidekiqRackAttack) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{14}
}

func (x *SidekiqRackAttack) GetGitBasicAuth() *SidekiqGitBasicAuth {
	if x != nil {
		return x.GitBasicAuth
	}
	return nil
}

// SidekiqGitBasicAuth configures git basic auth throttling.
type SidekiqGitBasicAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether git basic auth throttling is enabled.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqGitBasicAuth) Reset() {
	*x = SidekiqGitBasicAuth{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqGitBasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqGitBasicAuth) ProtoMessage() {}

func (x *SidekiqGitBasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqGitBasicAuth.ProtoReflect.Descriptor instead.
func (*SidekiqGitBasicAuth) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{15}
}

func (x *SidekiqGitBasicAuth) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SidekiqDeployment configures the deployment upgrade strategy.
type SidekiqDeployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment update strategy.
	Strategy *structpb.Struct `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Grace period in seconds before pod termination.
	TerminationGracePeriodSeconds uint32 `protobuf:"varint,2,opt,name=termination_grace_period_seconds,json=terminationGracePeriodSeconds,proto3" json:"termination_grace_period_seconds,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SidekiqDeployment) Reset() {
	*x = SidekiqDeployment{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqDeployment) ProtoMessage() {}

func (x *SidekiqDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqDeployment.ProtoReflect.Descriptor instead.
func (*SidekiqDeployment) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{16}
}

func (x *SidekiqDeployment) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *SidekiqDeployment) GetTerminationGracePeriodSeconds() uint32 {
	if x != nil {
		return x.TerminationGracePeriodSeconds
	}
	return 0
}

// SidekiqHpa configures the Horizontal Pod Autoscaler.
type SidekiqHpa struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU-based scaling target.
	Cpu *SidekiqHpaMetric `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Custom metrics overriding the default HPA metrics definition.
	CustomMetrics *structpb.Struct `protobuf:"bytes,2,opt,name=custom_metrics,json=customMetrics,proto3" json:"custom_metrics,omitempty"`
	// Scaling behavior configuration.
	Behavior      *SidekiqHpaBehavior `protobuf:"bytes,3,opt,name=behavior,proto3" json:"behavior,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqHpa) Reset() {
	*x = SidekiqHpa{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqHpa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqHpa) ProtoMessage() {}

func (x *SidekiqHpa) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqHpa.ProtoReflect.Descriptor instead.
func (*SidekiqHpa) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{17}
}

func (x *SidekiqHpa) GetCpu() *SidekiqHpaMetric {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SidekiqHpa) GetCustomMetrics() *structpb.Struct {
	if x != nil {
		return x.CustomMetrics
	}
	return nil
}

func (x *SidekiqHpa) GetBehavior() *SidekiqHpaBehavior {
	if x != nil {
		return x.Behavior
	}
	return nil
}

// SidekiqHpaMetric configures a single HPA scaling metric.
type SidekiqHpaMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target type: "Utilization" or "AverageValue".
	TargetType string `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Target average value.
	TargetAverageValue string `protobuf:"bytes,2,opt,name=target_average_value,json=targetAverageValue,proto3" json:"target_average_value,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SidekiqHpaMetric) Reset() {
	*x = SidekiqHpaMetric{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqHpaMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqHpaMetric) ProtoMessage() {}

func (x *SidekiqHpaMetric) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqHpaMetric.ProtoReflect.Descriptor instead.
func (*SidekiqHpaMetric) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{18}
}

func (x *SidekiqHpaMetric) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *SidekiqHpaMetric) GetTargetAverageValue() string {
	if x != nil {
		return x.TargetAverageValue
	}
	return ""
}

// SidekiqHpaBehavior configures HPA scaling behavior.
type SidekiqHpaBehavior struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scale-down behavior.
	ScaleDown     *SidekiqHpaScaleDown `protobuf:"bytes,1,opt,name=scale_down,json=scaleDown,proto3" json:"scale_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqHpaBehavior) Reset() {
	*x = SidekiqHpaBehavior{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqHpaBehavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqHpaBehavior) ProtoMessage() {}

func (x *SidekiqHpaBehavior) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqHpaBehavior.ProtoReflect.Descriptor instead.
func (*SidekiqHpaBehavior) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{19}
}

func (x *SidekiqHpaBehavior) GetScaleDown() *SidekiqHpaScaleDown {
	if x != nil {
		return x.ScaleDown
	}
	return nil
}

// SidekiqHpaScaleDown configures HPA scale-down behavior.
type SidekiqHpaScaleDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stabilization window in seconds for scaling down.
	StabilizationWindowSeconds uint32 `protobuf:"varint,1,opt,name=stabilization_window_seconds,json=stabilizationWindowSeconds,proto3" json:"stabilization_window_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SidekiqHpaScaleDown) Reset() {
	*x = SidekiqHpaScaleDown{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqHpaScaleDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqHpaScaleDown) ProtoMessage() {}

func (x *SidekiqHpaScaleDown) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqHpaScaleDown.ProtoReflect.Descriptor instead.
func (*SidekiqHpaScaleDown) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{20}
}

func (x *SidekiqHpaScaleDown) GetStabilizationWindowSeconds() uint32 {
	if x != nil {
		return x.StabilizationWindowSeconds
	}
	return 0
}

// SidekiqKeda configures KEDA-based autoscaling.
type SidekiqKeda struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether KEDA autoscaling is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Polling interval in seconds.
	PollingInterval uint32 `protobuf:"varint,2,opt,name=polling_interval,json=pollingInterval,proto3" json:"polling_interval,omitempty"`
	// Cooldown period in seconds.
	CooldownPeriod uint32 `protobuf:"varint,3,opt,name=cooldown_period,json=cooldownPeriod,proto3" json:"cooldown_period,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SidekiqKeda) Reset() {
	*x = SidekiqKeda{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqKeda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqKeda) ProtoMessage() {}

func (x *SidekiqKeda) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqKeda.ProtoReflect.Descriptor instead.
func (*SidekiqKeda) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{21}
}

func (x *SidekiqKeda) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqKeda) GetPollingInterval() uint32 {
	if x != nil {
		return x.PollingInterval
	}
	return 0
}

func (x *SidekiqKeda) GetCooldownPeriod() uint32 {
	if x != nil {
		return x.CooldownPeriod
	}
	return 0
}

// SidekiqServiceAccount configures the service account.
type SidekiqServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to use a service account.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether to create the service account.
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	// Annotations applied to the service account.
	Annotations   *structpb.Struct `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqServiceAccount) Reset() {
	*x = SidekiqServiceAccount{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqServiceAccount) ProtoMessage() {}

func (x *SidekiqServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqServiceAccount.ProtoReflect.Descriptor instead.
func (*SidekiqServiceAccount) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{22}
}

func (x *SidekiqServiceAccount) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqServiceAccount) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *SidekiqServiceAccount) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// SidekiqPod defines a queue-group pod configuration.
type SidekiqPod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the queue-group pod.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Sidekiq concurrency for this pod.
	Concurrency uint32 `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// Memory killer overrides for this pod.
	MemoryKiller *SidekiqMemoryKiller `protobuf:"bytes,3,opt,name=memory_killer,json=memoryKiller,proto3" json:"memory_killer,omitempty"`
	// Minimum replicas for this pod.
	MinReplicas uint32 `protobuf:"varint,4,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	// Maximum replicas for this pod.
	MaxReplicas uint32 `protobuf:"varint,5,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	// Deployment strategy for this pod.
	Strategy *structpb.Struct `protobuf:"bytes,6,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Sidekiq queues handled by this pod.
	Queues string `protobuf:"bytes,7,opt,name=queues,proto3" json:"queues,omitempty"`
	// Additional volumes for this pod.
	ExtraVolumes *structpb.Struct `protobuf:"bytes,8,opt,name=extra_volumes,json=extraVolumes,proto3" json:"extra_volumes,omitempty"`
	// Additional volume mounts for this pod.
	ExtraVolumeMounts *structpb.Struct `protobuf:"bytes,9,opt,name=extra_volume_mounts,json=extraVolumeMounts,proto3" json:"extra_volume_mounts,omitempty"`
	// Priority class for this pod.
	PriorityClassName string `protobuf:"bytes,10,opt,name=priority_class_name,json=priorityClassName,proto3" json:"priority_class_name,omitempty"`
	// HPA configuration for this pod.
	Hpa *SidekiqHpa `protobuf:"bytes,11,opt,name=hpa,proto3" json:"hpa,omitempty"`
	// KEDA configuration for this pod.
	Keda *SidekiqKeda `protobuf:"bytes,12,opt,name=keda,proto3" json:"keda,omitempty"`
	// Common labels for this pod.
	Common *SidekiqCommon `protobuf:"bytes,13,opt,name=common,proto3" json:"common,omitempty"`
	// Labels applied to this pod.
	PodLabels *structpb.Struct `protobuf:"bytes,14,opt,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty"`
	// Grace period in seconds before pod termination.
	TerminationGracePeriodSeconds uint32 `protobuf:"varint,15,opt,name=termination_grace_period_seconds,json=terminationGracePeriodSeconds,proto3" json:"termination_grace_period_seconds,omitempty"`
	// Node selector for this pod.
	NodeSelector *structpb.Struct `protobuf:"bytes,16,opt,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty"`
	// Tolerations for this pod.
	Tolerations   []*structpb.Struct `protobuf:"bytes,17,rep,name=tolerations,proto3" json:"tolerations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqPod) Reset() {
	*x = SidekiqPod{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqPod) ProtoMessage() {}

func (x *SidekiqPod) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqPod.ProtoReflect.Descriptor instead.
func (*SidekiqPod) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{23}
}

func (x *SidekiqPod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SidekiqPod) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *SidekiqPod) GetMemoryKiller() *SidekiqMemoryKiller {
	if x != nil {
		return x.MemoryKiller
	}
	return nil
}

func (x *SidekiqPod) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *SidekiqPod) GetMaxReplicas() uint32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *SidekiqPod) GetStrategy() *structpb.Struct {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *SidekiqPod) GetQueues() string {
	if x != nil {
		return x.Queues
	}
	return ""
}

func (x *SidekiqPod) GetExtraVolumes() *structpb.Struct {
	if x != nil {
		return x.ExtraVolumes
	}
	return nil
}

func (x *SidekiqPod) GetExtraVolumeMounts() *structpb.Struct {
	if x != nil {
		return x.ExtraVolumeMounts
	}
	return nil
}

func (x *SidekiqPod) GetPriorityClassName() string {
	if x != nil {
		return x.PriorityClassName
	}
	return ""
}

func (x *SidekiqPod) GetHpa() *SidekiqHpa {
	if x != nil {
		return x.Hpa
	}
	return nil
}

func (x *SidekiqPod) GetKeda() *SidekiqKeda {
	if x != nil {
		return x.Keda
	}
	return nil
}

func (x *SidekiqPod) GetCommon() *SidekiqCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SidekiqPod) GetPodLabels() *structpb.Struct {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *SidekiqPod) GetTerminationGracePeriodSeconds() uint32 {
	if x != nil {
		return x.TerminationGracePeriodSeconds
	}
	return 0
}

func (x *SidekiqPod) GetNodeSelector() *structpb.Struct {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

func (x *SidekiqPod) GetTolerations() []*structpb.Struct {
	if x != nil {
		return x.Tolerations
	}
	return nil
}

// SidekiqMicrosoftGraphMailer configures the Microsoft Graph mailer.
type SidekiqMicrosoftGraphMailer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the Microsoft Graph mailer is enabled.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqMicrosoftGraphMailer) Reset() {
	*x = SidekiqMicrosoftGraphMailer{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqMicrosoftGraphMailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqMicrosoftGraphMailer) ProtoMessage() {}

func (x *SidekiqMicrosoftGraphMailer) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqMicrosoftGraphMailer.ProtoReflect.Descriptor instead.
func (*SidekiqMicrosoftGraphMailer) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{24}
}

func (x *SidekiqMicrosoftGraphMailer) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SidekiqIncomingEmail configures incoming email handling.
type SidekiqIncomingEmail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether incoming email is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Incoming email address.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqIncomingEmail) Reset() {
	*x = SidekiqIncomingEmail{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqIncomingEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqIncomingEmail) ProtoMessage() {}

func (x *SidekiqIncomingEmail) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqIncomingEmail.ProtoReflect.Descriptor instead.
func (*SidekiqIncomingEmail) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{25}
}

func (x *SidekiqIncomingEmail) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqIncomingEmail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// SidekiqServiceDeskEmail configures Service Desk email handling.
type SidekiqServiceDeskEmail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Service Desk email is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Service Desk email address.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqServiceDeskEmail) Reset() {
	*x = SidekiqServiceDeskEmail{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqServiceDeskEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqServiceDeskEmail) ProtoMessage() {}

func (x *SidekiqServiceDeskEmail) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqServiceDeskEmail.ProtoReflect.Descriptor instead.
func (*SidekiqServiceDeskEmail) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{26}
}

func (x *SidekiqServiceDeskEmail) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqServiceDeskEmail) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// SidekiqObjectStorage configures an object storage backend.
type SidekiqObjectStorage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this object storage is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Whether downloads are proxied through GitLab.
	ProxyDownload bool `protobuf:"varint,2,opt,name=proxy_download,json=proxyDownload,proto3" json:"proxy_download,omitempty"`
	// Storage bucket name.
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Object storage connection configuration.
	Connection    *structpb.Struct `protobuf:"bytes,4,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqObjectStorage) Reset() {
	*x = SidekiqObjectStorage{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqObjectStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqObjectStorage) ProtoMessage() {}

func (x *SidekiqObjectStorage) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqObjectStorage.ProtoReflect.Descriptor instead.
func (*SidekiqObjectStorage) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{27}
}

func (x *SidekiqObjectStorage) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqObjectStorage) GetProxyDownload() bool {
	if x != nil {
		return x.ProxyDownload
	}
	return false
}

func (x *SidekiqObjectStorage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SidekiqObjectStorage) GetConnection() *structpb.Struct {
	if x != nil {
		return x.Connection
	}
	return nil
}

// SidekiqExternalDiffs configures external merge request diff storage.
type SidekiqExternalDiffs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When to store diffs externally.
	When string `protobuf:"bytes,1,opt,name=when,proto3" json:"when,omitempty"`
	// Whether downloads are proxied through GitLab.
	ProxyDownload bool `protobuf:"varint,2,opt,name=proxy_download,json=proxyDownload,proto3" json:"proxy_download,omitempty"`
	// Storage bucket name.
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Object storage connection configuration.
	Connection    *structpb.Struct `protobuf:"bytes,4,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqExternalDiffs) Reset() {
	*x = SidekiqExternalDiffs{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqExternalDiffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqExternalDiffs) ProtoMessage() {}

func (x *SidekiqExternalDiffs) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqExternalDiffs.ProtoReflect.Descriptor instead.
func (*SidekiqExternalDiffs) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{28}
}

func (x *SidekiqExternalDiffs) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

func (x *SidekiqExternalDiffs) GetProxyDownload() bool {
	if x != nil {
		return x.ProxyDownload
	}
	return false
}

func (x *SidekiqExternalDiffs) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SidekiqExternalDiffs) GetConnection() *structpb.Struct {
	if x != nil {
		return x.Connection
	}
	return nil
}

// SidekiqTerraformState configures Terraform state storage.
type SidekiqTerraformState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Terraform state storage is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Storage bucket name.
	Bucket string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Object storage connection configuration.
	Connection    *structpb.Struct `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqTerraformState) Reset() {
	*x = SidekiqTerraformState{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqTerraformState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqTerraformState) ProtoMessage() {}

func (x *SidekiqTerraformState) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqTerraformState.ProtoReflect.Descriptor instead.
func (*SidekiqTerraformState) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{29}
}

func (x *SidekiqTerraformState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqTerraformState) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SidekiqTerraformState) GetConnection() *structpb.Struct {
	if x != nil {
		return x.Connection
	}
	return nil
}

// SidekiqLdap configures LDAP servers.
type SidekiqLdap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LDAP server definitions keyed by provider ID.
	Servers       *structpb.Struct `protobuf:"bytes,1,opt,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqLdap) Reset() {
	*x = SidekiqLdap{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqLdap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqLdap) ProtoMessage() {}

func (x *SidekiqLdap) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqLdap.ProtoReflect.Descriptor instead.
func (*SidekiqLdap) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{30}
}

func (x *SidekiqLdap) GetServers() *structpb.Struct {
	if x != nil {
		return x.Servers
	}
	return nil
}

// SidekiqOmniauth configures OmniAuth providers.
type SidekiqOmniauth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether OmniAuth is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Provider to automatically sign in with.
	AutoSignInWithProvider string `protobuf:"bytes,2,opt,name=auto_sign_in_with_provider,json=autoSignInWithProvider,proto3" json:"auto_sign_in_with_provider,omitempty"`
	// Providers to sync profile from.
	SyncProfileFromProvider []string `protobuf:"bytes,3,rep,name=sync_profile_from_provider,json=syncProfileFromProvider,proto3" json:"sync_profile_from_provider,omitempty"`
	// Profile attributes to sync.
	SyncProfileAttributes []string `protobuf:"bytes,4,rep,name=sync_profile_attributes,json=syncProfileAttributes,proto3" json:"sync_profile_attributes,omitempty"`
	// Providers allowed for single sign-on.
	AllowSingleSignOn []string `protobuf:"bytes,5,rep,name=allow_single_sign_on,json=allowSingleSignOn,proto3" json:"allow_single_sign_on,omitempty"`
	// Whether auto-created users are blocked.
	BlockAutoCreatedUsers bool `protobuf:"varint,6,opt,name=block_auto_created_users,json=blockAutoCreatedUsers,proto3" json:"block_auto_created_users,omitempty"`
	// Whether to auto-link LDAP users.
	AutoLinkLdapUser bool `protobuf:"varint,7,opt,name=auto_link_ldap_user,json=autoLinkLdapUser,proto3" json:"auto_link_ldap_user,omitempty"`
	// Whether to auto-link SAML users.
	AutoLinkSamlUser bool `protobuf:"varint,8,opt,name=auto_link_saml_user,json=autoLinkSamlUser,proto3" json:"auto_link_saml_user,omitempty"`
	// Providers to auto-link users for.
	AutoLinkUser []string `protobuf:"bytes,9,rep,name=auto_link_user,json=autoLinkUser,proto3" json:"auto_link_user,omitempty"`
	// External providers.
	ExternalProviders []string `protobuf:"bytes,10,rep,name=external_providers,json=externalProviders,proto3" json:"external_providers,omitempty"`
	// Providers allowed to bypass two-factor authentication.
	AllowBypassTwoFactor []string `protobuf:"bytes,11,rep,name=allow_bypass_two_factor,json=allowBypassTwoFactor,proto3" json:"allow_bypass_two_factor,omitempty"`
	// Provider configuration secret references.
	Providers     []*SidekiqSecretRef `protobuf:"bytes,12,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqOmniauth) Reset() {
	*x = SidekiqOmniauth{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqOmniauth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqOmniauth) ProtoMessage() {}

func (x *SidekiqOmniauth) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqOmniauth.ProtoReflect.Descriptor instead.
func (*SidekiqOmniauth) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{31}
}

func (x *SidekiqOmniauth) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqOmniauth) GetAutoSignInWithProvider() string {
	if x != nil {
		return x.AutoSignInWithProvider
	}
	return ""
}

func (x *SidekiqOmniauth) GetSyncProfileFromProvider() []string {
	if x != nil {
		return x.SyncProfileFromProvider
	}
	return nil
}

func (x *SidekiqOmniauth) GetSyncProfileAttributes() []string {
	if x != nil {
		return x.SyncProfileAttributes
	}
	return nil
}

func (x *SidekiqOmniauth) GetAllowSingleSignOn() []string {
	if x != nil {
		return x.AllowSingleSignOn
	}
	return nil
}

func (x *SidekiqOmniauth) GetBlockAutoCreatedUsers() bool {
	if x != nil {
		return x.BlockAutoCreatedUsers
	}
	return false
}

func (x *SidekiqOmniauth) GetAutoLinkLdapUser() bool {
	if x != nil {
		return x.AutoLinkLdapUser
	}
	return false
}

func (x *SidekiqOmniauth) GetAutoLinkSamlUser() bool {
	if x != nil {
		return x.AutoLinkSamlUser
	}
	return false
}

func (x *SidekiqOmniauth) GetAutoLinkUser() []string {
	if x != nil {
		return x.AutoLinkUser
	}
	return nil
}

func (x *SidekiqOmniauth) GetExternalProviders() []string {
	if x != nil {
		return x.ExternalProviders
	}
	return nil
}

func (x *SidekiqOmniauth) GetAllowBypassTwoFactor() []string {
	if x != nil {
		return x.AllowBypassTwoFactor
	}
	return nil
}

func (x *SidekiqOmniauth) GetProviders() []*SidekiqSecretRef {
	if x != nil {
		return x.Providers
	}
	return nil
}

// SidekiqSentry configures Sentry error reporting.
type SidekiqSentry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Sentry is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Server-side Sentry DSN.
	Dsn string `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// Client-side Sentry DSN.
	ClientsideDsn string `protobuf:"bytes,3,opt,name=clientside_dsn,json=clientsideDsn,proto3" json:"clientside_dsn,omitempty"`
	// Sentry environment name.
	Environment   string `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqSentry) Reset() {
	*x = SidekiqSentry{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqSentry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqSentry) ProtoMessage() {}

func (x *SidekiqSentry) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqSentry.ProtoReflect.Descriptor instead.
func (*SidekiqSentry) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{32}
}

func (x *SidekiqSentry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SidekiqSentry) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *SidekiqSentry) GetClientsideDsn() string {
	if x != nil {
		return x.ClientsideDsn
	}
	return ""
}

func (x *SidekiqSentry) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// SidekiqSecretRef references a value stored in a Kubernetes Secret.
type SidekiqSecretRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Secret.
	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Key within the Secret.
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidekiqSecretRef) Reset() {
	*x = SidekiqSecretRef{}
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidekiqSecretRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidekiqSecretRef) ProtoMessage() {}

func (x *SidekiqSecretRef) ProtoReflect() protoreflect.Message {
	mi := &file_charts_values_v1_sidekiq_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidekiqSecretRef.ProtoReflect.Descriptor instead.
func (*SidekiqSecretRef) Descriptor() ([]byte, []int) {
	return file_charts_values_v1_sidekiq_proto_rawDescGZIP(), []int{33}
}

func (x *SidekiqSecretRef) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SidekiqSecretRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_charts_values_v1_sidekiq_proto protoreflect.FileDescriptor

const file_charts_values_v1_sidekiq_proto_rawDesc = "" +
	"\n" +
	"\x1echarts/values/v1/sidekiq.proto\x12\x10charts.values.v1\x1a\x1fgitlab/config/annotations.proto\x1a\x1dcharts/values/v1/global.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd3\x11\n" +
	"\rSidekiqValues\x12-\n" +
	"\x05image\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05image\x121\n" +
	"\x04init\x18\x02 \x01(\v2\x1d.charts.values.v1.SidekiqInitR\x04init\x129\n" +
	"\vtolerations\x18\x03 \x03(\v2\x17.google.protobuf.StructR\vtolerations\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x129\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructR\vannotations\x126\n" +
	"\n" +
	"pod_labels\x18\x06 \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x127\n" +
	"\x06common\x18\a \x01(\v2\x1f.charts.values.v1.SidekiqCommonR\x06common\x12:\n" +
	"\alogging\x18\b \x01(\v2 .charts.values.v1.SidekiqLoggingR\alogging\x12L\n" +
	"\rnetworkpolicy\x18\t \x01(\v2&.charts.values.v1.SidekiqNetworkPolicyR\rnetworkpolicy\x12:\n" +
	"\ametrics\x18\n" +
	" \x01(\v2 .charts.values.v1.SidekiqMetricsR\ametrics\x12]\n" +
	"\rhealth_checks\x18\v \x01(\v2%.charts.values.v1.SidekiqHealthChecksB\x11\x92\xb5\x18\rhealth_checksR\fhealthChecks\x124\n" +
	"\x05redis\x18\f \x01(\v2\x1e.charts.values.v1.SidekiqRedisR\x05redis\x12+\n" +
	"\x04psql\x18\r \x01(\v2\x17.google.protobuf.StructR\x04psql\x12J\n" +
	"\rmemory_killer\x18\x0e \x01(\v2%.charts.values.v1.SidekiqMemoryKillerR\fmemoryKiller\x12E\n" +
	"\x0eliveness_probe\x18\x0f \x01(\v2\x1e.charts.values.v1.SidekiqProbeR\rlivenessProbe\x12G\n" +
	"\x0freadiness_probe\x18\x10 \x01(\v2\x1e.charts.values.v1.SidekiqProbeR\x0ereadinessProbe\x126\n" +
	"\x06global\x18\x11 \x01(\v2\x1e.charts.values.v1.GlobalConfigR\x06global\x127\n" +
	"\x06gitaly\x18\x12 \x01(\v2\x1f.charts.values.v1.SidekiqGitalyR\x06gitaly\x12-\n" +
	"\x05extra\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x05extra\x124\n" +
	"\textra_env\x18\x14 \x01(\v2\x17.google.protobuf.StructR\bextraEnv\x12U\n" +
	"\vrack_attack\x18\x15 \x01(\v2#.charts.values.v1.SidekiqRackAttackB\x0f\x92\xb5\x18\vrack_attackR\n" +
	"rackAttack\x12<\n" +
	"\x0ftrusted_proxies\x18\x16 \x03(\tB\x13\x92\xb5\x18\x0ftrusted_proxiesR\x0etrustedProxies\x12!\n" +
	"\fmin_replicas\x18\x17 \x01(\rR\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x18 \x01(\rR\vmaxReplicas\x12 \n" +
	"\vconcurrency\x18\x19 \x01(\rR\vconcurrency\x12C\n" +
	"\n" +
	"deployment\x18\x1a \x01(\v2#.charts.values.v1.SidekiqDeploymentR\n" +
	"deployment\x12.\n" +
	"\x03hpa\x18\x1b \x01(\v2\x1c.charts.values.v1.SidekiqHpaR\x03hpa\x121\n" +
	"\x04keda\x18\x1c \x01(\v2\x1d.charts.values.v1.SidekiqKedaR\x04keda\x12\x18\n" +
	"\atimeout\x18\x1d \x01(\rR\atimeout\x125\n" +
	"\tresources\x18\x1e \x01(\v2\x17.google.protobuf.StructR\tresources\x12'\n" +
	"\x0fmax_unavailable\x18\x1f \x01(\rR\x0emaxUnavailable\x120\n" +
	"\x04pods\x18  \x03(\v2\x1c.charts.values.v1.SidekiqPodR\x04pods\x12B\n" +
	"\x10security_context\x18! \x01(\v2\x17.google.protobuf.StructR\x0fsecurityContext\x12U\n" +
	"\x1acontainer_security_context\x18\" \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext\x12P\n" +
	"\x0fservice_account\x18# \x01(\v2'.charts.values.v1.SidekiqServiceAccountR\x0eserviceAccount\x12.\n" +
	"\x13priority_class_name\x18$ \x01(\tR\x11priorityClassName\x12#\n" +
	"\ranti_affinity\x18% \x01(\tR\fantiAffinity\x123\n" +
	"\baffinity\x18& \x01(\v2\x17.google.protobuf.StructR\baffinity\x12W\n" +
	"\x1btopology_spread_constraints\x18' \x01(\v2\x17.google.protobuf.StructR\x19topologySpreadConstraints:\x04\x88\xb5\x18\x01\"\xd0\x01\n" +
	"\vSidekiqInit\x12-\n" +
	"\x05image\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05image\x125\n" +
	"\tresources\x18\x02 \x01(\v2\x17.google.protobuf.StructR\tresources\x12U\n" +
	"\x1acontainer_security_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x18containerSecurityContext:\x04\x88\xb5\x18\x01\"F\n" +
	"\rSidekiqCommon\x12/\n" +
	"\x06labels\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06labels:\x04\x88\xb5\x18\x01\".\n" +
	"\x0eSidekiqLogging\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format:\x04\x88\xb5\x18\x01\"\x81\x02\n" +
	"\x14SidekiqNetworkPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12E\n" +
	"\x06egress\x18\x02 \x01(\v2-.charts.values.v1.SidekiqNetworkPolicyRuleSetR\x06egress\x12G\n" +
	"\aingress\x18\x03 \x01(\v2-.charts.values.v1.SidekiqNetworkPolicyRuleSetR\aingress\x129\n" +
	"\vannotations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"l\n" +
	"\x1bSidekiqNetworkPolicyRuleSet\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x05rules\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05rules:\x04\x88\xb5\x18\x01\"\x86\x03\n" +
	"\x0eSidekiqMetrics\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12/\n" +
	"\vlisten_addr\x18\x02 \x01(\tB\x0e\x92\xb5\x18\n" +
	"listenAddrR\n" +
	"listenAddr\x12\x1f\n" +
	"\x04port\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x120\n" +
	"\vlog_enabled\x18\x05 \x01(\bB\x0f\x92\xb5\x18\vlog_enabledR\n" +
	"logEnabled\x12D\n" +
	"\vpod_monitor\x18\x06 \x01(\v2#.charts.values.v1.SidekiqPodMonitorR\n" +
	"podMonitor\x12?\n" +
	"\vannotations\x18\a \x01(\v2\x17.google.protobuf.StructB\x04\x98\xb5\x18\x05R\vannotations\x125\n" +
	"\x03tls\x18\b \x01(\v2#.charts.values.v1.SidekiqMetricsTlsR\x03tls:\x04\x88\xb5\x18\x01\"\xbb\x01\n" +
	"\x11SidekiqPodMonitor\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12D\n" +
	"\x11additional_labels\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x10additionalLabels\x12@\n" +
	"\x0fendpoint_config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0eendpointConfig:\x04\x88\xb5\x18\x01\"3\n" +
	"\x11SidekiqMetricsTls\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled:\x04\x88\xb5\x18\x01\"m\n" +
	"\x13SidekiqHealthChecks\x12/\n" +
	"\vlisten_addr\x18\x01 \x01(\tB\x0e\x92\xb5\x18\n" +
	"listenAddrR\n" +
	"listenAddr\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port:\x04\x88\xb5\x18\x01\"A\n" +
	"\fSidekiqRedis\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04auth:\x04\x88\xb5\x18\x01\"\xc0\x01\n" +
	"\x13SidekiqMemoryKiller\x12\x1f\n" +
	"\vdaemon_mode\x18\x01 \x01(\bR\n" +
	"daemonMode\x12\x17\n" +
	"\amax_rss\x18\x02 \x01(\rR\x06maxRss\x12\x1d\n" +
	"\n" +
	"grace_time\x18\x03 \x01(\rR\tgraceTime\x12#\n" +
	"\rshutdown_wait\x18\x04 \x01(\rR\fshutdownWait\x12%\n" +
	"\x0echeck_interval\x18\x05 \x01(\rR\rcheckInterval:\x04\x88\xb5\x18\x01\"\xf2\x01\n" +
	"\fSidekiqProbe\x122\n" +
	"\x15initial_delay_seconds\x18\x01 \x01(\rR\x13initialDelaySeconds\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\rR\rperiodSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rR\x0etimeoutSeconds\x12+\n" +
	"\x11success_threshold\x18\x04 \x01(\rR\x10successThreshold\x12+\n" +
	"\x11failure_threshold\x18\x05 \x01(\rR\x10failureThreshold:\x04\x88\xb5\x18\x01\"M\n" +
	"\rSidekiqGitaly\x126\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\v2\x17.google.protobuf.StructR\tauthToken:\x04\x88\xb5\x18\x01\"z\n" +
	"\x11SidekiqRackAttack\x12_\n" +
	"\x0egit_basic_auth\x18\x01 \x01(\v2%.charts.values.v1.SidekiqGitBasicAuthB\x12\x92\xb5\x18\x0egit_basic_authR\fgitBasicAuth:\x04\x88\xb5\x18\x01\"5\n" +
	"\x13SidekiqGitBasicAuth\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled:\x04\x88\xb5\x18\x01\"\x97\x01\n" +
	"\x11SidekiqDeployment\x123\n" +
	"\bstrategy\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bstrategy\x12G\n" +
	" termination_grace_period_seconds\x18\x02 \x01(\rR\x1dterminationGracePeriodSeconds:\x04\x88\xb5\x18\x01\"\xca\x01\n" +
	"\n" +
	"SidekiqHpa\x124\n" +
	"\x03cpu\x18\x01 \x01(\v2\".charts.values.v1.SidekiqHpaMetricR\x03cpu\x12>\n" +
	"\x0ecustom_metrics\x18\x02 \x01(\v2\x17.google.protobuf.StructR\rcustomMetrics\x12@\n" +
	"\bbehavior\x18\x03 \x01(\v2$.charts.values.v1.SidekiqHpaBehaviorR\bbehavior:\x04\x88\xb5\x18\x01\"k\n" +
	"\x10SidekiqHpaMetric\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x120\n" +
	"\x14target_average_value\x18\x02 \x01(\tR\x12targetAverageValue:\x04\x88\xb5\x18\x01\"`\n" +
	"\x12SidekiqHpaBehavior\x12D\n" +
	"\n" +
	"scale_down\x18\x01 \x01(\v2%.charts.values.v1.SidekiqHpaScaleDownR\tscaleDown:\x04\x88\xb5\x18\x01\"]\n" +
	"\x13SidekiqHpaScaleDown\x12@\n" +
	"\x1cstabilization_window_seconds\x18\x01 \x01(\rR\x1astabilizationWindowSeconds:\x04\x88\xb5\x18\x01\"\x81\x01\n" +
	"\vSidekiqKeda\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10polling_interval\x18\x02 \x01(\rR\x0fpollingInterval\x12'\n" +
	"\x0fcooldown_period\x18\x03 \x01(\rR\x0ecooldownPeriod:\x04\x88\xb5\x18\x01\"\x8a\x01\n" +
	"\x15SidekiqServiceAccount\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06create\x18\x02 \x01(\bR\x06create\x129\n" +
	"\vannotations\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vannotations:\x04\x88\xb5\x18\x01\"\xfd\x06\n" +
	"\n" +
	"SidekiqPod\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\rR\vconcurrency\x12J\n" +
	"\rmemory_killer\x18\x03 \x01(\v2%.charts.values.v1.SidekiqMemoryKillerR\fmemoryKiller\x12!\n" +
	"\fmin_replicas\x18\x04 \x01(\rR\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x05 \x01(\rR\vmaxReplicas\x123\n" +
	"\bstrategy\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bstrategy\x12\x16\n" +
	"\x06queues\x18\a \x01(\tR\x06queues\x12<\n" +
	"\rextra_volumes\x18\b \x01(\v2\x17.google.protobuf.StructR\fextraVolumes\x12G\n" +
	"\x13extra_volume_mounts\x18\t \x01(\v2\x17.google.protobuf.StructR\x11extraVolumeMounts\x12.\n" +
	"\x13priority_class_name\x18\n" +
	" \x01(\tR\x11priorityClassName\x12.\n" +
	"\x03hpa\x18\v \x01(\v2\x1c.charts.values.v1.SidekiqHpaR\x03hpa\x121\n" +
	"\x04keda\x18\f \x01(\v2\x1d.charts.values.v1.SidekiqKedaR\x04keda\x127\n" +
	"\x06common\x18\r \x01(\v2\x1f.charts.values.v1.SidekiqCommonR\x06common\x126\n" +
	"\n" +
	"pod_labels\x18\x0e \x01(\v2\x17.google.protobuf.StructR\tpodLabels\x12G\n" +
	" termination_grace_period_seconds\x18\x0f \x01(\rR\x1dterminationGracePeriodSeconds\x12<\n" +
	"\rnode_selector\x18\x10 \x01(\v2\x17.google.protobuf.StructR\fnodeSelector\x129\n" +
	"\vtolerations\x18\x11 \x03(\v2\x17.google.protobuf.StructR\vtolerations:\x04\x88\xb5\x18\x01\"=\n" +
	"\x1bSidekiqMicrosoftGraphMailer\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled:\x04\x88\xb5\x18\x01\"P\n" +
	"\x14SidekiqIncomingEmail\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress:\x04\x88\xb5\x18\x01\"S\n" +
	"\x17SidekiqServiceDeskEmail\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress:\x04\x88\xb5\x18\x01\"\xc2\x01\n" +
	"\x14SidekiqObjectStorage\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\x0eproxy_download\x18\x02 \x01(\bB\x12\x92\xb5\x18\x0eproxy_downloadR\rproxyDownload\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x127\n" +
	"\n" +
	"connection\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"connection:\x04\x88\xb5\x18\x01\"\xbc\x01\n" +
	"\x14SidekiqExternalDiffs\x12\x12\n" +
	"\x04when\x18\x01 \x01(\tR\x04when\x129\n" +
	"\x0eproxy_download\x18\x02 \x01(\bB\x12\x92\xb5\x18\x0eproxy_downloadR\rproxyDownload\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x127\n" +
	"\n" +
	"connection\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"connection:\x04\x88\xb5\x18\x01\"\x88\x01\n" +
	"\x15SidekiqTerraformState\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x127\n" +
	"\n" +
	"connection\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"connection:\x04\x88\xb5\x18\x01\"F\n" +
	"\vSidekiqLdap\x121\n" +
	"\aservers\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aservers:\x04\x88\xb5\x18\x01\"\xf8\x04\n" +
	"\x0fSidekiqOmniauth\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12:\n" +
	"\x1aauto_sign_in_with_provider\x18\x02 \x01(\tR\x16autoSignInWithProvider\x12;\n" +
	"\x1async_profile_from_provider\x18\x03 \x03(\tR\x17syncProfileFromProvider\x126\n" +
	"\x17sync_profile_attributes\x18\x04 \x03(\tR\x15syncProfileAttributes\x12/\n" +
	"\x14allow_single_sign_on\x18\x05 \x03(\tR\x11allowSingleSignOn\x127\n" +
	"\x18block_auto_created_users\x18\x06 \x01(\bR\x15blockAutoCreatedUsers\x12-\n" +
	"\x13auto_link_ldap_user\x18\a \x01(\bR\x10autoLinkLdapUser\x12-\n" +
	"\x13auto_link_saml_user\x18\b \x01(\bR\x10autoLinkSamlUser\x12$\n" +
	"\x0eauto_link_user\x18\t \x03(\tR\fautoLinkUser\x12-\n" +
	"\x12external_providers\x18\n" +
	" \x03(\tR\x11externalProviders\x125\n" +
	"\x17allow_bypass_two_factor\x18\v \x03(\tR\x14allowBypassTwoFactor\x12@\n" +
	"\tproviders\x18\f \x03(\v2\".charts.values.v1.SidekiqSecretRefR\tproviders:\x04\x88\xb5\x18\x01\"\x9e\x01\n" +
	"\rSidekiqSentry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\x129\n" +
	"\x0eclientside_dsn\x18\x03 \x01(\tB\x12\x92\xb5\x18\x0eclientside_dsnR\rclientsideDsn\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment:\x04\x88\xb5\x18\x01\"B\n" +
	"\x10SidekiqSecretRef\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key:\x04\x88\xb5\x18\x01BJZHgitlab.com/gitlab-org/charts/gitlab/pkg/values/charts/values/v1;valuesv1b\x06proto3"

var (
	file_charts_values_v1_sidekiq_proto_rawDescOnce sync.Once
	file_charts_values_v1_sidekiq_proto_rawDescData []byte
)

func file_charts_values_v1_sidekiq_proto_rawDescGZIP() []byte {
	file_charts_values_v1_sidekiq_proto_rawDescOnce.Do(func() {
		file_charts_values_v1_sidekiq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_charts_values_v1_sidekiq_proto_rawDesc), len(file_charts_values_v1_sidekiq_proto_rawDesc)))
	})
	return file_charts_values_v1_sidekiq_proto_rawDescData
}

var file_charts_values_v1_sidekiq_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_charts_values_v1_sidekiq_proto_goTypes = []any{
	(*SidekiqValues)(nil),               // 0: charts.values.v1.SidekiqValues
	(*SidekiqInit)(nil),                 // 1: charts.values.v1.SidekiqInit
	(*SidekiqCommon)(nil),               // 2: charts.values.v1.SidekiqCommon
	(*SidekiqLogging)(nil),              // 3: charts.values.v1.SidekiqLogging
	(*SidekiqNetworkPolicy)(nil),        // 4: charts.values.v1.SidekiqNetworkPolicy
	(*SidekiqNetworkPolicyRuleSet)(nil), // 5: charts.values.v1.SidekiqNetworkPolicyRuleSet
	(*SidekiqMetrics)(nil),              // 6: charts.values.v1.SidekiqMetrics
	(*SidekiqPodMonitor)(nil),           // 7: charts.values.v1.SidekiqPodMonitor
	(*SidekiqMetricsTls)(nil),           // 8: charts.values.v1.SidekiqMetricsTls
	(*SidekiqHealthChecks)(nil),         // 9: charts.values.v1.SidekiqHealthChecks
	(*SidekiqRedis)(nil),                // 10: charts.values.v1.SidekiqRedis
	(*SidekiqMemoryKiller)(nil),         // 11: charts.values.v1.SidekiqMemoryKiller
	(*SidekiqProbe)(nil),                // 12: charts.values.v1.SidekiqProbe
	(*SidekiqGitaly)(nil),               // 13: charts.values.v1.SidekiqGitaly
	(*SidekiqRackAttack)(nil),           // 14: charts.values.v1.SidekiqRackAttack
	(*SidekiqGitBasicAuth)(nil),         // 15: charts.values.v1.SidekiqGitBasicAuth
	(*SidekiqDeployment)(nil),           // 16: charts.values.v1.SidekiqDeployment
	(*SidekiqHpa)(nil),                  // 17: charts.values.v1.SidekiqHpa
	(*SidekiqHpaMetric)(nil),            // 18: charts.values.v1.SidekiqHpaMetric
	(*SidekiqHpaBehavior)(nil),          // 19: charts.values.v1.SidekiqHpaBehavior
	(*SidekiqHpaScaleDown)(nil),         // 20: charts.values.v1.SidekiqHpaScaleDown
	(*SidekiqKeda)(nil),                 // 21: charts.values.v1.SidekiqKeda
	(*SidekiqServiceAccount)(nil),       // 22: charts.values.v1.SidekiqServiceAccount
	(*SidekiqPod)(nil),                  // 23: charts.values.v1.SidekiqPod
	(*SidekiqMicrosoftGraphMailer)(nil), // 24: charts.values.v1.SidekiqMicrosoftGraphMailer
	(*SidekiqIncomingEmail)(nil),        // 25: charts.values.v1.SidekiqIncomingEmail
	(*SidekiqServiceDeskEmail)(nil),     // 26: charts.values.v1.SidekiqServiceDeskEmail
	(*SidekiqObjectStorage)(nil),        // 27: charts.values.v1.SidekiqObjectStorage
	(*SidekiqExternalDiffs)(nil),        // 28: charts.values.v1.SidekiqExternalDiffs
	(*SidekiqTerraformState)(nil),       // 29: charts.values.v1.SidekiqTerraformState
	(*SidekiqLdap)(nil),                 // 30: charts.values.v1.SidekiqLdap
	(*SidekiqOmniauth)(nil),             // 31: charts.values.v1.SidekiqOmniauth
	(*SidekiqSentry)(nil),               // 32: charts.values.v1.SidekiqSentry
	(*SidekiqSecretRef)(nil),            // 33: charts.values.v1.SidekiqSecretRef
	(*structpb.Struct)(nil),             // 34: google.protobuf.Struct
	(*GlobalConfig)(nil),                // 35: charts.values.v1.GlobalConfig
}
var file_charts_values_v1_sidekiq_proto_depIdxs = []int32{
	34, // 0: charts.values.v1.SidekiqValues.image:type_name -> google.protobuf.Struct
	1,  // 1: charts.values.v1.SidekiqValues.init:type_name -> charts.values.v1.SidekiqInit
	34, // 2: charts.values.v1.SidekiqValues.tolerations:type_name -> google.protobuf.Struct
	34, // 3: charts.values.v1.SidekiqValues.annotations:type_name -> google.protobuf.Struct
	34, // 4: charts.values.v1.SidekiqValues.pod_labels:type_name -> google.protobuf.Struct
	2,  // 5: charts.values.v1.SidekiqValues.common:type_name -> charts.values.v1.SidekiqCommon
	3,  // 6: charts.values.v1.SidekiqValues.logging:type_name -> charts.values.v1.SidekiqLogging
	4,  // 7: charts.values.v1.SidekiqValues.networkpolicy:type_name -> charts.values.v1.SidekiqNetworkPolicy
	6,  // 8: charts.values.v1.SidekiqValues.metrics:type_name -> charts.values.v1.SidekiqMetrics
	9,  // 9: charts.values.v1.SidekiqValues.health_checks:type_name -> charts.values.v1.SidekiqHealthChecks
	10, // 10: charts.values.v1.SidekiqValues.redis:type_name -> charts.values.v1.SidekiqRedis
	34, // 11: charts.values.v1.SidekiqValues.psql:type_name -> google.protobuf.Struct
	11, // 12: charts.values.v1.SidekiqValues.memory_killer:type_name -> charts.values.v1.SidekiqMemoryKiller
	12, // 13: charts.values.v1.SidekiqValues.liveness_probe:type_name -> charts.values.v1.SidekiqProbe
	12, // 14: charts.values.v1.SidekiqValues.readiness_probe:type_name -> charts.values.v1.SidekiqProbe
	35, // 15: charts.values.v1.SidekiqValues.global:type_name -> charts.values.v1.GlobalConfig
	13, // 16: charts.values.v1.SidekiqValues.gitaly:type_name -> charts.values.v1.SidekiqGitaly
	34, // 17: charts.values.v1.SidekiqValues.extra:type_name -> google.protobuf.Struct
	34, // 18: charts.values.v1.SidekiqValues.extra_env:type_name -> google.protobuf.Struct
	14, // 19: charts.values.v1.SidekiqValues.rack_attack:type_name -> charts.values.v1.SidekiqRackAttack
	16, // 20: charts.values.v1.SidekiqValues.deployment:type_name -> charts.values.v1.SidekiqDeployment
	17, // 21: charts.values.v1.SidekiqValues.hpa:type_name -> charts.values.v1.SidekiqHpa
	21, // 22: charts.values.v1.SidekiqValues.keda:type_name -> charts.values.v1.SidekiqKeda
	34, // 23: charts.values.v1.SidekiqValues.resources:type_name -> google.protobuf.Struct
	23, // 24: charts.values.v1.SidekiqValues.pods:type_name -> charts.values.v1.SidekiqPod
	34, // 25: charts.values.v1.SidekiqValues.security_context:type_name -> google.protobuf.Struct
	34, // 26: charts.values.v1.SidekiqValues.container_security_context:type_name -> google.protobuf.Struct
	22, // 27: charts.values.v1.SidekiqValues.service_account:type_name -> charts.values.v1.SidekiqServiceAccount
	34, // 28: charts.values.v1.SidekiqValues.affinity:type_name -> google.protobuf.Struct
	34, // 29: charts.values.v1.SidekiqValues.topology_spread_constraints:type_name -> google.protobuf.Struct
	34, // 30: charts.values.v1.SidekiqInit.image:type_name -> google.protobuf.Struct
	34, // 31: charts.values.v1.SidekiqInit.resources:type_name -> google.protobuf.Struct
	34, // 32: charts.values.v1.SidekiqInit.container_security_context:type_name -> google.protobuf.Struct
	34, // 33: charts.values.v1.SidekiqCommon.labels:type_name -> google.protobuf.Struct
	5,  // 34: charts.values.v1.SidekiqNetworkPolicy.egress:type_name -> charts.values.v1.SidekiqNetworkPolicyRuleSet
	5,  // 35: charts.values.v1.SidekiqNetworkPolicy.ingress:type_name -> charts.values.v1.SidekiqNetworkPolicyRuleSet
	34, // 36: charts.values.v1.SidekiqNetworkPolicy.annotations:type_name -> google.protobuf.Struct
	34, // 37: charts.values.v1.SidekiqNetworkPolicyRuleSet.rules:type_name -> google.protobuf.Struct
	7,  // 38: charts.values.v1.SidekiqMetrics.pod_monitor:type_name -> charts.values.v1.SidekiqPodMonitor
	34, // 39: charts.values.v1.SidekiqMetrics.annotations:type_name -> google.protobuf.Struct
	8,  // 40: charts.values.v1.SidekiqMetrics.tls:type_name -> charts.values.v1.SidekiqMetricsTls
	34, // 41: charts.values.v1.SidekiqPodMonitor.additional_labels:type_name -> google.protobuf.Struct
	34, // 42: charts.values.v1.SidekiqPodMonitor.endpoint_config:type_name -> google.protobuf.Struct
	34, // 43: charts.values.v1.SidekiqRedis.auth:type_name -> google.protobuf.Struct
	34, // 44: charts.values.v1.SidekiqGitaly.auth_token:type_name -> google.protobuf.Struct
	15, // 45: charts.values.v1.SidekiqRackAttack.git_basic_auth:type_name -> charts.values.v1.SidekiqGitBasicAuth
	34, // 46: charts.values.v1.SidekiqDeployment.strategy:type_name -> google.protobuf.Struct
	18, // 47: charts.values.v1.SidekiqHpa.cpu:type_name -> charts.values.v1.SidekiqHpaMetric
	34, // 48: charts.values.v1.SidekiqHpa.custom_metrics:type_name -> google.protobuf.Struct
	19, // 49: charts.values.v1.SidekiqHpa.behavior:type_name -> charts.values.v1.SidekiqHpaBehavior
	20, // 50: charts.values.v1.SidekiqHpaBehavior.scale_down:type_name -> charts.values.v1.SidekiqHpaScaleDown
	34, // 51: charts.values.v1.SidekiqServiceAccount.annotations:type_name -> google.protobuf.Struct
	11, // 52: charts.values.v1.SidekiqPod.memory_killer:type_name -> charts.values.v1.SidekiqMemoryKiller
	34, // 53: charts.values.v1.SidekiqPod.strategy:type_name -> google.protobuf.Struct
	34, // 54: charts.values.v1.SidekiqPod.extra_volumes:type_name -> google.protobuf.Struct
	34, // 55: charts.values.v1.SidekiqPod.extra_volume_mounts:type_name -> google.protobuf.Struct
	17, // 56: charts.values.v1.SidekiqPod.hpa:type_name -> charts.values.v1.SidekiqHpa
	21, // 57: charts.values.v1.SidekiqPod.keda:type_name -> charts.values.v1.SidekiqKeda
	2,  // 58: charts.values.v1.SidekiqPod.common:type_name -> charts.values.v1.SidekiqCommon
	34, // 59: charts.values.v1.SidekiqPod.pod_labels:type_name -> google.protobuf.Struct
	34, // 60: charts.values.v1.SidekiqPod.node_selector:type_name -> google.protobuf.Struct
	34, // 61: charts.values.v1.SidekiqPod.tolerations:type_name -> google.protobuf.Struct
	34, // 62: charts.values.v1.SidekiqObjectStorage.connection:type_name -> google.protobuf.Struct
	34, // 63: charts.values.v1.SidekiqExternalDiffs.connection:type_name -> google.protobuf.Struct
	34, // 64: charts.values.v1.SidekiqTerraformState.connection:type_name -> google.protobuf.Struct
	34, // 65: charts.values.v1.SidekiqLdap.servers:type_name -> google.protobuf.Struct
	33, // 66: charts.values.v1.SidekiqOmniauth.providers:type_name -> charts.values.v1.SidekiqSecretRef
	67, // [67:67] is the sub-list for method output_type
	67, // [67:67] is the sub-list for method input_type
	67, // [67:67] is the sub-list for extension type_name
	67, // [67:67] is the sub-list for extension extendee
	0,  // [0:67] is the sub-list for field type_name
}

func init() { file_charts_values_v1_sidekiq_proto_init() }
func file_charts_values_v1_sidekiq_proto_init() {
	if File_charts_values_v1_sidekiq_proto != nil {
		return
	}
	file_charts_values_v1_global_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_charts_values_v1_sidekiq_proto_rawDesc), len(file_charts_values_v1_sidekiq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_charts_values_v1_sidekiq_proto_goTypes,
		DependencyIndexes: file_charts_values_v1_sidekiq_proto_depIdxs,
		MessageInfos:      file_charts_values_v1_sidekiq_proto_msgTypes,
	}.Build()
	File_charts_values_v1_sidekiq_proto = out.File
	file_charts_values_v1_sidekiq_proto_goTypes = nil
	file_charts_values_v1_sidekiq_proto_depIdxs = nil
}
