.kubeconform:
  stage: test
  when: always
  script:
    - kubectl version --client=true --output=json
    - helm version --template='{{.Version}}'
    - helm plugin list
    - helm repo add gitlab https://charts.gitlab.io
    - helm dependency update
    - echo "$HELM_DEFAULT_SETTINGS" | tee ./template_settings.yaml
    - echo "${KUBECONFORM_SCHEMA_LOCATION:-default}"
    - >
      helm kubeconform --strict --summary
      -f ./template_settings.yaml
      --kubernetes-version $KUBE_VERSION
      --schema-location "${KUBECONFORM_SCHEMA_LOCATION:-default}"
      --schema-location "$KUBE_CRD_SCHEMA_URL"
      --output json
      .
  rules:
    - if: '$PIPELINE_TYPE =~ /_MR_PIPELINE$/'
    - if: '$PIPELINE_TYPE =~ /_BRANCH_PIPELINE$/'
    - if: '$PIPELINE_TYPE == "NIGHTLY_PIPELINE"'
kubeconform:
  extends: .kubeconform
  parallel:
    matrix:
      - KUBE_VERSION:
        - 1.33.13
        - 1.34.9
        - 1.35.6
        - 1.36.2
      - KUBE_VERSION: "1.36.2"
        HELM_MINOR_VERSION: "3.20"
