cleanup:review-apps:gke135:
  stage: cleanup
  variables:
    AGENT_NAME: "gke135-ci-cluster"
    NAMESPACE: helm-charts-win
    DAYS_AGO: 2
    FILTER: rvw
    DRY_RUN: ""
  environment:
    name: gke135_review/scheduled-cleanup
    action: access
  before_script:
    - apt-get update -qq && apt-get install -y -qq jq
  script:
    - source scripts/ci/autodevops.sh
    - set_context
    - FILTER="$FILTER" NAMESPACE="$NAMESPACE" DAYS_AGO="$DAYS_AGO" DRY_RUN="$DRY_RUN" scripts/ci/cleanup-old-helm-releases.sh reap
    - NAMESPACE="$NAMESPACE" DRY_RUN="$DRY_RUN" scripts/ci/cleanup-ghost-resources.sh reap
  rules:
    - if: '$PIPELINE_TYPE == "CLEANUP_REVIEW_APPS_PIPELINE"'

cleanup:review-apps:eks134:
  stage: cleanup
  variables:
    AGENT_NAME: "eks134-ci-cluster"
    NAMESPACE: eks-helm-charts-win
    DAYS_AGO: 2
    FILTER: rvw
    DRY_RUN: ""
  environment:
    name: eks134_review/scheduled-cleanup
    action: access
  before_script:
    - apt-get update -qq && apt-get install -y -qq jq
  script:
    - source scripts/ci/autodevops.sh
    - set_context
    - FILTER="$FILTER" NAMESPACE="$NAMESPACE" DAYS_AGO="$DAYS_AGO" DRY_RUN="$DRY_RUN" scripts/ci/cleanup-old-helm-releases.sh reap
    - NAMESPACE="$NAMESPACE" DRY_RUN="$DRY_RUN" scripts/ci/cleanup-ghost-resources.sh reap
  rules:
    - if: '$PIPELINE_TYPE == "CLEANUP_REVIEW_APPS_PIPELINE"'
